plugin.audio.soundcloud/addon.xml, plugin.audio.soundcloud/changelog.txt, plugin.audio.soundcloud/resources/lib/kodion/__init__.py, plugin.audio.soundcloud/resources/lib/kodion/abstract_provider.py, plugin.audio.soundcloud/resources/lib/kodion/constants/const_settings.py, plugin.audio.soundcloud/resources/lib/kodion/exceptions.py, plugin.audio.soundcloud/resources/lib/kodion/impl/abstract_settings.py, plugin.audio.soundcloud/resources/lib/kodion/impl/mock/mock_runner.py, plugin.audio.soundcloud/resources/lib/kodion/impl/xbmc/xbmc_items.py, plugin.audio.soundcloud/resources/lib/kodion/impl/xbmc/xbmc_runner.py, plugin.audio.soundcloud/resources/lib/kodion/iso8601.py, plugin.audio.soundcloud/resources/lib/kodion/items/__init__.py, plugin.audio.soundcloud/resources/lib/kodion/items/favorites_item.py, plugin.audio.soundcloud/resources/lib/kodion/items/new_search_item.py, plugin.audio.soundcloud/resources/lib/kodion/items/next_page_item.py, plugin.audio.soundcloud/resources/lib/kodion/items/search_history_item.py, plugin.audio.soundcloud/resources/lib/kodion/items/search_item.py, plugin.audio.soundcloud/resources/lib/kodion/items/uri_item.py, plugin.audio.soundcloud/resources/lib/kodion/items/watch_later_item.py, plugin.audio.soundcloud/resources/lib/kodion/runner.py, plugin.audio.soundcloud/resources/lib/kodion/simple_requests/__init__.py, plugin.audio.soundcloud/resources/lib/kodion/simple_requests/api.py, plugin.audio.soundcloud/resources/lib/kodion/simple_requests/constants/__init__.py, plugin.audio.soundcloud/resources/lib/kodion/simple_requests/constants/codes.py, plugin.audio.soundcloud/resources/lib/soundcloud/client.py, plugin.audio.soundcloud/resources/lib/soundcloud/provider.py, plugin.audio.soundcloud/resources/lib/test_soundcloud/test_provider.py
UPD: dropped dependency of 'requests'-module because of performance issues
=> [plugin.audio.soundcloud] 1.1.1

plugin.video.rtl-now.de/addon.xml, plugin.video.rtl-now.de/changelog.txt, plugin.video.rtl-now.de/resources/lib/rtlinteractive/client.py, plugin.video.rtl-now.de/resources/lib/rtlinteractive/provider.py, plugin.video.rtl-now.de/resources/lib/test/test_client.py
FIX: playback based on web-page changes
=> [plugin.video.rtl-now.de] 2.1.2

plugin.video.rtl2-now.de/addon.xml, plugin.video.rtl2-now.de/changelog.txt, plugin.video.rtl2-now.de/resources/lib/rtlinteractive/client.py, plugin.video.rtl2-now.de/resources/lib/rtlinteractive/provider.py
FIX: playback based on web-page changes
=> [plugin.video.rtl2-now.de] 2.1.2

plugin.video.vox-now.de/addon.xml, plugin.video.vox-now.de/changelog.txt, plugin.video.vox-now.de/resources/lib/rtlinteractive/client.py, plugin.video.vox-now.de/resources/lib/rtlinteractive/provider.py
FIX: playback based on web-page changes
=> [plugin.video.vox-now.de] 2.1.2

plugin.video.ntv-now.de/addon.xml, plugin.video.ntv-now.de/changelog.txt, plugin.video.ntv-now.de/resources/lib/rtlinteractive/client.py, plugin.video.ntv-now.de/resources/lib/test/test_client.py
FIX: playback based on web-page changes
=> [plugin.video.ntv-now.de] 2.1.2

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/language/Polish/strings.xml, plugin.video.youtube/resources/language/Russian/strings.xml, plugin.video.youtube/resources/lib/test_youtube/test_client.py, plugin.video.youtube/resources/lib/youtube/helper/video_info.py
UPD: Polish (thx 2 Etharr)
UPD: Russian (thx 2 BytEvil)
FIX: improved playback
=> [plugin.video.youtube] 5.0.8

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/lib/kodion/__init__.py, plugin.video.youtube/resources/lib/kodion/debug.py, plugin.video.youtube/resources/lib/kodion/impl/abstract_settings.py, plugin.video.youtube/resources/lib/kodion/impl/abstract_system_version.py, plugin.video.youtube/resources/lib/kodion/impl/mock/mock_context.py, plugin.video.youtube/resources/lib/kodion/impl/mock/mock_system_version.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/info_labels.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_context.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_items.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_system_version.py, plugin.video.youtube/resources/lib/kodion/iso8601.py, plugin.video.youtube/resources/lib/test_youtube/test_client.py, plugin.video.youtube/resources/lib/test_youtube/test_provider.py, plugin.video.youtube/resources/lib/youtube/client/youtube.py, plugin.video.youtube/resources/lib/youtube/helper/utils.py, plugin.video.youtube/resources/lib/youtube/helper/video_info.py, plugin.video.youtube/resources/lib/youtube/provider.py
ADD: 'duration' optimized for KODI 15.X (Isengard)
ADD: EndPoint for listing the videos of a playlist: "plugin://plugin.video.youtube/playlist/<PLAYLIST_ID>/"
UPD: optimized client-/server transfer (use gzip)
=> [plugin.video.youtube] 5.0.9

plugin.video.glwiz/addon.xml, plugin.video.glwiz/default.py
=> [plugin.video.glwiz] 1.1.3

plugin.video.golem.de/addon.xml, plugin.video.golem.de/changelog.txt, plugin.video.golem.de/resources/language/English/strings.xml, plugin.video.golem.de/resources/language/German/strings.xml, plugin.video.golem.de/resources/lib/golem_de/provider.py, plugin.video.golem.de/resources/lib/kodion/__init__.py, plugin.video.golem.de/resources/lib/kodion/debug.py, plugin.video.golem.de/resources/lib/kodion/impl/abstract_system_version.py, plugin.video.golem.de/resources/lib/kodion/impl/mock/mock_context.py, plugin.video.golem.de/resources/lib/kodion/impl/mock/mock_system_version.py, plugin.video.golem.de/resources/lib/kodion/impl/xbmc/info_labels.py, plugin.video.golem.de/resources/lib/kodion/impl/xbmc/xbmc_context.py, plugin.video.golem.de/resources/lib/kodion/impl/xbmc/xbmc_context_ui.py, plugin.video.golem.de/resources/lib/kodion/impl/xbmc/xbmc_items.py, plugin.video.golem.de/resources/lib/kodion/impl/xbmc/xbmc_runner.py, plugin.video.golem.de/resources/lib/kodion/impl/xbmc/xbmc_system_version.py, plugin.video.golem.de/resources/lib/kodion/items/audio_item.py, plugin.video.golem.de/resources/lib/kodion/items/base_item.py, plugin.video.golem.de/resources/lib/kodion/items/video_item.py, plugin.video.golem.de/resources/lib/kodion/utils/__init__.py, plugin.video.golem.de/resources/lib/kodion/utils/datetime_parser.py, plugin.video.golem.de/resources/lib/kodion/utils/storage.py, plugin.video.golem.de/resources/lib/kodion/utils/view_manager.py, plugin.video.golem.de/resources/lib/test_golem_de/test_client.py, plugin.video.golem.de/resources/lib/test_golem_de/test_provider.py
ADD: Category 'Wochenrückblick' (en: 'Week in Review')
ADD: Category 'Trailer'
UPD: improved support for Gotham, Helix and Isengard
=> [plugin.video.golem.de] 1.1.0

plugin.video.focus-online.de/addon.xml, plugin.video.focus-online.de/changelog.txt, plugin.video.focus-online.de/resources/lib/focus/client.py, plugin.video.focus-online.de/resources/lib/focus/provider.py, plugin.video.focus-online.de/resources/settings.xml
ADD: support for 1080p (default 720p)
UPD: improved video stream support
=> [plugin.video.focus-online.de] 1.1.1

plugin.video.7tv/addon.xml, plugin.video.7tv/changelog.txt, plugin.video.7tv/resources/lib/prosiebensat1/provider.py
FIX: improve playback on ARM systems
=> [plugin.video.7tv] 2.2.1

plugin.video.vimeo/addon.xml, plugin.video.vimeo/changelog.txt, plugin.video.vimeo/resources/lib/kodion/__init__.py, plugin.video.vimeo/resources/lib/kodion/simple_requests/__init__.py, plugin.video.vimeo/resources/lib/kodion/simple_requests/api.py, plugin.video.vimeo/resources/lib/kodion/utils/storage.py, plugin.video.vimeo/resources/lib/test_vimeo/test_client.py, plugin.video.vimeo/resources/lib/vimeo/client.py
FIX: login (encoding issues)
FIX: updating search history
=> [plugin.video.vimeo] 4.1.1

plugin.video.rtl2-now.de/addon.xml, plugin.video.rtl2-now.de/changelog.txt, plugin.video.rtl2-now.de/resources/lib/rtlinteractive/client.py
FIX: playback (based on DRM protection)
=> [plugin.video.rtl2-now.de] 2.2.2

plugin.video.vox-now.de/addon.xml, plugin.video.vox-now.de/changelog.txt, plugin.video.vox-now.de/resources/lib/rtlinteractive/client.py
FIX: playback (based on DRM protection)
=> [plugin.video.vox-now.de] 2.2.2

plugin.video.rtl-now.de/addon.xml, plugin.video.rtl-now.de/changelog.txt, plugin.video.rtl-now.de/resources/lib/rtlinteractive/client.py
FIX: playback (based on DRM protection)
=> [plugin.video.rtl-now.de] 2.2.2

plugin.video.golem.de/addon.xml, plugin.video.golem.de/changelog.txt, plugin.video.golem.de/resources/language/English/strings.xml, plugin.video.golem.de/resources/language/German/strings.xml, plugin.video.golem.de/resources/lib/golem_de/provider.py, plugin.video.golem.de/resources/lib/kodion/__init__.py, plugin.video.golem.de/resources/lib/kodion/abstract_provider.py, plugin.video.golem.de/resources/lib/kodion/impl/abstract_context_ui.py, plugin.video.golem.de/resources/lib/kodion/impl/mock/mock_context_ui.py, plugin.video.golem.de/resources/lib/kodion/impl/mock/mock_progress_dialog.py, plugin.video.golem.de/resources/lib/kodion/impl/xbmc/xbmc_context_ui.py, plugin.video.golem.de/resources/lib/kodion/items/directory_item.py, plugin.video.golem.de/resources/lib/kodion/runner.py, plugin.video.golem.de/resources/lib/kodion/simple_requests/__init__.py, plugin.video.golem.de/resources/lib/kodion/simple_requests/api.py, plugin.video.golem.de/resources/lib/kodion/utils/function_cache.py, plugin.video.golem.de/resources/lib/kodion/utils/storage.py
ADD: Category 'Hersteller-Videos' (en: 'Manufacturer videos')
UPD: improved performance
FIX: search wasn't working
=> [plugin.video.golem.de] 1.2.0

plugin.video.clipfish.de/addon.xml, plugin.video.clipfish.de/changelog.txt, plugin.video.clipfish.de/resources/lib/clipfish/client.py, plugin.video.clipfish.de/resources/lib/clipfish/provider.py, plugin.video.clipfish.de/resources/lib/kodion/__init__.py, plugin.video.clipfish.de/resources/lib/kodion/abstract_provider.py, plugin.video.clipfish.de/resources/lib/kodion/impl/abstract_context_ui.py, plugin.video.clipfish.de/resources/lib/kodion/impl/mock/mock_context_ui.py, plugin.video.clipfish.de/resources/lib/kodion/impl/mock/mock_progress_dialog.py, plugin.video.clipfish.de/resources/lib/kodion/impl/xbmc/xbmc_context_ui.py, plugin.video.clipfish.de/resources/lib/kodion/items/directory_item.py, plugin.video.clipfish.de/resources/lib/kodion/runner.py, plugin.video.clipfish.de/resources/lib/kodion/simple_requests/__init__.py, plugin.video.clipfish.de/resources/lib/kodion/simple_requests/api.py, plugin.video.clipfish.de/resources/lib/kodion/utils/function_cache.py, plugin.video.clipfish.de/resources/lib/kodion/utils/storage.py, plugin.video.clipfish.de/resources/lib/test_clipfish/test_client.py
UPD: improved playback. Working with the id of the video, so videos stay watched
=> [plugin.video.clipfish.de] 1.1.1

plugin.video.redbull.tv/addon.xml, plugin.video.redbull.tv/changelog.txt, plugin.video.redbull.tv/resources/language/English/strings.xml, plugin.video.redbull.tv/resources/language/German/strings.xml, plugin.video.redbull.tv/resources/lib/kodion/__init__.py, plugin.video.redbull.tv/resources/lib/kodion/impl/abstract_context.py, plugin.video.redbull.tv/resources/lib/kodion/impl/xbmc/xbmc_context.py, plugin.video.redbull.tv/resources/lib/redbull_tv/client.py, plugin.video.redbull.tv/resources/lib/redbull_tv/provider.py, plugin.video.redbull.tv/resources/lib/test_redbull_tv/test_client.py, plugin.video.redbull.tv/resources/lib/test_redbull_tv/test_provider.py
ADD: support for 'Live' events
ADD: support for 'Replays' and 'Upcoming' events
ADD: 'Latest Films' (Red Bull TV)
ADD: 'Recently Added' (Red Bull TV)
FIX: show correct 'Featured Shows' (Red Bull TV)
FIX: corrected url for 'Featured' (Red Bull TV)
=> [plugin.video.redbull.tv] 1.1.0

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/lib/kodion/__init__.py, plugin.video.youtube/resources/lib/kodion/abstract_provider.py, plugin.video.youtube/resources/lib/kodion/constants/__init__.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_context.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_context_ui.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_playlist.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_runner.py, plugin.video.youtube/resources/lib/kodion/impl/xbmc/xbmc_system_version.py, plugin.video.youtube/resources/lib/kodion/items/utils.py, plugin.video.youtube/resources/lib/kodion/utils/datetime_parser.py, plugin.video.youtube/resources/lib/kodion/utils/favorite_list.py, plugin.video.youtube/resources/lib/kodion/utils/function_cache.py, plugin.video.youtube/resources/lib/kodion/utils/storage.py, plugin.video.youtube/resources/lib/kodion/utils/watch_later_list.py, plugin.video.youtube/resources/lib/youtube/helper/video_info.py, plugin.video.youtube/resources/lib/youtube/helper/yt_old_actions.py, plugin.video.youtube/resources/lib/youtube/helper/yt_setup_wizard.py
Found a little bug...only a problem for newcomers.
=> [plugin.video.youtube] 5.1.3

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/lib/test_youtube/test_client.py, plugin.video.youtube/resources/lib/youtube/client/login_client.py, plugin.video.youtube/resources/lib/youtube/client/youtube.py, plugin.video.youtube/resources/lib/youtube/helper/v3.py, plugin.video.youtube/resources/lib/youtube/helper/yt_old_actions.py
UPD: remove deprecation warning for Isengard
FIX: Issue 7163 (Missing pagination for subscriptions - YouTube APIv3 bug)
=> [plugin.video.youtube] 5.1.5

plugin.video.vimeo/addon.xml, plugin.video.vimeo/changelog.txt, plugin.video.vimeo/resources/lib/kodion/__init__.py, plugin.video.vimeo/resources/lib/kodion/impl/abstract_context.py, plugin.video.vimeo/resources/lib/kodion/simple_requests/api.py, plugin.video.vimeo/resources/lib/kodion/utils/search_history.py, plugin.video.vimeo/resources/lib/test_vimeo/test_client.py, plugin.video.vimeo/resources/lib/test_vimeo/test_provider.py, plugin.video.vimeo/resources/lib/vimeo/client.py
=> [plugin.video.vimeo] 4.1.4

plugin.video.manoto/addon.xml, plugin.video.manoto/default.py, plugin.video.manoto/resources/settings.xml
=> [plugin.video.manoto] 1.2.0

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/language/Chinese (Traditional)/strings.xml, plugin.video.youtube/resources/language/Czech/strings.xml, plugin.video.youtube/resources/language/Polish/strings.xml, plugin.video.youtube/resources/language/Romanian/strings.xml, plugin.video.youtube/resources/lib/kodion/__init__.py, plugin.video.youtube/resources/lib/kodion/constants/const_log.py, plugin.video.youtube/resources/lib/kodion/impl/abstract_context.py, plugin.video.youtube/resources/lib/kodion/simple_requests/api.py, plugin.video.youtube/resources/lib/kodion/utils/search_history.py, plugin.video.youtube/resources/lib/test_youtube/test_client.py, plugin.video.youtube/resources/lib/test_youtube/test_provider.py, plugin.video.youtube/resources/lib/youtube/client/youtube.py, plugin.video.youtube/resources/lib/youtube/helper/tv.py, plugin.video.youtube/resources/lib/youtube/helper/url_to_item_converter.py, plugin.video.youtube/resources/lib/youtube/helper/video_info.py, plugin.video.youtube/resources/lib/youtube/helper/yt_specials.py, plugin.video.youtube/resources/lib/youtube/provider.py
ADD: Chinese (Traditional) (thx 2 beddfaf916)
ADD: Czech (thx 2 tomaswcz)
ADD: Romanian (thx 2 Danny3)
UPD: test some new pagination for 'My Subscriptions'
UPD: Polish (thx 2 Etharr)
FIX: show notification again for unsupported rtmpe streams
FIX: unicode/utf-8 trouble in kodion
=> [plugin.video.youtube] 5.1.6

plugin.video.nowtv.de/addon.xml, plugin.video.nowtv.de/changelog.txt, plugin.video.nowtv.de/resources/language/English/strings.xml, plugin.video.nowtv.de/resources/language/German/strings.xml, plugin.video.nowtv.de/resources/lib/kodion/__init__.py, plugin.video.nowtv.de/resources/lib/kodion/simple_requests/__init__.py, plugin.video.nowtv.de/resources/lib/kodion/simple_requests/api.py, plugin.video.nowtv.de/resources/lib/nowtv/client.py, plugin.video.nowtv.de/resources/lib/nowtv/provider.py, plugin.video.nowtv.de/resources/lib/test/test_client.py, plugin.video.nowtv.de/resources/lib/test/test_provider.py, plugin.video.nowtv.de/resources/settings.xml
ADD: support for payed content
ADD: Managing playlists (watch later) via the login (add and remove)
ADD: Managing favorites via the login (add and remove)
ADD: Date-spans and correct tab handling
UPD: only show free content if you're not logged in.
FIX: add format to addon favs.
FIX: script error while trying to load a format (bug of the web page)
FIX: script error while trying to load the thumbnail of an episode
FIX: some crashes
FIX: german localization (thx 2 ultrara1n)
=> [plugin.video.nowtv.de] 1.0.2

plugin.video.syfy/README.txt, plugin.video.syfy/addon.xml, plugin.video.syfy/changelog.txt, plugin.video.syfy/default.py
Hopefully this will create just one pull request for the current commit of the syfy addon
=> [plugin.video.syfy] 1.0.8

plugin.video.syfy/README.txt, plugin.video.syfy/addon.xml, plugin.video.syfy/changelog.txt, plugin.video.syfy/default.py
=> [plugin.video.syfy] 1.0.9

plugin.video.fyi/README.txt, plugin.video.fyi/addon.xml, plugin.video.fyi/changelog.txt, plugin.video.fyi/default.py
=> [plugin.video.fyi] 1.0.2

plugin.video.sprout/README.txt, plugin.video.sprout/addon.xml, plugin.video.sprout/changelog.txt, plugin.video.sprout/default.py
sorry about last PR, forgot to rebase
=> [plugin.video.sprout] 1.0.11

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/default.py, plugin.video.wnbc/readme.txt
Sorry about the screwed up previous PRs, too impatient to wait for rebase to finish I guess. Hopefully this batch will be ok.
=> [plugin.video.wnbc] 1.0.12

plugin.video.metv/README.txt, plugin.video.metv/addon.xml, plugin.video.metv/changelog.txt, plugin.video.metv/default.py
=> [plugin.video.metv] 1.4.4

plugin.video.cbc/README.txt, plugin.video.cbc/addon.xml, plugin.video.cbc/changelog.txt, plugin.video.cbc/default.py
Sorry for issuing another pull request. Nasty unicode error in Canadian English.
=> [plugin.video.cbc] 2.0.6

plugin.video.cbsn/README.txt, plugin.video.cbsn/addon.xml, plugin.video.cbsn/changelog.txt, plugin.video.cbsn/default.py
and, of course, there's a website change after all the previous PRs on this - sorry
=> [plugin.video.cbsn] 2.0.3

plugin.video.cbc/addon.xml
Mark 1.0.x version in Gotham branch as "broken"
=> [plugin.video.cbc] 1.0.14

plugin.video.wral/addon.xml
Mark 1.0.x version in Gotham branch as "broken"
=> [plugin.video.wral] 1.0.6

plugin.video.i24News/addon.xml
=> [plugin.video.i24News] 1.0.5 mark as broken

plugin.video.ifc/addon.xml
=> [plugin.video.ifc] 1.0.2 mark as broken

plugin.video.linktv/addon.xml
=> [plugin.video.linktv] 1.0.3 mark as broken

plugin.video.tubitv/README.txt, plugin.video.tubitv/addon.xml, plugin.video.tubitv/changelog.txt, plugin.video.tubitv/default.py
Sorry for quick update, the website changed again.
=> [plugin.video.tubitv] 2.0.7

plugin.video.manoto/addon.xml, plugin.video.manoto/default.py
- domain name updated to match the new SSL certificate used
Thanks :)
=> [plugin.video.manoto] 1.2.1

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/default.py
version is a bit screwed in the branch name, should be plugin.video.thinktv 2.0.7. Don't think it makes a difference for the pull though. If it does let me know. Thanks
=> [plugin.video.thinktv] 2.0.7

plugin.video.thenewboston/README.markdown, plugin.video.thenewboston/addon.xml, plugin.video.thenewboston/changelog.txt, plugin.video.thenewboston/requirements.txt, plugin.video.thenewboston/resources/lib/tnb.py, plugin.video.thenewboston/test.py
=> [plugin.video.thenewboston] 1.1.3

plugin.video.tubitv/addon.xml
=> [plugin.video.tubitv] 2.0.8 mark as broken

plugin.video.syfy/addon.xml
I screwed up the addon version in last PR - should be 3.0.1, NOT 2.0.4
=> [plugin.video.syfy] 3.0.1a

plugin.video.jeuxvideo.com/addon.py, plugin.video.jeuxvideo.com/addon.xml, plugin.video.jeuxvideo.com/changelog.txt, plugin.video.jeuxvideo.com/resources/language/English/strings.xml, plugin.video.jeuxvideo.com/resources/language/French/strings.xml
Addon is currently broken as the API it used is dropped (404).
=> [plugin.video.jeuxvideo.com] 1.2.0

plugin.video.wabc/addon.xml, plugin.video.wabc/changelog.txt, plugin.video.wabc/default.py, plugin.video.wabc/lib/scraper.py, plugin.video.wabc/readme.txt
=> [plugin.video.wabc] 3.0.3

plugin.video.on_aol/addon.xml, plugin.video.on_aol/changelog.txt, plugin.video.on_aol/default.py, plugin.video.on_aol/resources/language/English/strings.po, plugin.video.on_aol/resources/language/English/strings.xml
Fix an encoding mix-up and add strings.po file.
@learningit  This looks better, I think.
Thanks.
=> [plugin.video.on_aol] 1.1.1

plugin.video.wnbc/addon.xml
Sorry missed that there was a typo in the plugin name
=> [plugin.video.wnbc] 3.0.3 fix addon.xml

plugin.video.eso/.gitignore, plugin.video.eso/addon.xml, plugin.video.eso/changelog.txt, plugin.video.eso/default.py, plugin.video.eso/resources/settings.xml
Changelog for plugin.video.eso at Gotham:
1.0.6 (2016.04.01)
- Fixed video parser due to website changes.
- Support for Ultra HD videos option available from add-on settings menu.
This is my first PR using the new method directly from GitHub, so please, don't hesitate to correct me if i make any mistake.
jamontes.
=> [plugin.video.eso] 1.0.6

plugin.video.rtlxl/addon.py, plugin.video.rtlxl/addon.xml, plugin.video.rtlxl/changelog.txt
=> [plugin.video.rtlxl] 1.1.2

plugin.video.attactv/.gitignore, plugin.video.attactv/addon.xml, plugin.video.attactv/changelog.txt, plugin.video.attactv/default.py
Hi,
This is a new update for attactv add-on over Gotham branch,
Changelog:
1.1.12 (2016.04.03)
- Quick fix on scraper due to Vimeo website changes.
- Code refactoring and cleaning.
Thanks a lot in advance and best regards,
jamontes.
=> [plugin.video.attactv] 1.1.12

plugin.video.on_aol/addon.xml, plugin.video.on_aol/changelog.txt, plugin.video.on_aol/default.py, plugin.video.on_aol/resources/language/English/strings.po, plugin.video.on_aol/resources/settings.xml
Adds support for HLS streams witch seems to be the new default.
=> [plugin.video.on_aol] 1.1.2

plugin.video.digistorageplayer/addon.py, plugin.video.digistorageplayer/addon.xml, plugin.video.digistorageplayer/changelog.txt
=> [plugin.video.digistorageplayer] 1.0.1

plugin.video.tv3play.dk/addon.py, plugin.video.tv3play.dk/addon.xml, plugin.video.tv3play.dk/changelog.txt, plugin.video.tv3play.dk/mtgapi.py
- Fixed crash on Android caused by limited format string support
=> [plugin.video.tv3play.dk] 3.0.2

plugin.video.filmsforaction/.gitignore, plugin.video.filmsforaction/.travis.yml, plugin.video.filmsforaction/addon.xml, plugin.video.filmsforaction/changelog.txt, plugin.video.filmsforaction/resources/lib/ffa_api.py
Hi,
This is a new update of plugin.video.filmsforaction over gotham branch.
Changelog:
1.0.7 (2016.04.05)
- Update Vimeo scraper due to Vimeo website changes.
jamontes.
=> [plugin.video.filmsforaction] 1.0.7

plugin.video.pcloud-video-streaming/.gitignore, plugin.video.pcloud-video-streaming/README.md, plugin.video.pcloud-video-streaming/addon.py, plugin.video.pcloud-video-streaming/addon.xml, plugin.video.pcloud-video-streaming/changelog.txt, plugin.video.pcloud-video-streaming/resources/lib/loginfailedexception.py, plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
FIxed plugin.video.pcloud-video-streaming issue with stale logon credentials.
=> [plugin.video.pcloud-video-streaming] 1.2.3

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py, plugin.video.thinktv/resources/settings.xml
=> [plugin.video.thinktv] 3.0.4

plugin.video.thenewboston/README.markdown, plugin.video.thenewboston/addon.xml, plugin.video.thenewboston/changelog.txt, plugin.video.thenewboston/resources/lib/tnb.py
Version bump to fix a scraper problem, also updated docs a lil' bit.
Thanks!
=> [plugin.video.thenewboston] 1.1.4

plugin.audio.rne/addon.xml, plugin.audio.rne/changelog.txt, plugin.audio.rne/resources/lib/rne_api.py
Hi,
This is a new PR for Helix brach due to a website change.
Changelog:
1.0.7 (2016.05.02)
- Quick fix for direct channels due to website changes (credits: vicglez).
Thanks a lot in advance and best regards,
jamontes.
=> [plugin.audio.rne] 1.0.7

plugin.video.tehnik/INSTALL.txt, plugin.video.tehnik/addon.py, plugin.video.tehnik/addon.xml, plugin.video.tehnik/changelog.txt
Dear All,
I would like to update the plugin described below
addon - plugin.video.tehnik
version - 2.0.6
revision - f7202aff9437619e2bac3d186f9a8ad719069fde
url - https://github.com/deltha/plugin.video.tehnik/
revision - isengard (and above)
Thank you in advance,
Rujinschi Remus
deltha@gmail.com
=> [plugin.video.tehnik] 2.0.6

plugin.video.putio/addon.xml, plugin.video.putio/changelog.txt, plugin.video.putio/main.py, plugin.video.putio/resources/language/English/strings.po, plugin.video.putio/resources/language/Turkish/strings.po, plugin.video.putio/resources/lib/putio.py, plugin.video.putio/service.py
* Show 'watched' icon if the video is played before
* Show video duration next to its title
* Sort-by-name sorts files and folders together
* Use put.io/kodi endpoint
* Several bugfixes regarding video resume
=> [plugin.video.putio] 2.2.0

plugin.video.nba/addon.xml, plugin.video.nba/changelog.txt, plugin.video.nba/games.py
Quick release to fix a 404 bug on game 7 :(
=> [plugin.video.nba] 0.8.2

plugin.video.putio/README.md, plugin.video.putio/addon.xml, plugin.video.putio/changelog.txt, plugin.video.putio/resources/lib/putio.py
Update client to sync with Put.io servers
=> [plugin.video.putio] 2.2.1

plugin.video.myjamtv/addon.py, plugin.video.myjamtv/addon.xml, plugin.video.myjamtv/changelog.txt
=> [plugin.video.myjamtv] 1.1.0

plugin.video.disclose_tv/addon.xml, plugin.video.disclose_tv/changelog.txt, plugin.video.disclose_tv/resources/lib/scraper.py
Disclose_tv Addon for Kodi Update
0.1.8 (07.02.2016)
- fixed playback
Main changes done in:
addon.xml
scraper.py
changelog.txt
=> [plugin.video.disclose_tv] 0.1.8

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/live.py
Just a simple regex fix
Thanks a lot
=> [plugin.video.rtpplay] 2.5.6

plugin.audio.calmradio/addon.xml, plugin.audio.calmradio/api.py, plugin.audio.calmradio/changelog.txt, plugin.audio.calmradio/resources/language/English/strings.po
Hi guys,
An update to CalmRadio add-on, contains a fix which sets default bit rate to non registered users.
Thanks!
=> plugin.audio.calmradio - 0.2.3

plugin.audio.tunir/addon.xml, plugin.audio.tunir/api.py, plugin.audio.tunir/changelog.txt
Hi,
A small bug fix to USA radio stations list.
Thanks!
=> plugin.audio.tunir - v0.0.6

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/kika.py
Changed from lxml to Beautifulsoup
=> [plugin.video.mediathek] 0.7.3

plugin.onedrive/addon.py, plugin.onedrive/addon.xml, plugin.onedrive/changelog.txt
=> [plugin.onedrive] 1.1.10

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/dreisat.py, plugin.video.mediathek/mediathek/ndr.py
CHG: Repearing NDR und 3SAT
second try ...
=> [plugin.video.mediathek] 0.7.4

plugin.audio.calmradio/addon.xml, plugin.audio.calmradio/changelog.txt, plugin.audio.calmradio/user.py
verify flag added to requests.get method
=> plugin.audio.calmradio - v0.2.4

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/main.py, plugin.video.tyt/resources/lib/modules/type1.py
Fixed critical bug which stopped users from entering member area.
=> [plugin.video.tyt] 2.0.1

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/main.py, plugin.video.tyt/resources/lib/modules/type1.py
Fixed bug involving cookies.  Bug wasn't found in last commit because of existing cookie file.  Sorry for the recent pulls, found remaining bug on remote system.  This should be the last pull request for a long.
=> [plugin.video.tyt] 2.0.2

plugin.audio.soundcloud/README.md, plugin.audio.soundcloud/addon.xml, plugin.audio.soundcloud/changelog.txt, plugin.audio.soundcloud/resources/lib/content/items.py
=> [plugin.audio.soundcloud] 2.0.6

plugin.video.twitch/README.md, plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/Czech/strings.xml, plugin.video.twitch/resources/language/Danish/strings.xml, plugin.video.twitch/resources/language/Dutch/strings.xml, plugin.video.twitch/resources/language/English/strings.xml, plugin.video.twitch/resources/language/French/strings.xml, plugin.video.twitch/resources/language/German/strings.xml, plugin.video.twitch/resources/language/Norwegian/strings.xml, plugin.video.twitch/resources/language/Polish/strings.xml, plugin.video.twitch/resources/language/Spanish/strings.xml, plugin.video.twitch/resources/lib/converter.py, plugin.video.twitch/resources/lib/routes.py, plugin.video.twitch/resources/lib/twitch/api.py, plugin.video.twitch/resources/lib/twitch/constants.py, plugin.video.twitch/resources/lib/twitch/utils.py, plugin.video.twitch/resources/lib/utils.py, plugin.video.twitch/resources/settings.xml
=> [plugin.video.twitch] 1.4.3

plugin.video.rivedila7/addon.py, plugin.video.rivedila7/addon.xml, plugin.video.rivedila7/changelog.txt
=> [plugin.video.rivedila7] 0.0.7

plugin.video.snnow/addon.xml, plugin.video.snnow/changelog.txt, plugin.video.snnow/snnow.py
Fixes authentication and key error. Thanks to @portse and @mfallone.
=> [plugin.video.snnow] 1.0.6

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/helper.py
=> [plugin.video.svtplay] 4.0.32

plugin.audio.deejayIt.reloaded/.gitignore, plugin.audio.deejayIt.reloaded/addon.xml, plugin.audio.deejayIt.reloaded/changelog.txt, plugin.audio.deejayIt.reloaded/default.py, plugin.audio.deejayIt.reloaded/resources/lib/deejay_it_parser.py
Fixing issue #15, related to new season's shows.
=> [plugin.audio.deejayIt.reloaded] 1.6.1

plugin.video.spurs-tv/addon.py, plugin.video.spurs-tv/addon.xml, plugin.video.spurs-tv/changelog.txt
Fixes YouTube channel broken by the previous update 
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly …
=> [plugin.video.spurs-tv] 2.12.1

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/helper.py
=> [plugin.video.svtplay] 4.0.33

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/main.py, plugin.video.tyt/resources/language/English/strings.po, plugin.video.tyt/resources/lib/modules/type1.py, plugin.video.tyt/resources/settings.xml
Added member-tytlive.  Added members-special events.  Added auto-show changelog on version update.
=> [plugin.video.tyt] 2.0.4

plugin.video.popcorntv/addon.xml, plugin.video.popcorntv/changelog.txt, plugin.video.popcorntv/default.py, plugin.video.popcorntv/resources/lib/popcorntv.py
Updated page parsing because of upstream HTML changes.
=> [plugin.video.popcorntv] 1.0.13

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/readme.txt, plugin.video.wnbc/resources/lib/scraper.py
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- …
=> [plugin.video.wnbc] 3.0.7

plugin.video.twitch/README.md, plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/English/strings.po, plugin.video.twitch/resources/lib/routes.py, plugin.video.twitch/resources/lib/twitch/api.py, plugin.video.twitch/resources/lib/twitch/constants.py, plugin.video.twitch/resources/lib/twitch/utils.py
[plugin.video.twitch] 1.4.5
- Added compatibility for new Twitch encoder names.
=> [plugin.video.twitch] 1.4.5

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
Fix broken news listing due to site changes.
=> [plugin.video.svtplay] 4.0.34

plugin.video.bravo/README.txt, plugin.video.bravo/addon.xml, plugin.video.bravo/changelog.txt, plugin.video.bravo/resources/lib/scraper.py
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly monitor your python coding before submitting to repo.
- …
=> [plugin.video.bravo] 3.0.4

plugin.video.hallmark/README.txt, plugin.video.hallmark/addon.xml, plugin.video.hallmark/changelog.txt, plugin.video.hallmark/resources/lib/scraper.py
- [x ] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0
- …
=> [plugin.video.hallmark] 3.0.3

plugin.video.wabc/addon.xml, plugin.video.wabc/changelog.txt, plugin.video.wabc/readme.txt, plugin.video.wabc/resources/lib/scraper.py
- [ x] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0
- …
=> [plugin.video.wabc] 3.0.7

plugin.video.snagfilms/README.txt, plugin.video.snagfilms/addon.xml, plugin.video.snagfilms/changelog.txt, plugin.video.snagfilms/resources/lib/scraper.py
- [ x] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0
- …
=> [plugin.video.snagfilms] 3.0.3

plugin.video.roosterteeth/addon.py, plugin.video.roosterteeth/addon.xml, plugin.video.roosterteeth/changelog.txt, plugin.video.roosterteeth/resources/language/English/strings.po, plugin.video.roosterteeth/resources/lib/roosterteeth_const.py, plugin.video.roosterteeth/resources/lib/roosterteeth_list_episodes.py, plugin.video.roosterteeth/resources/lib/roosterteeth_main.py, plugin.video.roosterteeth/resources/lib/roosterteeth_play.py
v1.3.2 (2016-10-23):
small fix in debugging info
added recent video's for Achievement Hunter
added recent video's for Fun Haus
added recent video's for Screw Attack
added shows for Game Attack
added recent video's for Game Attack
added recent video's for The Know
added shows for Cow Chop
added recent video's for Cow Chop
added some debug info
=> [plugin.video.roosterteeth] 1.3.2

plugin.video.snnow/addon.xml, plugin.video.snnow/changelog.txt, plugin.video.snnow/default.py, plugin.video.snnow/sportsnet.py
Attempts reauthentication when stream retrieval fails and fixes sportsnet authentication.
=> [plugin.video.snnow] 1.0.7

plugin.video.fsgo/addon.xml, plugin.video.fsgo/changelog.txt, plugin.video.fsgo/default.py, plugin.video.fsgo/resources/lib/fsgo.py
So sorry for pushing another release so quickly, but there was a critical bug introduced in the previous version that caused the add-on to fail completely for some providers.
+ Critical bug fix: session wouldn't always refresh on time
- This add-on repository has automated code guideline check which could help you improve …
=> [plugin.video.fsgo] 1.1.2

plugin.video.nhklive/README.txt, plugin.video.nhklive/addon.xml, plugin.video.nhklive/changelog.txt, plugin.video.nhklive/resources/lib/scraper.py
- [x ] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0
- …
=> [plugin.video.nhklive] 3.0.6

plugin.video.nba/addon.xml, plugin.video.nba/changelog.txt, plugin.video.nba/common.py, plugin.video.nba/games.py, plugin.video.nba/utils.py, plugin.video.nba/videos.py
Changelog:
- General fixes for game playability
- Fixed highlights url that was no longer available from game menu
- Fixed away game feed in game menu
- Restore availability of 60fps
- Fixed videos not playing
- Fixed date parsing for videos, nba has two different formats
- Check if condensed game is available instead of showing it broken
=> [plugin.video.nba] 0.8.4

plugin.video.watchmojo/.gitignore, plugin.video.watchmojo/addon.xml, plugin.video.watchmojo/changelog.txt, plugin.video.watchmojo/resources/lib/main.py, plugin.video.watchmojo/resources/settings.xml
Fix video url scraper after site changed to html5 video
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuesly …
=> [plugin.video.watchmojo] 2.0.1

plugin.video.twit/addon.xml, plugin.video.twit/changelog.txt, plugin.video.twit/default.py
Fix for format changes in RSS feed.
- [x ] Each add-on submission should be a sinlge commit with using the following style: [plugin.video.foo] v1.0.0
- …
=> [plugin.video.twit] 2.1.6

plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/lib/gamekings_const.py, plugin.video.gamekings/resources/lib/gamekings_list.py, plugin.video.gamekings/resources/lib/gamekings_play.py
=> [plugin.video.gamekings] 1.2.4

plugin.audio.deejayIt.reloaded/addon.xml, plugin.audio.deejayIt.reloaded/changelog.txt, plugin.audio.deejayIt.reloaded/default.py
=> [plugin.audio.deejayIt.reloaded] 1.6.2

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py
=> [plugin.video.thinktv] 3.0.7

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
=> [plugin.video.svtplay] 4.0.35

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py
Update due to broken menu items …
=> [plugin.video.svtplay] 4.0.36

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_radio.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.2

plugin.video.fsgo/README.md, plugin.video.fsgo/addon.xml, plugin.video.fsgo/changelog.txt, plugin.video.fsgo/resources/lib/fsgo.py
=> [plugin.video.fsgo] 1.1.4

plugin.video.livestream/addon.xml, plugin.video.livestream/changelog.txt, plugin.video.livestream/main.py, plugin.video.livestream/resources/__init__.py, plugin.video.livestream/resources/globals.py, plugin.video.nbcsnliveextra/addon.xml, plugin.video.nbcsnliveextra/changelog.txt, plugin.video.nbcsnliveextra/nbcsn.py, plugin.video.nbcsnliveextra/resources/globals.py, plugin.video.nbcsnliveextra/resources/providers/adobe.py, plugin.video.nbcsnliveextra/resources/providers/comcast.py, plugin.video.nbcsnliveextra/resources/providers/frontier.py, plugin.video.nbcsnliveextra/resources/providers/playstation_vue.py, plugin.video.nbcsnliveextra/resources/providers/summit_broadband.py, plugin.video.nbcsnliveextra/resources/settings.xml
=> [plugin.video.nbcsnliveextra] 2016.10.21

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/FavoritesManager.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/svt.py
=> [plugin.video.svtplay] 4.0.37

plugin.video.snnow/addon.xml, plugin.video.snnow/changelog.txt, plugin.video.snnow/shawgo.py
Fix ShawGo authentication after provider form change.
=> [plugin.video.snnow] 1.0.8

plugin.video.tweakers/addon.xml, plugin.video.tweakers/changelog.txt, plugin.video.tweakers/resources/lib/tweakers_const.py, plugin.video.tweakers/resources/lib/tweakers_list.py, plugin.video.tweakers/resources/lib/tweakers_play.py, plugin.video.tweakers/resources/lib/tweakers_search.py
=> [plugin.video.tweakers] 1.1.7

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/FavoritesManager.py
Fix update causing issues on some platforms. …
=> [plugin.video.svtplay] 4.0.38

plugin.video.viaplay/README.md, plugin.video.viaplay/addon.xml, plugin.video.viaplay/changelog.txt, plugin.video.viaplay/default.py, plugin.video.viaplay/resources/language/English/strings.po, plugin.video.viaplay/resources/language/Swedish/strings.po, plugin.video.viaplay/resources/lib/vialib.py, plugin.video.viaplay/resources/settings.xml
+ Improve sports section
+ Fix broken playback for new content
+ Remove add-on debugging setting and automatically detect it instead
+ Code cleanup …
=> [plugin.video.viaplay] 1.0.6

plugin.onedrive/addon.py, plugin.onedrive/addon.xml, plugin.onedrive/changelog.txt, plugin.onedrive/resources/language/english/strings.po, plugin.onedrive/resources/settings.xml
- Blank settings text fixed.
- Subtitle loading issue fixed.
- Export process set to background.
Thanks!
=> [plugin.onedrive] 1.1.11

plugin.video.hgtv/README.txt, plugin.video.hgtv/addon.xml, plugin.video.hgtv/changelog.txt, plugin.video.hgtv/resources/lib/scraper.py
=> [plugin.video.hgtv] 3.0.7

plugin.video.diy/addon.xml, plugin.video.diy/changelog.txt, plugin.video.diy/readme.txt, plugin.video.diy/resources/lib/scraper.py
=> [plugin.video.diy] 3.0.5

plugin.video.rtlxl/addon.py, plugin.video.rtlxl/addon.xml, plugin.video.rtlxl/changelog.txt, plugin.video.rtlxl/resources/language/English/strings.xml, plugin.video.rtlxl/resources/lib/rtlxl.py, plugin.video.rtlxl/resources/settings.xml, plugin.video.rtlxl/rtlxltest.py
=> [plugin.video.rtlxl] 1.1.4

plugin.video.rtlxl/addon.py, plugin.video.rtlxl/addon.xml, plugin.video.rtlxl/changelog.txt
=> [plugin.video.rtlxl] 1.1.5

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/svt.py
Fixes broken category lisitng.
Hopefully last server side change before Christmas... …
=> [plugin.video.svtplay] 4.0.39

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/arte.py, plugin.video.mediathek/mediathek/zdf.py, plugin.video.mediathek/simplexbmc.py
Recover ARTE search and browse functionality
Minor code cleanup
=> [plugin.video.mediathek] 0.8.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
Updated image urls.
I am submitting as a co-author because @CaptainTK is away on holiday. …
=> [plugin.video.iplayerwww] 2.5.3

plugin.image.moebooru/addon.xml, plugin.image.moebooru/changelog.txt, plugin.image.moebooru/default.py
Updated Moebooru Imageboard plugin to work with the new Konachan API.
=> plugin.image.moebooru: Quickfix to adapt to konachan API changes

plugin.video.beergeeks/addon.xml, plugin.video.beergeeks/changelog.txt, plugin.video.beergeeks/main.py
Updates are as folllows
2016.7.13
- Fixed bug caused obsolete quality setting (no longer used)
2016.4.5
- Fixed bug
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard …
=> [plugin.video.beergeeks] 2016.7.13

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py
=> [plugin.video.thinktv] 3.0.8

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
**Update to the Infowars Kodi Addon**
**Version 2.0.3**
-Updated links (Spinalcracker)
**Main files changed:**
addon.xml (version number)
changelog.txt (updated links comment)
default.py (links updated) …
=> [plugin.video.infowars] 2.0.3

plugin.video.syfy/README.txt, plugin.video.syfy/addon.xml, plugin.video.syfy/changelog.txt, plugin.video.syfy/resources/lib/scraper.py
=> [plugin.video.syfy] 3.0.3

plugin.video.wabc/addon.xml, plugin.video.wabc/changelog.txt, plugin.video.wabc/readme.txt, plugin.video.wabc/resources/lib/scraper.py
=> [plugin.video.wabc] 3.0.8

plugin.video.espn_3/addon.py, plugin.video.espn_3/addon.xml, plugin.video.espn_3/changelog.txt, plugin.video.espn_3/resources/lib/adobe_activate_api.py, plugin.video.espn_3/resources/lib/appletv.py, plugin.video.espn_3/resources/lib/events.py, plugin.video.espn_3/resources/lib/globals.py, plugin.video.espn_3/resources/lib/legacy.py, plugin.video.espn_3/resources/lib/player_config.py, plugin.video.espn_3/resources/lib/util.py
Fixes for Adobe Authentication
Switch to requests library for better support with disabling SSL
=> [plugin.video.espn_3] 2.9.25

plugin.video.comingsoon.it/addon.xml
Quick fix for missing require in the addon.xml
it requires https://github.com/xbmc/repo-scripts/pull/346 to go in …
=> [plugin.video.comingsoon.it] 1.1.1

plugin.video.snnow/addon.xml, plugin.video.snnow/changelog.txt, plugin.video.snnow/cogeco.py
Fixes Cogeco authentication (URL changed)
=> [plugin.video.snnow] 1.0.9

plugin.video.metalvideo/addon.xml, plugin.video.metalvideo/changelog.txt, plugin.video.metalvideo/resources/language/English/strings.po, plugin.video.metalvideo/resources/lib/main.py, plugin.video.metalvideo/resources/lib/parsers.py
Changelog
- Fixed category parsing.
- Fixed the url's after site changed format.
- Renamed "Random videos" to "Party Mode".
=> [plugin.video.metalvideo] 2.0.2

plugin.video.rtpplay/README.md, plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/live.py
Fix a simple regex expression
Thanks
=> [plugin.video.rtpplay] 2.5.7

plugin.video.portico.tv/addon.xml
Mark Add-on as broken and no longer supported
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the …
=> [plugin.video.portico.tv] 1.0.4

plugin.video.cbc/addon.xml, plugin.video.cbc/resources/lib/scraper.py
=> [plugin.video.cbc] 3.0.3

plugin.video.sportube/addon.xml
=> [plugin.video.sportube] broken

plugin.video.4players/addon.py, plugin.video.4players/addon.xml, plugin.video.4players/changelog.txt
small fix for a bug that crashed the add-on after a return value of the API changed. Credits to @1337Boby who PR'ed the fix to Spheres repo
=> [plugin.video.4players] version 2.0.4

plugin.video.amaproracing/addon.xml, plugin.video.amaproracing/changelog.txt, plugin.video.amaproracing/main.py, plugin.video.amaproracing/motocross.py, plugin.video.amaproracing/supercross.py
2017.1.18
- Trimmed down content to focus on motocross & supercross for now
- Added Videos on Demand option in motocross which includes: Event highlights, Features, Full Motos, GoPro Footage and more
- Fixed bugs and general code clean up
- This add-on repository has automated code guideline check which could help you …
=> [plugin.video.amaproracing] 2017.1.18

plugin.video.snnow/addon.xml, plugin.video.snnow/changelog.txt, plugin.video.snnow/shawgo.py
=> [plugin.video.snnow] 1.0.10

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/live.py
Fix live channels. It's a single line - one new header is required.
=> [plugin.video.rtpplay] 2.5.8

plugin.video.blanketfort/addon.xml, plugin.video.blanketfort/changelog.txt, plugin.video.blanketfort/default.py
New video add-on for the web series Blanket Fort as well as other podcasts created by Blanket Fort Media.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You …
=> [plugin.video.blanketfort] v1.0.1

plugin.service.gto/README.md, plugin.service.gto/addon.xml, plugin.service.gto/changelog.txt, plugin.service.gto/default.py, plugin.service.gto/integration/Confluence/script-gto.xml, plugin.service.gto/integration/README.md, plugin.service.gto/resources/language/English/strings.po, plugin.service.gto/resources/language/German/strings.po, plugin.service.gto/resources/lib/rtv_de.py, plugin.service.gto/resources/lib/tvdigital_de.py, plugin.service.gto/resources/lib/tvspielfilm_de.py, plugin.service.gto/resources/settings.xml, plugin.service.gto/starter.py
Changelog:
2.0.8
- Cosmetics. Copy 'script-gto.xml' to Confluence folder to take effect.
See integration/README.md within the zip/addon folder
2.0.7
- handle exceptions while scraping with exception handler URLError instead of HTTPError.
2.0.6
- Scrape delay at startup removed. This is now handled dynamically.
2.0.5
- Scraper modifications
=> [plugin.service.gto] 2.0.8 Update

plugin.video.funimationnow/addon.xml
This plugin version has been marked as broken due to the old api being shut down and the new one incapable of performing the same tasks.
Please merge this PR to disable the broken plugin.
PR https://github.com/xbmc/repo-scripts/pull/369 has been created which is a replacement for this plugin and needs to be merged into the scripts repo to make available to all users as a replacement. 
Any previous users should use the official Kodi repo to install the new one which is marked as version 0.1.0.
Any additional links, Info, and or support can be found using this forum location.
http://forum.kodi.tv/showthread.php?tid=304479
Old API is no longer in service
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the …
=> [plugin.video.funimationnow] 0.0.4

plugin.video.guardian/addon.xml, plugin.video.guardian/changelog.txt, plugin.video.guardian/default.py, plugin.video.guardian/resources/lib/guardian.py
- Fixed videos in "documentaries" section.
- Fixed thumbnail handling.
- Added log messages.
- Minor changes. …
=> [plugin.video.guardian] 1.2.1

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
Version 2.0.4
- Updated links (Spinalcracker)
- Added Paul Joseph Watson section (Spinalcracker)
- Fixed random bugs with Krypton (Spinalcracker)
- [add-on …
=> [plugin.video.infowars] 2.0.4

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/arquivo.py, plugin.video.rtpplay/resources/favourites.py, plugin.video.rtpplay/resources/ondemand.py, plugin.video.rtpplay/resources/resolver.py, plugin.video.rtpplay/resources/settings.xml, plugin.video.rtpplay/resources/utilities.py
Fixes to on-demand
remove setview stuff
=> [plugin.video.rtpplay] 2.5.9

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/svt.py
Update broken program listing due to site change …
=> [plugin.video.svtplay] 4.0.41

plugin.video.snnow/addon.xml, plugin.video.snnow/changelog.txt, plugin.video.snnow/cogeco.py
Fix Cogeco provider authentication
=> [plugin.video.snnow] 1.0.11

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
Fixes broken search due to backend changes …
=> [plugin.video.svtplay] 4.0.42

plugin.video.nrwision/addon.py, plugin.video.nrwision/addon.xml, plugin.video.nrwision/changelog.txt
Bugfix: Videos didn't play under Krypton …
=> [plugin.video.nrwision] 1.4.0

plugin.video.myspass_de/addon.xml
Mark the add-on broken, as the website has changed and it doesn't work any longer.
=> [plugin.video.myspass_de] broken

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/language/English/strings.po, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py, plugin.video.iplayerwww/resources/settings.xml
=> [plugin.video.iplayerwww] 2.5.4

plugin.video.dmaxitalia/addon.xml
Mark the add-on broken, as the website has changed and it doesn't work any longer.
=> [plugin.video.dmaxitalia] broken

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/language/English/strings.po, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/settings.xml
=> [plugin.video.iplayerwww] 2.5.5

plugin.video.popcorntv/addon.xml, plugin.video.popcorntv/changelog.txt, plugin.video.popcorntv/default.py, plugin.video.popcorntv/resources/lib/popcorntv.py
- Updated page parsing because of upstream HTML changes.
- Added logging. …
=> [plugin.video.popcorntv] 1.0.14

plugin.audio.qobuz/addon.xml, plugin.audio.qobuz/changelog.txt, plugin.audio.qobuz/resources/lib/qobuz/player.py
=> [plugin.audio.qobuz] v1.2.2

plugin.video.bravo/README.txt, plugin.video.bravo/addon.xml, plugin.video.bravo/changelog.txt, plugin.video.bravo/resources/lib/scraper.py
=> [plugin.video.bravo] 3.0.5

plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/changelog.txt, plugin.video.foodnetwork/readme.txt, plugin.video.foodnetwork/resources/lib/scraper.py
=> [plugin.video.foodnetwork] 3.0.4

plugin.video.abcfamily/addon.xml, plugin.video.abcfamily/changelog.txt, plugin.video.abcfamily/readme.txt, plugin.video.abcfamily/resources/lib/scraper.py
=> [plugin.video.abcfamily] 3.0.4

plugin.video.metalvideo/addon.xml, plugin.video.metalvideo/changelog.txt, plugin.video.metalvideo/resources/lib/main.py, plugin.video.metalvideo/resources/lib/parsers.py
Fix addon after site reverted back to old url structure
=> [plugin.video.metalvideo] 2.0.3

plugin.video.wral/addon.xml, plugin.video.wral/changelog.txt, plugin.video.wral/readme.txt, plugin.video.wral/resources/language/English/strings.po, plugin.video.wral/resources/lib/scraper.py
=> [plugin.video.wral] 3.0.5

plugin.video.currenttime.tv/addon.py, plugin.video.currenttime.tv/addon.xml, plugin.video.currenttime.tv/changelog.txt
=> [plugin.video.currenttime.tv] 1.0.4

plugin.video.watchmojo/addon.xml, plugin.video.watchmojo/changelog.txt, plugin.video.watchmojo/resources/language/English/strings.po, plugin.video.watchmojo/resources/lib/main.py, plugin.video.watchmojo/resources/lib/parsers.py
=> [plugin.video.watchmojo] 2.1.0

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/live.py, plugin.video.rtpplay/resources/resolver.py
=> [plugin.video.rtpplay] 2.6.0

plugin.video.mtv_de/addon.xml, plugin.video.mtv_de/default.py
=> [plugin.video.mtv_de] 3.3.11

plugin.video.nick_de/addon.xml, plugin.video.nick_de/default.py, plugin.video.nick_de/resources/settings.xml
=> [plugin.video.nick_de] 1.1.6

plugin.video.bravo/README.txt, plugin.video.bravo/addon.xml, plugin.video.bravo/changelog.txt, plugin.video.bravo/resources/lib/scraper.py
=> [plugin.video.bravo] 3.0.6

plugin.video.syfy/README.txt, plugin.video.syfy/addon.xml, plugin.video.syfy/changelog.txt
bumped t1mlib version for fix for Kodi 17 Android request timeouts
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
=> [plugin.video.syfy] 3.0.4

plugin.video.mediacorp/README.txt, plugin.video.mediacorp/addon.xml, plugin.video.mediacorp/changelog.txt
bump t1mlib version to fix request timeouts in Kodi 17.0 android …
=> [plugin.video.mediacorp] 3.0.3

plugin.video.fsgo/addon.xml
=> [plugin.video.fsgo] - deprecated

plugin.video.snagfilms/README.txt, plugin.video.snagfilms/addon.xml, plugin.video.snagfilms/changelog.txt, plugin.video.snagfilms/resources/language/English/strings.po, plugin.video.snagfilms/resources/lib/scraper.py
=> [plugin.video.snagfilms] 3.0.4

plugin.audio.rco/addon.xml
Please merge only when/if https://github.com/xbmc/repo-plugins/pull/967 is adjusted.
=> [plugin.audio.rco] broken

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/language/Polish/strings.po, plugin.video.youtube/resources/lib/kodion/simple_requests/api.py, plugin.video.youtube/resources/lib/youtube/helper/subtitles.py, plugin.video.youtube/resources/lib/youtube/helper/utils.py, plugin.video.youtube/resources/lib/youtube/helper/video_info.py
Updated Youtube plugin from 5.3.8 to 5.3.10
=> [plugin.video.youtube] 5.3.10

plugin.video.zdf_de_2016/README.md, plugin.video.zdf_de_2016/addon.xml, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/api/StreamInfoResource.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/player/PlayVideo.py
New version with feature-requests and bug-fixes.
1.0.3 (2017-02-19)
- provide sub-titles for video, if available on zdf.de (see https://github.com/generia/plugin.video.zdf_de_2016/issues/3)
- Gotham support, lowered xbmc.python version to '2.14.0' (see https://github.com/generia/plugin.video.zdf_de_2016/issues/4)
- This …
=> [plugin.video.zdf_de_2016] 1.0.3

plugin.video.metalvideo/addon.xml, plugin.video.metalvideo/changelog.txt, plugin.video.metalvideo/resources/lib/main.py
=> [plugin.video.metalvideo] 2.0.4

plugin.video.nhlgcl/addon.xml, plugin.video.nhlgcl/changelog.txt, plugin.video.nhlgcl/resources/lib/globals.py
- Patched bug released in previous version that affected Kodi 16.x users …
=> [plugin.video.nhlgcl] 2017.2.24

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt, plugin.video.ign_com/default.py
2.3.1
- Adjusted video detection to new page structure
- Code clean up …
=> [plugin.video.ign_com] 2.3.1

plugin.video.fatstone/addon.xml, plugin.video.fatstone/changelog.txt, plugin.video.fatstone/default.py
Updated stream url of live-video
=> [plugin.video.fatstone] 1.0.2

plugin.video.uzg/addon.xml, plugin.video.uzg/changelog.txt, plugin.video.uzg/resources/lib/uzg.py
=> [plugin.video.uzg] v1.3.1

plugin.video.pcloud-video-streaming/addon.py, plugin.video.pcloud-video-streaming/addon.xml, plugin.video.pcloud-video-streaming/changelog.txt, plugin.video.pcloud-video-streaming/resources/language/English/strings.xml, plugin.video.pcloud-video-streaming/resources/language/Italian/strings.xml, plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
Solves issue reported at http://forum.kodi.tv/showthread.php?tid=239955&pid=2536802#pid2536802
=> [plugin.video.pcloud-video-streaming] 1.2.5

plugin.video.nhklive/README.txt, plugin.video.nhklive/addon.xml, plugin.video.nhklive/changelog.txt, plugin.video.nhklive/resources/lib/scraper.py
=> [plugin.video.nhklive] 3.0.7

plugin.video.roosterteeth/addon.xml, plugin.video.roosterteeth/changelog.txt, plugin.video.roosterteeth/resources/language/English/strings.po, plugin.video.roosterteeth/resources/lib/roosterteeth_const.py
v1.3.3 (2017-03-03):
fixed some typos
fixed url in addon.xml as per request
=> [plugin.video.roosterteeth] 1.3.3

plugin.video.nederland24/addon.xml, plugin.video.nederland24/changelog.txt, plugin.video.nederland24/nederland24.py, plugin.video.nederland24/resources/settings.xml
fixes breakage due to site change …
=> [plugin.video.nederland24] 4.5.3

plugin.video.botchamania/addon.xml, plugin.video.botchamania/changelog.txt, plugin.video.botchamania/resources/lib/botchamania_const.py
=> [plugin.video.botchamania] 1.1.5

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/default.py, plugin.video.orftvthek/resources/language/English/strings.po, plugin.video.orftvthek/resources/language/German/strings.po, plugin.video.orftvthek/resources/lib/Settings.py, plugin.video.orftvthek/resources/lib/base.py, plugin.video.orftvthek/resources/lib/htmlscraper.py, plugin.video.orftvthek/resources/lib/serviceapi.py
Fixed Livestream Issue by passing UA …
=> [plugin.video.orftvthek] 0.7.2

plugin.video.cnet.podcasts/addon.xml, plugin.video.cnet.podcasts/changelog.txt, plugin.video.cnet.podcasts/resources/language/English/strings.po
v1.1.3 (2017-03-03)
using po-files
fixed url in addon.xml as per request
=> [plugin.video.cnet.podcasts] 1.1.3

plugin.video.dumpert/addon.xml, plugin.video.dumpert/changelog.txt, plugin.video.dumpert/resources/lib/dumpert_const.py
=> [plugin.video.dumpert] 1.1.3

plugin.video.snagfilms/README.txt, plugin.video.snagfilms/addon.xml, plugin.video.snagfilms/changelog.txt, plugin.video.snagfilms/resources/lib/scraper.py, plugin.video.snagfilms/resources/settings.xml
=> [plugin.video.snagfilms] 3.0.5

plugin.video.deredactie/LICENSE.txt, plugin.video.deredactie/README.md, plugin.video.deredactie/addon.xml, plugin.video.deredactie/changelog.txt, plugin.video.deredactie/deredactie.py
- Disabled SSL to avoid certificate-related issues with some versions of Kodi
=> [plugin.video.deredactie] 0.6.0

plugin.video.charge/addon.xml
=> [plugin.video.charge] 3.0.2

plugin.video.cbcnews/addon.xml
=> [plugin.video.cbcnews] 3.0.2

plugin.video.deredactie/addon.xml, plugin.video.deredactie/changelog.txt
- Updated xbmc.python dependency to match Gotham
=> [plugin.video.deredactie] 0.6.1

plugin.video.tbdtv/addon.xml
=> [plugin.video.tbdtv] 3.0.2

plugin.audio.rainymood.com/addon.xml
=> [plugin.audio.rainymood.com] 1.2.0

plugin.video.latelelibre_fr/.gitignore, plugin.video.latelelibre_fr/addon.xml, plugin.video.latelelibre_fr/changelog.txt, plugin.video.latelelibre_fr/default.py, plugin.video.latelelibre_fr/resources/language/English/strings.xml, plugin.video.latelelibre_fr/resources/language/French/strings.xml, plugin.video.latelelibre_fr/resources/language/German/strings.xml, plugin.video.latelelibre_fr/resources/language/Spanish/strings.xml, plugin.video.latelelibre_fr/resources/lib/ltl_api.py, plugin.video.latelelibre_fr/resources/lib/lutil.py, plugin.video.latelelibre_fr/resources/lib/plugin.py, plugin.video.latelelibre_fr/resources/settings.xml, plugin.video.latelelibre_fr/resources/tests/test_api.py
Hi, this is an update on the Gotham branch for the plugin.video.latelelibre_fr
Changelog: v1.0.2 (2017.03.07)
- Sanitize thumbnail URLs (credits: andersonvom).
- Fix playable video URL pattern (credits: andersonvom).
- Undesired whitespace code cleaning (credits: andersonvom).
- Updated test case code (credits: andersonvom).
- Added support for preferred video quality option from add-on settings menu.
- Updated logging system.
- Improved video patterns.
- Improved special character translations from description fields.
- Code refactored.
Thanks a lot in advance and best regards,
jamontes.
- [ X] I have read the …
=> [plugin.video.latelelibre_fr] 1.0.2

plugin.video.mlslive/addon.xml, plugin.video.mlslive/changelog.txt, plugin.video.mlslive/default.py, plugin.video.mlslive/mlslive.py, plugin.video.mlslive/resources/language/English/strings.xml, plugin.video.mlslive/test.py
Updates for the 2017 season and the switch to MLBAM (from Neulion)
Hi,
I'm very sorry for the massive commit and PR. They changed their whole system away from Neulion to MLB Advanced Media so this is basically a brand new plugin with the old album art.
Anyway, thanks in advance.
=> [plugin.video.mlslive] 1.17.0

plugin.video.hallmark/README.txt, plugin.video.hallmark/addon.xml, plugin.video.hallmark/changelog.txt, plugin.video.hallmark/resources/lib/scraper.py
=> [plugin.video.hallmark] 3.0.4

plugin.video.wabc/addon.xml, plugin.video.wabc/changelog.txt, plugin.video.wabc/readme.txt, plugin.video.wabc/resources/lib/scraper.py
=> [plugin.video.wabc] 3.0.10

plugin.video.awntv/addon.xml
Broken. Site no longer exists.
=> [plugin.video.awntv] 2.0.1

plugin.video.engineeringtv/addon.xml
=> [plugin.video.engineeringtv] 2.0.2

plugin.video.watchmojo/addon.xml, plugin.video.watchmojo/changelog.txt, plugin.video.watchmojo/resources/lib/main.py, plugin.video.watchmojo/resources/lib/parsers.py
Fix add-on after more site changes
=> [plugin.video.watchmojo] 2.1.1

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/svt.py
=> [plugin.video.svtplay] 4.0.43

plugin.video.mlslive/addon.xml, plugin.video.mlslive/changelog.txt, plugin.video.mlslive/default.py, plugin.video.mlslive/mlslive.py, plugin.video.mlslive/resources/language/English/strings.xml, plugin.video.mlslive/resources/settings.xml, plugin.video.mlslive/test.py
- Fix authorization issues
- Add graphics, better game details, and favorite team
- Condensed matches
=> [plugin.video.mlslive] 1.17.1

plugin.video.fernsehkritik/addon.xml, plugin.video.fernsehkritik/changelog.txt
=> [plugin.video.fernsehkritik] 1.0.2

plugin.video.dr.dk.bonanza/addon.py, plugin.video.dr.dk.bonanza/addon.xml, plugin.video.dr.dk.bonanza/changelog.txt
Updated addon due to website changes.
=> [plugin.video.dr.dk.bonanza] 3.1.0

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/readme.txt, plugin.video.wnbc/resources/lib/scraper.py
=> [plugin.video.wnbc] 3.0.9

plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/lib/gamekings_const.py
v1.2.6 (2017-03-12)
- added twitch as a dependency
=> [plugin.video.gamekings] 1.2.6

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/svt.py
Fixes broken playback of clips …
=> [plugin.video.svtplay] 4.0.44

plugin.video.videomediaset/addon.xml, plugin.video.videomediaset/changelog.txt, plugin.video.videomediaset/resources/lib/mediaset.py
v1.2.1:
fix after website changes
=> [plugin.video.videomediaset] 1.2.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py, plugin.video.iplayerwww/resources/settings.xml
=> [plugin.video.iplayerwww] 2.5.7

plugin.video.nederland24/addon.xml, plugin.video.nederland24/changelog.txt, plugin.video.nederland24/nederland24.py
fix channels affected by another site change …
=> [plugin.video.nederland24] 4.5.6

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py, plugin.video.iplayerwww/resources/settings.xml
=> [plugin.video.iplayerwww] 3.0.1

plugin.video.wral/addon.xml, plugin.video.wral/changelog.txt, plugin.video.wral/readme.txt, plugin.video.wral/resources/lib/scraper.py
=> [plugin.video.wral] 3.0.6

plugin.video.sgtv/README.md, plugin.video.sgtv/addon.xml, plugin.video.sgtv/default.py
Plugin update
Fix compatibility for Kodi running on Android due to python incompatibility
=> [plugin.video.sgtv] v1.8.1

plugin.video.mlslive/addon.xml, plugin.video.mlslive/changelog.txt, plugin.video.mlslive/default.py, plugin.video.mlslive/mlslive.py, plugin.video.mlslive/resources/language/English/strings.xml, plugin.video.mlslive/resources/settings.xml, plugin.video.mlslive/test.py
- Fix international game issues
- Format test stream output for ffmpeg
- Show login progress with DialogProgress
- Only login when auth token is not present, or becomes invalid
- Enable logout from settings
- Use proper XBMC logging
- Improved error handling (and logging)
=> [plugin.video.mlslive] 1.17.2

plugin.video.eso/.gitignore, plugin.video.eso/addon.xml, plugin.video.eso/changelog.txt, plugin.video.eso/default.py, plugin.video.eso/lutil.py
Hi,
This is a new update for plugin.video.eso over Gotham branch.
Changelog: 1.0.7 (2017.03.13)
- Fixed thumbnail images.
- Updated logging system.
- Code refactored and cleaned.
jamontes.
=> [plugin.video.eso] 1.0.7

plugin.video.filmsforaction/.gitignore, plugin.video.filmsforaction/addon.xml, plugin.video.filmsforaction/changelog.txt, plugin.video.filmsforaction/default.py, plugin.video.filmsforaction/resources/lib/ffa_api.py, plugin.video.filmsforaction/resources/lib/lutil.py, plugin.video.filmsforaction/resources/lib/plugin.py, plugin.video.filmsforaction/resources/tests/test_api.py
Hi,
This is a new update for plugin.video.filmsforaction over Gotham branch.
Changelog: 1.0.8 (2017.03.13)
- Fixed video scraper due to Dailymotion website changes.
- Fixed category menus due to website changes.
- Fixed search option due to website changes.
- Fixed Next/Previous Page entries due to website changes.
- Improved Vimeo scraper to support non standard video resolutions.
- Updated logging system.
- Updated lutils library to latest version.
- Updated category test case.
- Improved video patterns.
- Code refactored and cleaned.
jamontes.
=> [plugin.video.filmsforaction] 1.0.8

plugin.video.tv3play.dk/addon.py, plugin.video.tv3play.dk/addon.xml, plugin.video.tv3play.dk/changelog.txt
=> [plugin.video.tv3play.dk] 3.1.0

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
Fixes broken playback of news items. …
=> [plugin.video.svtplay] 4.0.45

plugin.video.metv/README.txt, plugin.video.metv/addon.xml, plugin.video.metv/changelog.txt, plugin.video.metv/lib/scraper.py
=> [plugin.video.metv] 3.0.4

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
=> [plugin.video.svtplay] 4.0.46

plugin.video.tmos/addon.py, plugin.video.tmos/addon.xml, plugin.video.tmos/changelog.txt
https://github.com/xbmc/repo-plugins/issues/1081
=> [plugin.video.tmos] 1.0.6

plugin.video.disclose_tv/addon.xml, plugin.video.disclose_tv/changelog.txt, plugin.video.disclose_tv/resources/lib/scraper.py
- Fixed playback by manually setting HDR in scraper.py
- Updated changelog and XML
=> [plugin.video.disclose_tv] 0.1.9

plugin.video.nbcsnliveextra/addon.xml, plugin.video.nbcsnliveextra/changelog.txt, plugin.video.nbcsnliveextra/resources/globals.py, plugin.video.nbcsnliveextra/resources/language/English/strings.xml, plugin.video.nbcsnliveextra/resources/settings.xml
- Added Sportsnet New York to filter list
- Moved label ids to correct range …
=> [plugin.video.nbcsnliveextra] 2017.4.4

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/arte.py, plugin.video.mediathek/mediathek/orf.py, plugin.video.mediathek/simplexbmc.py
Small bugfixes
reimplement orf
=> [plugin.video.mediathek] 0.8.2

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt, plugin.video.ign_com/default.py
IGN.com Update
2.3.2 // 2017-04-06
- Adjusted video detection to new page structure
- Added detection for new different video implementation
=> [plugin.video.ign_com] 2.3.2

plugin.video.playonbrowser/addon.xml, plugin.video.playonbrowser/default.py
=> [plugin.video.playonbrowser] 1.0.21

plugin.video.tviplayer/addon.xml, plugin.video.tviplayer/changelog.txt, plugin.video.tviplayer/resources/ondemand.py, plugin.video.tviplayer/resources/settings.xml, plugin.video.tviplayer/resources/webutils.py
=> [plugin.video.tviplayer] v0.2.1

plugin.video.abcfamily/addon.xml, plugin.video.abcfamily/changelog.txt, plugin.video.abcfamily/readme.txt, plugin.video.abcfamily/resources/lib/scraper.py
=> [plugin.video.abcfamily] 3.0.5

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/svt.py
=> [plugin.video.svtplay] 4.0.47

plugin.video.worldstarhiphop/addon.xml, plugin.video.worldstarhiphop/changelog.txt, plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_const.py, plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_play.py
v1.0.9 (2017-04-08):
- adjusted video detection to website changes
=> [plugin.video.worldstarhiphop] 1.0.9

plugin.video.reddit_viewer/README.md, plugin.video.reddit_viewer/addon.xml, plugin.video.reddit_viewer/changelog.txt, plugin.video.reddit_viewer/default.py, plugin.video.reddit_viewer/resources/language/English/strings.po, plugin.video.reddit_viewer/resources/lib/CommonFunctions.py, plugin.video.reddit_viewer/resources/lib/YoutubeDLWrapper.py, plugin.video.reddit_viewer/resources/lib/actions.py, plugin.video.reddit_viewer/resources/lib/autoplay.py, plugin.video.reddit_viewer/resources/lib/domains.py, plugin.video.reddit_viewer/resources/lib/guis.py, plugin.video.reddit_viewer/resources/lib/main_listing.py, plugin.video.reddit_viewer/resources/lib/reddit.py, plugin.video.reddit_viewer/resources/lib/slideshow.py, plugin.video.reddit_viewer/resources/lib/utils.py, plugin.video.reddit_viewer/resources/settings.xml
=> [plugin.video.reddit_viewer] 3.3.8

plugin.video.revision3/addon.xml
Well, it looks this one hasn't last for long. Probably a farewell to revision3.
=> [plugin.video.revision3] broken

plugin.video.videomediaset/addon.xml, plugin.video.videomediaset/changelog.txt, plugin.video.videomediaset/default.py, plugin.video.videomediaset/resources/lib/mediaset.py
=> [plugin.video.videomediaset] 1.2.2

plugin.video.rocketbeans/addon.xml, plugin.video.rocketbeans/resources/lib/guide.py, plugin.video.rocketbeans/resources/lib/plugin.py, plugin.video.rocketbeans/resources/lib/youtube.py
Well, I've overlooked something pretty essential here...
Would be cool to get it merged soon …
=> [plugin.video.rocketbeans] 1.0.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.8

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.2

plugin.service.gto/addon.xml, plugin.service.gto/default.py, plugin.service.gto/resources/lib/klack_de.py, plugin.service.gto/resources/lib/rtv_de.py, plugin.service.gto/resources/lib/tvdigital_de.py, plugin.service.gto/resources/lib/tvspielfilm_de.py, plugin.service.gto/resources/settings.xml
=> [plugin.service.gto] v2.0.9

plugin.video.mlbbasesloaded/README.md, plugin.video.mlbbasesloaded/addon.xml, plugin.video.mlbbasesloaded/mlbtv_session.py, plugin.video.mlbbasesloaded/mlbtv_stream_api.py
* Critical bug fix: the plugin would fail when a blacked out game was selected, resulting in the plugin not switching between games. …
=> [plugin.video.mlbbasesloaded] 0.3.0

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/language/English/strings.po, plugin.video.thinktv/resources/lib/scraper.py
=> [plugin.video.thinktv] 3.0.9

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.9

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.3

plugin.video.zattoobox/addon.xml, plugin.video.zattoobox/changelog.txt, plugin.video.zattoobox/resources/lib/core/zapisession.py
This update does fix a broken streaming URL.
--- …
=> [plugin.video.zattoobox] 1.0.1

plugin.program.remote.control.browser/addon.xml, plugin.program.remote.control.browser/browse.py, plugin.program.remote.control.browser/changelog.txt, plugin.program.remote.control.browser/plugin.py, plugin.program.remote.control.browser/resources/data/dependencies.xml, plugin.program.remote.control.browser/resources/data/lircd/browser.lirc, plugin.program.remote.control.browser/resources/language/resource.language.de_de/strings.po, plugin.program.remote.control.browser/resources/language/resource.language.en_gb/strings.po, plugin.program.remote.control.browser/resources/language/resource.language.en_us/strings.po, plugin.program.remote.control.browser/resources/language/resource.language.pt_br/strings.po, plugin.program.remote.control.browser/resources/settings.xml, plugin.program.remote.control.browser/retrieve.py, plugin.program.remote.control.browser/service.py
This add-on makes it easy to browse websites using a remote control instead of a mouse and keyboard. This upgrade from v1.0.5 includes better support for low-powered/tiny/fanless hosts.
=> [plugin.program.remote.control.browser] 1.2.0

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_common.py
=> [plugin.video.iplayerwww] 3.0.4

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py
=> [plugin.video.iplayerwww] 2.5.10

plugin.video.myvevo/README.txt, plugin.video.myvevo/addon.xml, plugin.video.myvevo/changelog.txt, plugin.video.myvevo/resources/language/English/strings.po, plugin.video.myvevo/resources/lib/scraper.py
=> [plugin.video.myvevo] 3.0.6

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_radio.py
=> [plugin.video.iplayerwww] 2.5.11

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.12

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_radio.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.5

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/language/English/strings.po, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py, plugin.video.iplayerwww/resources/settings.xml
=> [plugin.video.iplayerwww] 2.5.13

plugin.video.liveleak/addon.xml, plugin.video.liveleak/changelog.txt, plugin.video.liveleak/default.py
This is a plugin update:
- Add "view" mode for calling from another plugin
- Update version number more inline w/ Semantic Versioning
=> [plugin.video.liveleak] 1.0.1

plugin.video.filmstarts/addon.xml, plugin.video.filmstarts/changelog.txt, plugin.video.filmstarts/default.py
Bugfix
- X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0 …
=> [plugin.video.filmstarts] 0.6.8

plugin.video.tele5_de/addon.xml, plugin.video.tele5_de/changelog.txt, plugin.video.tele5_de/default.py
=> [plugin.video.tele5_de] 1.1.11

plugin.video.aod/addon.xml, plugin.video.aod/changelog.txt, plugin.video.aod/default.py, plugin.video.aod/resources/language/English/strings.po, plugin.video.aod/resources/language/German/strings.po, plugin.video.aod/resources/settings.xml
=> [plugin.video.aod] 0.6.0

plugin.video.pbskids/README.txt, plugin.video.pbskids/addon.xml, plugin.video.pbskids/changelog.txt, plugin.video.pbskids/resources/lib/scraper.py
=> [plugin.video.pbskids] 3.0.3

plugin.video.vrt.nu/addon.xml
=> [plugin.video.vrt.nu] 0.0.2

plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/lib/gamekings_const.py, plugin.video.gamekings/resources/lib/gamekings_list.py, plugin.video.gamekings/resources/lib/gamekings_main.py, plugin.video.gamekings/resources/lib/gamekings_play.py
v1.2.8 (2017-05-07)
- small improvements to scraping of the video-id in all categories
- fix for gamekings extra video's
=> [plugin.video.gamekings] 1.2.8

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/arte.py
=> [plugin.video.mediathek] 0.8.3

plugin.video.noco/.hg_archival.txt, plugin.video.noco/addon.py, plugin.video.noco/addon.xml, plugin.video.noco/resources/language/English/strings.xml, plugin.video.noco/resources/language/French/strings.xml
Pulling on behalf of Julien Gormotte (gormux)
#1191
Added support for playlists / queuing, thanks to pcjco
This is probably the last update if nothing breaks the plugin in a future release, as it works correctly and has apparently all the features people want (as I only received this contribution in the last... 2 years iirc, no plugin-related bugs or feature requests), so as I'm not used to git (and had difficulties contributing to ansible recently), I did not take the time to use a PR for this update.
=> [plugin.video.noco] 1.0.12

plugin.onedrive/README.md, plugin.onedrive/addon.py, plugin.onedrive/addon.xml, plugin.onedrive/changelog.txt, plugin.onedrive/resources/language/english/strings.po, plugin.onedrive/resources/lib/api/OneDriveHTTPRequestHandler.py, plugin.onedrive/resources/lib/api/onedrive.py, plugin.onedrive/resources/settings.xml, plugin.onedrive/service.py
v1.2.0 released:
Download subtitle fixed
Now supporting business accounts
xbmcvfs is used for disk operations
Previous PR issues fixed.
=> [plugin.onedrive] 1.2.0

plugin.video.noco/addon.py, plugin.video.noco/addon.xml, plugin.video.noco/changelog.txt, plugin.video.noco/resources/language/English/strings.xml, plugin.video.noco/resources/language/French/strings.xml, plugin.video.noco/resources/lib/api.py, plugin.video.noco/resources/settings.xml
- Fix the need to enter a username and password for guest mode
- Allow to set the User Rating (1-5 star) for a video from item contextual menu
- Setting to block play for not advised content (CSA rating)
- write CSA rating string into MPAA info
- Sets the plugin content to videos when applicable to better show info in skins
=> [plugin.video.noco] v1.0.14

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.14

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.6

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py, plugin.video.iplayerwww/resources/settings.xml
=> [plugin.video.iplayerwww] 3.0.7

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.15

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/main.py
=> [plugin.video.tyt] 2.1.1

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/arte.py
ARTE changed their link to retrieve JSON again ...
=> [plugin.video.mediathek] 0.8.4

plugin.video.nbcsnliveextra/addon.xml, plugin.video.nbcsnliveextra/changelog.txt, plugin.video.nbcsnliveextra/nbcsn.py, plugin.video.nbcsnliveextra/resources/globals.py, plugin.video.nbcsnliveextra/resources/language/English/strings.xml, plugin.video.nbcsnliveextra/resources/settings.xml
- Golf Channel requires subscription
- Added Sportsnet New York to filter list
- Moved label ids to correct range …
=> [plugin.video.nbcsnliveextra] 2017.5.24

plugin.video.rt/README.txt, plugin.video.rt/addon.xml, plugin.video.rt/changelog.txt, plugin.video.rt/default.py
=> [plugin.video.rt] 2.0.2

plugin.onedrive/README.md, plugin.onedrive/addon.py, plugin.onedrive/addon.xml, plugin.onedrive/changelog.txt, plugin.onedrive/resources/language/english/strings.po, plugin.onedrive/resources/lib/api/account.py, plugin.onedrive/resources/lib/api/download.py, plugin.onedrive/resources/lib/api/html.py, plugin.onedrive/resources/lib/api/onedrive.py, plugin.onedrive/resources/lib/api/source.py, plugin.onedrive/resources/settings.xml, plugin.onedrive/service.py
v1.3.0
- Use OneDrive as a source
- Subtitle fix
=> [plugin.onedrive] 1.3.0

plugin.video.hallmark/README.txt, plugin.video.hallmark/addon.xml, plugin.video.hallmark/changelog.txt, plugin.video.hallmark/resources/lib/scraper.py
=> [plugin.video.hallmark] 3.0.5

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.8

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.16

plugin.video.foodnetwork.canada/README.txt, plugin.video.foodnetwork.canada/addon.xml, plugin.video.foodnetwork.canada/changelog.txt, plugin.video.foodnetwork.canada/resources/lib/scraper.py
=> [plugin.video.foodnetwork.canada] 3.0.3

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/helper.py
Enhance compability with Kodi v<17 …
=> [plugin.video.svtplay] 4.0.49

plugin.video.diy/addon.xml, plugin.video.diy/changelog.txt, plugin.video.diy/readme.txt, plugin.video.diy/resources/lib/scraper.py
=> [plugin.video.diy] 3.0.6

plugin.video.hgtv/README.txt, plugin.video.hgtv/addon.xml, plugin.video.hgtv/changelog.txt, plugin.video.hgtv/resources/lib/scraper.py
=> [plugin.video.hgtv] 3.0.8

plugin.video.psvue/addon.xml, plugin.video.psvue/resources/language/resource.language.en_gb/strings.po, plugin.video.psvue/resources/lib/globals.py
- Fix for special characters in username and password
- Improved error notification descriptions …
=> [plugin.video.psvue] 2017.6.1

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
Fix broken category lisitng due to backend change …
=> [plugin.video.svtplay] 4.0.50

plugin.video.noco/addon.py, plugin.video.noco/addon.xml, plugin.video.noco/changelog.txt, plugin.video.noco/resources/language/English/strings.xml, plugin.video.noco/resources/language/French/strings.xml, plugin.video.noco/resources/lib/api.py, plugin.video.noco/resources/settings.xml
- Fix "Noco favorite shows" issues (cannot add favorite)
- Speed enhancement by using cache for most pages (can be parametrized or disabled in settings)
- Add a clear cache button in settings  
- Add info text for shows and partners when available
- Add "Settings" item in root menu
- New videos since user last visit have a [N] tag in the "Last videos" directory (can be disabled in settings)
=> [plugin.video.noco] 1.0.15

plugin.video.zdf_de_2016/README.md, plugin.video.zdf_de_2016/addon.xml, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/web/Resource.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/NavigationResource.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Regex.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/RubricResource.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Teaser.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/RubricPage.py, plugin.video.zdf_de_2016/resources/language/English/strings.po, plugin.video.zdf_de_2016/resources/language/German/strings.po
New version after ZDF website update
1.0.4 (2017-06-03)
- inform about redirects to external sites (see https://github.com/generia/plugin.video.zdf_de_2016/issues/5)
- fixes for minor labeling issues after updates on zdf.de  …
=> [plugin.video.zdf_de_2016] 1.0.4

plugin.video.plutotv/addon.xml, plugin.video.plutotv/default.py
=> [plugin.video.plutotv] 1.0.2

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.17

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.9

plugin.video.plutotv/addon.xml, plugin.video.plutotv/default.py
Minor fix and tweak, hopefully should be my final version. …
=> [plugin.video.plutotv] 1.0.3

plugin.audio.radio_de/addon.xml, plugin.audio.radio_de/changelog.txt, plugin.audio.radio_de/resources/lib/api.py
fixed playback of some stations
=> [plugin.audio.radio_de] 2.3.2

plugin.video.psvue/addon.xml, plugin.video.psvue/main.py, plugin.video.psvue/resources/language/resource.language.en_gb/strings.po, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py, plugin.video.psvue/resources/settings.xml
- Fixed streams not launching
- Code Clean Up …
=> [plugin.video.psvue] 2017.6.7

plugin.onedrive/addon.py, plugin.onedrive/addon.xml, plugin.onedrive/changelog.txt, plugin.onedrive/resources/language/english/strings.po, plugin.onedrive/resources/lib/api/account.py, plugin.onedrive/resources/lib/api/onedrive.py
v1.3.1 released - Jun 9, 2017:
- Fix export to .strm
- Minor fixes
=> [plugin.onedrive] 1.3.1

plugin.video.psvue/main.py, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py
- Another fix for streams not launching …
=> [plugin.video.psvue] 2017.6.9

plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/changelog.txt, plugin.video.foodnetwork/readme.txt, plugin.video.foodnetwork/resources/lib/scraper.py
=> [plugin.video.foodnetwork] 3.0.5

plugin.video.worldstarhiphop/addon.xml, plugin.video.worldstarhiphop/changelog.txt, plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_const.py, plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_list.py, plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_search.py
v1.0.10 (2017-06-18):                                    
- changed getting title due to website changes           
- refactored getting video- and thumbnail-url
=> [plugin.video.worldstarhiphop] 1.0.10

plugin.video.wral/addon.xml, plugin.video.wral/changelog.txt, plugin.video.wral/readme.txt, plugin.video.wral/resources/lib/scraper.py
=> [plugin.video.wral] 3.0.7

plugin.audio.talandaviad/addon.xml, plugin.audio.talandaviad/changelog.txt
beautifulsoup4 version update
beautifulsoup4 version update …
=> [plugin.audio.talandaviad] 0.0.2

plugin.audio.talandaviad/addon.xml, plugin.audio.talandaviad/changelog.txt
* Update addon.xml
* Update changelog.txt
Requests module version update …
=> [plugin.audio.talandaviad] 0.0.3

plugin.video.powerunlimited/addon.xml, plugin.video.powerunlimited/changelog.txt, plugin.video.powerunlimited/resources/lib/powerunlimited_const.py, plugin.video.powerunlimited/resources/lib/powerunlimited_play.py
v1.0.6 (2017-06-20):
- fixed getting video due to website change
=> [plugin.video.powerunlimited] 1.0.6

plugin.video.nfl.gamepass/.github/ISSUE_TEMPLATE.md, plugin.video.nfl.gamepass/README.md, plugin.video.nfl.gamepass/addon.xml, plugin.video.nfl.gamepass/changelog.txt, plugin.video.nfl.gamepass/resources/lib/pigskin.py, plugin.video.nfl.gamepass/resources/skins/Default/1080i/script-gamepass.xml, plugin.video.nfl.gamepass/resources/skins/Default/720p/script-gamepass.xml
The GamePass service has been awarded to a new partner; the old service has been moved to a different DNS location until July 31st, when it will be shut down.
This update points to the new location of the old service while we work to update the addon to use the new GamePass service.
- This add-on repository has automated …
=> [plugin.video.nfl.gamepass] 0.10.2

plugin.video.snagfilms/README.txt, plugin.video.snagfilms/addon.xml, plugin.video.snagfilms/changelog.txt, plugin.video.snagfilms/resources/lib/scraper.py
=> [plugin.video.snagfilms] 3.0.6

plugin.video.mediacorp/README.txt, plugin.video.mediacorp/addon.xml, plugin.video.mediacorp/changelog.txt, plugin.video.mediacorp/resources/lib/scraper.py
=> [plugin.video.mediacorp] 3.0.5

plugin.video.rt/README.txt, plugin.video.rt/addon.xml, plugin.video.rt/changelog.txt, plugin.video.rt/resources/lib/scraper.py
=> [plugin.video.rt] 3.0.2

plugin.video.travel/README.txt, plugin.video.travel/addon.xml, plugin.video.travel/changelog.txt, plugin.video.travel/resources/lib/scraper.py
=> [plugin.video.travel] 3.0.3

plugin.video.psvue/addon.xml, plugin.video.psvue/main.py, plugin.video.psvue/resources/language/resource.language.en_gb/strings.po, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py, plugin.video.psvue/resources/settings.xml
- Yet another fix for streams not launching …
=> [plugin.video.psvue] 2017.7.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.18

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.10

plugin.video.psvue/addon.xml, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py
=> [plugin.video.psvue] 2017.7.2

plugin.video.travel/README.txt, plugin.video.travel/addon.xml, plugin.video.travel/changelog.txt, plugin.video.travel/resources/lib/scraper.py
=> [plugin.video.travel] 3.0.4

plugin.video.hgtv/README.txt, plugin.video.hgtv/addon.xml, plugin.video.hgtv/changelog.txt, plugin.video.hgtv/resources/lib/scraper.py
=> [plugin.video.hgtv] 3.0.9

plugin.video.diy/addon.xml, plugin.video.diy/changelog.txt, plugin.video.diy/readme.txt, plugin.video.diy/resources/lib/scraper.py
=> [plugin.video.diy] 3.0.7

plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/changelog.txt, plugin.video.foodnetwork/readme.txt, plugin.video.foodnetwork/resources/lib/scraper.py
=> [plugin.video.foodnetwork] 3.0.6

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.11

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.19

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.12

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.20

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/readme.txt, plugin.video.wnbc/resources/lib/scraper.py
=> [plugin.video.wnbc] 3.0.10

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/readme.txt, plugin.video.wnbc/resources/lib/scraper.py
=> [plugin.video.wnbc] 3.0.11

plugin.video.wral/addon.xml, plugin.video.wral/changelog.txt, plugin.video.wral/readme.txt, plugin.video.wral/resources/lib/scraper.py
=> [plugin.video.wral] 3.0.8

plugin.video.sapo/addon.xml
Marking this addon as broken as requested by original author
=> [plugin.video.sapo] broken

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/readme.txt, plugin.video.wnbc/resources/lib/scraper.py
=> [plugin.video.wnbc] 3.0.12

plugin.video.hallmark/README.txt, plugin.video.hallmark/addon.xml, plugin.video.hallmark/changelog.txt, plugin.video.hallmark/resources/lib/scraper.py
=> [plugin.video.hallmark] 3.0.6

plugin.audio.hearthis_at/addon.xml
fixed icon-path for proper building/submission to kodi-repos
=> [plugin.audio.hearthis_at] 1.0.1

plugin.audio.hearthis_at/addon.py, plugin.audio.hearthis_at/addon.xml, plugin.audio.hearthis_at/resources/language/resource.language.de_de/strings.po, plugin.audio.hearthis_at/resources/language/resource.language.en_gb/strings.po, plugin.audio.hearthis_at/resources/settings.xml
sorry for rapid PRs; oversaw a bug that made the plugin unusable for non-logged-in users
=> [plugin.audio.hearthis_at] 1.0.2

plugin.video.currenttime.tv/addon.py, plugin.video.currenttime.tv/addon.xml, plugin.video.currenttime.tv/changelog.txt
Brought it into line with provider changers plus reworked it a little to make it easily editable for future changes.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboar …
=> [plugin.video.currenttime.tv] 1.0.5

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.13

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.21

plugin.audio.eco99music/addon.py, plugin.audio.eco99music/addon.xml, plugin.audio.eco99music/changelog.txt
* Update changelog.txt
* Update addon.xml
* Update addon.py
Use different link for playlists …
=> [plugin.audio.eco99music] v0.0.2

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/clientinfo.py, plugin.video.embycon/resources/lib/downloadutils.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/menu_functions.py, plugin.video.embycon/resources/lib/translation.py, plugin.video.embycon/service.py
new version, add Latest TV Show Menu option …
=> [plugin.video.embycon] 1.3.20

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/default.py, plugin.video.ustvnow/resources/language/resource.language.en_gb/strings.po
=> [plugin.video.ustvnow] 2017.7.26

plugin.audio.calmradio/addon.xml, plugin.audio.calmradio/changelog.txt, plugin.audio.calmradio/intro.py, plugin.audio.calmradio/resources/settings.xml, plugin.audio.calmradio/user.py
* Update version
* Update changelog.txt
* Mask password field
* Disable SUA check
* Fix exit button bg color
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You …
=> [plugin.audio.calmradio] v0.2.7

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/default.py, plugin.video.ustvnow/resources/language/resource.language.en_gb/strings.po
=> [plugin.video.ustvnow] 2017.7.31

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/lib/datamanager.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/menu_functions.py, plugin.video.embycon/resources/lib/simple_logging.py, plugin.video.embycon/resources/lib/translation.py, plugin.video.embycon/resources/lib/utils.py, plugin.video.embycon/service.py
fixes a bug with wait for abort
add a few features …
=> [plugin.video.embycon] 1.3.24

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/default.py, plugin.video.ustvnow/resources/language/resource.language.en_gb/strings.po
=> [plugin.video.ustvnow] 2017.8.2

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py
=> [plugin.video.thinktv] 3.0.10

plugin.video.news12/addon.xml, plugin.video.news12/default.py, plugin.video.news12/resources/settings.xml
=> [plugin.video.news12] 1.0.1

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/default.py
=> [plugin.video.ustvnow] 2017.8.5

plugin.program.newgrounds/addon.py, plugin.program.newgrounds/addon.xml, plugin.program.newgrounds/changelog.txt, plugin.program.newgrounds/resources/language/english/strings.xml, plugin.program.newgrounds/resources/settings.xml
=> [plugin.programs.newgrounds] 1.0.3

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
Scraping fix. Marked Watched fix for Live Streams. …
=> [plugin.video.iplayerwww] 2.5.22

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
Scrape fix. Hide Watched fix for Live Streams. …
=> [plugin.video.iplayerwww] 3.0.14

plugin.audio.mixcloud/README, plugin.audio.mixcloud/addon.xml, plugin.audio.mixcloud/changelog.txt, plugin.audio.mixcloud/default.py, plugin.audio.mixcloud/resources/language/French/strings.xml, plugin.audio.mixcloud/resources/settings.xml
- added new resolver to fix broken mixcloud links
- modified french localisation
=> [plugin.audio.mixcloud] v2.2.0

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/language/French/strings.po, plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/__config__.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/subtitles.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py, plugin.video.youtube/resources/settings.xml
Updating Youtube Plugin 5.4.0 to 5.4.2
=> [plugin.video.youtube] 5.4.2

plugin.video.psvue/addon.xml, plugin.video.psvue/main.py, plugin.video.psvue/resources/language/resource.language.en_gb/strings.po, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py, plugin.video.psvue/resources/settings.xml
- Added All Channels section
- Added ability to add / remove channels to Favorite Channels via the context menu
- Added ability to add / remove shows to My Shows via the context menu
- Added more info to streams (resume time, duration, etc.)
- This add-on repository has automated code guideline check which could help you …
=> [plugin.video.psvue] 2017.8.12

plugin.video.nfl.gamepass/README.md, plugin.video.nfl.gamepass/addon.xml, plugin.video.nfl.gamepass/changelog.txt, plugin.video.nfl.gamepass/default.py, plugin.video.nfl.gamepass/resources/language/Dutch/strings.po, plugin.video.nfl.gamepass/resources/language/English/strings.po, plugin.video.nfl.gamepass/resources/language/German/strings.po, plugin.video.nfl.gamepass/resources/language/Japanese/strings.po, plugin.video.nfl.gamepass/resources/language/Russian/strings.po, plugin.video.nfl.gamepass/resources/language/Ukrainian/strings.po, plugin.video.nfl.gamepass/resources/lib/pigskin.py, plugin.video.nfl.gamepass/resources/settings.xml
This update adds support for Game Pass Europe but drops (hopefully temporarily) support for Game Pass International while we search for a developer with a Game Pass International subscription.
If you have any comments or questions, let me know.
---Alex …
=> [plugin.video.nfl.gamepass] 0.11.0

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/default.py, plugin.video.ustvnow/resources/language/resource.language.en_gb/strings.po, plugin.video.ustvnow/resources/settings.xml
=> [plugin.video.ustvnow] 2017.8.23

plugin.video.playonbrowser/addon.xml, plugin.video.playonbrowser/default.py
=> [plugin.video.playonbrowser] 2.0.1

plugin.video.nfl.gamepass/README.md, plugin.video.nfl.gamepass/addon.xml, plugin.video.nfl.gamepass/changelog.txt, plugin.video.nfl.gamepass/default.py, plugin.video.nfl.gamepass/resources/language/resource.language.de_de/strings.po, plugin.video.nfl.gamepass/resources/language/resource.language.en_gb/strings.po, plugin.video.nfl.gamepass/resources/language/resource.language.ja_jp/strings.po, plugin.video.nfl.gamepass/resources/language/resource.language.nl_nl/strings.po, plugin.video.nfl.gamepass/resources/language/resource.language.ru_ru/strings.po, plugin.video.nfl.gamepass/resources/language/resource.language.uk_ua/strings.po, plugin.video.nfl.gamepass/resources/lib/pigskin.py, plugin.video.nfl.gamepass/resources/settings.xml
=> [plugin.video.nfl.gamepass] 0.11.1

README.md
Fix markdown syntax for the links on the master branch
=> Fix links markdown

plugin.video.myvevo/README.txt, plugin.video.myvevo/addon.xml, plugin.video.myvevo/changelog.txt, plugin.video.myvevo/resources/lib/scraper.py
=> [plugin.video.myvevo] 3.0.7

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
=> [plugin.video.svtplay] 4.0.51

plugin.video.manoto/addon.xml, plugin.video.manoto/default.py
=> [plugin.video.manoto] 2.0.1

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/English/strings.po, plugin.video.twitch/resources/lib/addon/api.py, plugin.video.twitch/resources/lib/addon/common/cache.py, plugin.video.twitch/resources/lib/addon/common/kodi.py, plugin.video.twitch/resources/lib/addon/constants.py, plugin.video.twitch/resources/lib/addon/converter.py, plugin.video.twitch/resources/lib/addon/googl_shorten.py, plugin.video.twitch/resources/lib/addon/player.py, plugin.video.twitch/resources/lib/addon/strings.py, plugin.video.twitch/resources/lib/addon/utils.py, plugin.video.twitch/resources/lib/routes.py, plugin.video.twitch/resources/lib/service.py, plugin.video.twitch/resources/settings.xml
[plugin.video.twitch] 2.0.2
Requires script.module.python.twitch 1.0.2
Changes:
Fixes in response to Twitch API changes.
Thanks …
=> [plugin.video.twitch] 2.0.2

plugin.video.newsy/addon.xml, plugin.video.newsy/resources/lib/newsy.py
Added resolverurl cache, tweaked pagination end value. …
=> [plugin.video.newsy] 1.0.2

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/language/English/strings.xml, plugin.video.svtplay/resources/language/Swedish/strings.xml, plugin.video.svtplay/resources/lib/svt.py, plugin.video.svtplay/resources/settings.xml
=> [plugin.video.svtplay] 4.0.52

plugin.video.fitnessblenderv2/addon.xml
=> [plugin.video.fitnessblenderv2] v1.0.1

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
Version 2.0.5
- Updated links (Spinalcracker)
- Added Youtube feeds
- Added new shows
- Removed discontinued shows
- Fixed past audio podcasts
=> [plugin.video.infowars] 2.0.5

plugin.video.rivedila7/addon.py, plugin.video.rivedila7/addon.xml, plugin.video.rivedila7/changelog.txt, plugin.video.rivedila7/resources/language/English/strings.po, plugin.video.rivedila7/resources/language/Italian/strings.po
=> [plugin.video.rivedila7] 0.0.8

plugin.video.aktualnetv/addon.xml, plugin.video.aktualnetv/changelog.txt, plugin.video.aktualnetv/default.py
=> [plugin.video.aktualnetv] 2.0.1

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/svt.py
Better filtering for georestricted items …
=> [plugin.video.svtplay] 4.0.53

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
**Version 2.0.6**
- Updated links (Spinalcracker)
- Updated Youtube feeds
- Added War Room Youtube feed
- Cleaned up some code
** took suggestions from last release (2.0.5) and included them in this release (2.0.6)
=> [plugin.video.infowars] 2.0.6

plugin.video.spurs-tv/addon.xml, plugin.video.spurs-tv/changelog.txt, plugin.video.spurs-tv/resources/lib/new_stadium.py
Fixes the **New Stadium** > **Video Gallery** …
=> [plugin.video.spurs-tv] v2.14.1

plugin.video.sarpur/addon.xml, plugin.video.sarpur/changelog.txt, plugin.video.sarpur/default.py, plugin.video.sarpur/sarpur/__init__.py, plugin.video.sarpur/sarpur/actions.py, plugin.video.sarpur/sarpur/scraper.py
- Fixed the podcast index
- Fixed duration times
- Fixed live streams
- Added a live stream menu
=> [plugin.video.sarpur] 4.1.0

plugin.video.s04tv/addon.xml, plugin.video.s04tv/changelog.txt, plugin.video.s04tv/default.py
update due to website changes
- …
=> [plugin.video.s04tv] 3.1.2

plugin.video.nfl-teams/addon.py, plugin.video.nfl-teams/addon.xml, plugin.video.nfl-teams/changelog.txt, plugin.video.nfl-teams/resources/lib/nflc.py, plugin.video.nfl-teams/resources/lib/nflcs.py
- Fixed bug causing responses to be cached forever. I'm stupid.
=> [plugin.video.nfl-teams] 1.3.4

plugin.video.spurs-tv/addon.py, plugin.video.spurs-tv/addon.xml, plugin.video.spurs-tv/changelog.txt
Fixes the **Live Audio Commentary** item. …
=> [plugin.video.spurs-tv] v2.14.2

plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
VRT.Nu changed the way they work so i changed some things to work in the new way.
Also fixes a bug where some items would not be able to play.
Also changed my versioning system now it will start from v1.0.0.
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies …
=> [plugin.video.vrt.nu] 1.0.0

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.15

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.23

plugin.video.aktualnetv/addon.xml, plugin.video.aktualnetv/changelog.txt, plugin.video.aktualnetv/default.py
fix bug (video length parsing), improved live streaming and metadata handling …
=> [plugin.video.aktualnetv] 2.0.2

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.17

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.25

plugin.video.nba/addon.xml, plugin.video.nba/changelog.txt, plugin.video.nba/main.py, plugin.video.nba/resources/language/English/strings.po, plugin.video.nba/resources/settings.xml, plugin.video.nba/src/common.py, plugin.video.nba/src/games.py, plugin.video.nba/src/service.py, plugin.video.nba/src/shareddata.py, plugin.video.nba/src/vars.py
- Fix undefined variable for archive games
- Changed username to email
- Support variable bit rate HLS
- Fix (again) for utf8 chars in path …
=> [plugin.video.nba] v1.0.1

plugin.video.orftvthek/README.md, plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/default.py, plugin.video.orftvthek/resources/lib/base.py, plugin.video.orftvthek/resources/lib/helpers.py, plugin.video.orftvthek/resources/lib/htmlscraper.py, plugin.video.orftvthek/resources/lib/serviceapi.py
"Livestream Restart" working with html and serviceapi scraper …
=> [plugin.video.orftvthek] 0.8.0

plugin.video.aktualnetv/addon.xml, plugin.video.aktualnetv/changelog.txt, plugin.video.aktualnetv/default.py
cat-and-mouse game; fix for missing category in source page (this never happened before) …
=> [plugin.video.aktualnetv] 2.0.3

plugin.video.mytv_bg/addon.py, plugin.video.mytv_bg/addon.xml
=> [plugin.video.mytv_bg] 2.0.7

plugin.video.tvokids/README.txt, plugin.video.tvokids/addon.xml, plugin.video.tvokids/changelog.txt, plugin.video.tvokids/resources/lib/scraper.py
=> [plugin.video.tvokids] 3.0.2

plugin.video.metv/addon.xml
=> [plugin.video.metv] 3.0.5

plugin.video.pbskids/README.txt, plugin.video.pbskids/addon.xml, plugin.video.pbskids/changelog.txt, plugin.video.pbskids/resources/lib/scraper.py
=> [plugin.video.pbskids] 3.0.4

plugin.video.redbull.tv/addon.xml, plugin.video.redbull.tv/resources/lib/redbulltv_client.py
@Razzeee I just re-tested the API and noticed that RedBull has updated their API endpoints, so the add-on is no longer working. I was hoping to sneak this change in before my initial PR was merged (#1423), but just noticed that it went in last night - very unlucky timing, sorry.
I've made the minimum changes required to hopefully made code review and merge as simple as possible.
I'll also try kick of my integration tests nightly so I get quicker feedback if anything like this happens again, but tests are now passing: https://travis-ci.org/andy-g/kodi.plugin.video.redbulltv2
- [add-on …
=> [plugin.video.redbull.tv] v2.0.1

plugin.audio.ramfm/addon.xml, plugin.audio.ramfm/changelog.txt, plugin.audio.ramfm/default.py, plugin.audio.ramfm/resources/language/English/strings.xml
Closes #1375
I took the liberty to target gotham instead of krypton, as these changes seem to be compatible.
=> [plugin.audio.ramfm] 2.0.6

plugin.video.popcornflix/README.txt, plugin.video.popcornflix/addon.xml, plugin.video.popcornflix/changelog.txt, plugin.video.popcornflix/resources/lib/scraper.py
=> [plugin.video.popcornflix] 6.0.4

plugin.program.newgrounds/addon.py, plugin.program.newgrounds/addon.xml, plugin.program.newgrounds/changelog.txt
=> [plugin.program.newgrounds] 1.0.4

plugin.video.dailymotion_com/addon.xml, plugin.video.dailymotion_com/changelog.txt, plugin.video.dailymotion_com/default.py, plugin.video.dailymotion_com/resources/language/English/strings.po, plugin.video.dailymotion_com/resources/language/German/strings.po, plugin.video.dailymotion_com/resources/language/Hebrew/strings.po
[20171024]
- Add Hebrew Language
- Add Trending, Featured Categories
- Add Search by Live, User …
=> [plugin.video.dailymotion_com] v2.3.5

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.26

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.18

plugin.video.kermodeandmayo/addon.py, plugin.video.kermodeandmayo/addon.xml, plugin.video.kermodeandmayo/changelog.txt
Fixes the playing of video clips …
=> [plugin.video.kermodeandmayo] 0.5.3

plugin.video.currenttime.tv/addon.py, plugin.video.currenttime.tv/addon.xml, plugin.video.currenttime.tv/changelog.txt
=> [plugin.video.currenttime.tv] 1.0.6

plugin.video.massengeschmack/addon.xml, plugin.video.massengeschmack/changelog.txt
Fix required Python API version. …
=> [plugin.video.massengeschmack] 2.3.1

plugin.video.psvue/addon.xml, plugin.video.psvue/main.py, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py
=> [plugin.video.psvue] 2017.10.10

plugin.video.manoto/addon.xml, plugin.video.manoto/default.py, plugin.video.manoto/resources/language/English/strings.po
Stream URL changed, added a URL resolver with basic error handling …
=> [plugin.video.manoto] 2.1.0

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/ard.py, plugin.video.mediathek/mediathek/kika.py, plugin.video.mediathek/simplexbmc.py
FIX: KIKA and ARD implementation
=> [plugin.video.mediathek] 0.8.5

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py
=> [plugin.video.svtplay] 4.0.54

plugin.video.drnu/addon.py, plugin.video.drnu/addon.xml, plugin.video.drnu/changelog.txt, plugin.video.drnu/resources/language/Danish/strings.xml, plugin.video.drnu/resources/language/English/strings.xml, plugin.video.drnu/tvapi.py
Update of addon for Danish Broadcasting Corporation (dr.dk) 
Current version is broken after DR changed streams to https. Also subtitle support is updated.
I am invited by original maintainer @twinther to do the update as Tommy is not active in the project at this moment.
Development is in https://github.com/xbmc-danish-addons/plugin.video.drnu
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best …
=> [plugin.video.drnu] 5.0.10

plugin.video.nhlgcl/addon.xml, plugin.video.nhlgcl/resources/lib/globals.py, plugin.video.nhlgcl/resources/lib/nhl_tv.py, plugin.video.nhlgcl/resources/settings.xml
- Bug Fixes (stream quality, login) …
=> [plugin.video.nhlgcl] 2017.11.3

plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/changelog.txt, plugin.video.foodnetwork/readme.txt, plugin.video.foodnetwork/resources/lib/scraper.py
=> [plugin.video.foodnetwork] 3.0.7

plugin.video.fox.news/addon.xml, plugin.video.fox.news/changelog.txt, plugin.video.fox.news/default.py, plugin.video.fox.news/readme.txt
This is an ancient add-on which hasn't been modified in a few years, so there are many things not right current repo standards. The change is very minor and many users  are whining in the forum, so I hope this can be merged. …
=> [plugin.video.fox.news] 4.0.5

plugin.video.cook/addon.xml, plugin.video.cook/changelog.txt, plugin.video.cook/readme.txt, plugin.video.cook/resources/lib/scraper.py
=> [plugin.video.cook] 3.0.3

plugin.video.diy/addon.xml, plugin.video.diy/changelog.txt, plugin.video.diy/readme.txt, plugin.video.diy/resources/lib/scraper.py
=> [plugin.video.diy] 3.0.8

plugin.video.hgtv/README.txt, plugin.video.hgtv/addon.xml, plugin.video.hgtv/changelog.txt, plugin.video.hgtv/resources/lib/scraper.py
=> [plugin.video.hgtv] 3.0.10

plugin.video.npr/README.txt, plugin.video.npr/addon.xml, plugin.video.npr/changelog.txt, plugin.video.npr/resources/lib/scraper.py
Fix YouTube links, general cleanup …
=> [plugin.video.npr] 3.0.3

plugin.video.travel/README.txt, plugin.video.travel/addon.xml, plugin.video.travel/changelog.txt, plugin.video.travel/resources/lib/scraper.py
=> [plugin.video.travel] 3.0.5

plugin.audio.hearthis_at/addon.py, plugin.audio.hearthis_at/addon.xml
almost forgot i had a bugfix pending for the artist-search in my plugin. Change only consists of two missing brackets
=> [plugin.audio.hearthis_at] v1.0.3

plugin.video.hak5/addon.xml, plugin.video.hak5/changelog.txt, plugin.video.hak5/resources/lib/hak5_const.py, plugin.video.hak5/resources/lib/hak5_list_episodes.py, plugin.video.hak5/resources/lib/hak5_list_seasons.py, plugin.video.hak5/resources/lib/hak5_main.py, plugin.video.hak5/resources/lib/hak5_play.py
v1.0.2 (2017-11-12)
Fixes due to website changes …
=> [plugin.video.hak5] 1.0.2

plugin.video.ecbtv/addon.py, plugin.video.ecbtv/addon.xml, plugin.video.ecbtv/resources/language/resource.language.en_gb/strings.po, plugin.video.ecbtv/resources/lib/api.py
- Fix video browsing after website changes.
- Add additional categories …
=> [plugin.video.spurs-tv] 0.5.0

plugin.video.ustvnow/addon.xml
Addon.xml update, added missing dependency. …
=> [plugin.video.ustvnow] 2017.11.18

plugin.video.wnbc/addon.xml, plugin.video.wnbc/resources/lib/scraper.py
Fix playback timeout on Android. …
=> [plugin.video.wnbc] 3.0.13

plugin.video.ecbtv/addon.py, plugin.video.ecbtv/addon.xml, plugin.video.ecbtv/resources/language/resource.language.en_gb/strings.po, plugin.video.ecbtv/resources/lib/api.py
- Adds tournaments at the top level.
- Report errors to Rollbar. …
=> [plugin.video.ecbtv] 0.6.0

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.27

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.19

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/downloadutils.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/menu_functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/translation.py, plugin.video.embycon/resources/lib/utils.py, plugin.video.embycon/service.py
Latest version 
- Remove version check
- Add texture caching …
=> [plugin.video.embycon] 1.3.47

plugin.video.svtplay/README.md, plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/resources/lib/svt.py
=> [plugin.video.svtplay] 4.0.55

plugin.video.nhlgcl/addon.xml, plugin.video.nhlgcl/resources/lib/globals.py, plugin.video.nhlgcl/resources/lib/nhl_tv.py, plugin.video.nhlgcl/resources/settings.xml
- Fixed Settings invalid xml issue
- Fixed Quality selection issue …
=> [plugin.video.nhlgcl] 2017.11.28

plugin.video.btsportvideo/addon.py, plugin.video.btsportvideo/addon.xml, plugin.video.btsportvideo/resources/lib/api.py
Fixes some issues caused by occasional unexpected JSON responses. …
=> [plugin.video.btsportvideo] 0.1.1

plugin.video.mediacorp/README.txt, plugin.video.mediacorp/addon.xml, plugin.video.mediacorp/changelog.txt, plugin.video.mediacorp/resources/lib/scraper.py
=> [plugin.video.mediacorp] 3.0.7

plugin.video.gq/README.txt, plugin.video.gq/addon.xml, plugin.video.gq/changelog.txt, plugin.video.gq/resources/lib/scraper.py
=> [plugin.video.gq] 3.0.3

plugin.video.kla.tv/addon.py, plugin.video.kla.tv/addon.xml, plugin.video.kla.tv/resources/language/resource.language.de_de/strings.po, plugin.video.kla.tv/resources/language/resource.language.en_gb/strings.po, plugin.video.kla.tv/resources/language/resource.language.it_it/strings.po, plugin.video.kla.tv/resources/language/resource.language.nl_nl/strings.po, plugin.video.kla.tv/resources/language/resource.language.pl_pl/strings.po, plugin.video.kla.tv/resources/settings.xml
Updating for website changes and added 2 languages. …
=> [plugin.kla.tv] 0.0.7

plugin.video.rivedila7/addon.py, plugin.video.rivedila7/addon.xml, plugin.video.rivedila7/changelog.txt, plugin.video.rivedila7/resources/language/English/strings.po, plugin.video.rivedila7/resources/language/Italian/strings.po
=> [plugin.video.rivedila7] 1.0.0

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/live.py
=> [plugin.video.rtpplay] 2.6.1

plugin.video.vrt.nu/addon.py, plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py, plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py, plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Refactored code, thanks for merging
- …
=> [plugin.video.vrt.nu] 1.1.0

plugin.video.br3/addon.xml, plugin.video.disneychannel_de/addon.xml, plugin.video.nick_de/addon.xml, plugin.video.servustv_com/addon.xml, plugin.video.spiegel_tv/addon.xml, plugin.video.welt_der_wunder/addon.xml
Removed Addons that ar Broken, or my Own Addons i dont want in Kodi.tv
https://forum.kodi.tv/showthread.php?tid=325533
=> Marked Addons As Broken

plugin.video.aod/addon.xml, plugin.video.daisuki/addon.xml
Addon that are Borken marked as Broken
My Addons that i dont want to be anylonger in Kodi.tv,marked as Broken
https://forum.kodi.tv/showthread.php?tid=325533
=> Marked Broken Addons as Broken

plugin.video.4players/addon.xml, plugin.video.7tv/addon.xml, plugin.video.chefkoch_de/addon.xml, plugin.video.clipfish.de/addon.xml, plugin.video.myvideo_de/addon.xml
Makred Addons as Broken that are broken
=> Broken Addons

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/live.py
Please use `squash and merge` as I am out of space on my laptop to keep a clone locally.
=> [plugin.video.rtpplay] 2.6.2

plugin.video.disclose_tv/addon.xml
=> [plugin.video.disclose_tv] 2.0.0 Broken

plugin.video.media-ccc-de/README.md, plugin.video.media-ccc-de/addon.py, plugin.video.media-ccc-de/addon.xml, plugin.video.media-ccc-de/changelog.txt, plugin.video.media-ccc-de/resources/lib/helpers.py, plugin.video.media-ccc-de/resources/lib/http.py, plugin.video.media-ccc-de/resources/lib/stream.py, plugin.video.media-ccc-de/resources/lib/test_recording.py, plugin.video.media-ccc-de/resources/lib/test_stream.py, plugin.video.media-ccc-de/resources/lib/testdata.py
- Supports multiple translated streams (if available)
=> [plugin.video.media-ccc-de] v0.1.1

plugin.video.rtpplay/addon.xml
Removing this plugin from gotham and encourage users to update to the latest Kodi version. Please wait for the PR targeting Krypton.
Thanks
=> [plugin.video.rtpplay] broken

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/lib/plugin.py
Another episode of the cat and mouse game. Until they request a takedown to Team Kodi, I'll continue to fix it.
Cheers
=> [plugin.video.rtpplay] 3.0.1

plugin.video.infowars/LICENSE.txt, plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
**Version 2.0.7**
- Updated Youtube feeds (Spinalcracker)
=> [plugin.video.infowars] 2.0.7

plugin.video.crackler/addon.xml
Plugin no longer functions, New plugin found here: https://github.com/xbmc/repo-plugins/pull/1573 …
=> [plugin.video.crackler] 1.0.7 Broken

plugin.video.svtplay/addon.xml, plugin.video.svtplay/changelog.txt, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/svt.py
Major rewrite. Fixes playback issues for some items. …
=> [plugin.video.svtplay] 4.1.0

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/resources/language/resource.language.en_gb/strings.po, plugin.video.rtpplay/resources/lib/plugin.py, plugin.video.rtpplay/resources/settings.xml
=> [plugin.video.rtpplay] 3.0.2

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/resources/lib/plugin.py
=> [plugin.video.rtpplay] 3.0.3

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/resources/lib/plugin.py
=> [plugin.video.rtpplay] 3.0.4

plugin.video.s04tv/addon.xml, plugin.video.s04tv/changelog.txt, plugin.video.s04tv/default.py
update due to website changes
- …
=> [plugin.video.s04tv] 3.1.3

plugin.video.tweakers/addon.py, plugin.video.tweakers/addon.xml, plugin.video.tweakers/changelog.txt, plugin.video.tweakers/resources/lib/tweakers_const.py, plugin.video.tweakers/resources/lib/tweakers_list.py, plugin.video.tweakers/resources/lib/tweakers_play.py, plugin.video.tweakers/resources/lib/tweakers_search.py
v1.1.9 (2018-01-12)
- removed looking for video dialogue
- fix to match the correct thumbnail with the item
- addon now works in kode python 2 and also 3 (!!) thanks to the future project
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these …
=> [plugin.video.tweakers] 1.1.9

plugin.video.watchbox/README.md, plugin.video.watchbox/addon.xml, plugin.video.watchbox/changelog.txt, plugin.video.watchbox/resources/lib/login.py
Changes:
- Fixed login not working …
=> [plugin.video.watchbox] 0.4.1

plugin.video.wakanim/README.md, plugin.video.wakanim/addon.xml, plugin.video.wakanim/changelog.txt, plugin.video.wakanim/resources/language/resource.language.en_gb/strings.po, plugin.video.wakanim/resources/language/resource.language.fr_fr/strings.po, plugin.video.wakanim/resources/language/resource.language.he_il/strings.po, plugin.video.wakanim/resources/language/resource.language.ru_ru/strings.po, plugin.video.wakanim/resources/lib/login.py, plugin.video.wakanim/resources/lib/netapi.py, plugin.video.wakanim/resources/lib/view.py, plugin.video.wakanim/resources/lib/wakanim.py, plugin.video.wakanim/resources/settings.xml
Changes:
- Added support for Wakanim Russia
- Added russian language …
=> [plugin.video.wakanim] 0.6.0

plugin.video.cheddar/addon.xml, plugin.video.cheddar/default.py, plugin.video.cheddar/resources/language/resource.language.en_gb/strings.po, plugin.video.cheddar/resources/lib/cheddar.py, plugin.video.cheddar/resources/settings.xml
=> [plugin.video.cheddar] 1.0.2

plugin.video.johnlocker/addon.xml
Marked as broken. Site no longer exists.
=> [plugin.video.johnlocker] 3.0.1

plugin.video.spiketv/addon.xml
=> [plugin.video.spiketv] 1.0.2

plugin.video.currenttime.tv/addon.py, plugin.video.currenttime.tv/addon.xml, plugin.video.currenttime.tv/changelog.txt
=> [plugin.video.currenttime.tv] 1.0.7

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/routes.py
Bugfix
Fixes playback on Isengard …
=> [plugin.video.twitch] 2.1.1

plugin.image.dumpert/addon.xml, plugin.image.dumpert/changelog.txt, plugin.image.dumpert/default.py
v1.0.1 (2018-01-20):
- added forum thread link …
=> [plugin.image.dumpert] 1.0.1

plugin.video.newson/addon.xml, plugin.video.newson/default.py, plugin.video.newson/resources/lib/newson.py
=> [plugin.video.newson] 1.0.4

plugin.video.gamekings/addon.py, plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/language/Dutch/strings.po, plugin.video.gamekings/resources/language/English/strings.po, plugin.video.gamekings/resources/lib/gamekings_const.py, plugin.video.gamekings/resources/lib/gamekings_list.py, plugin.video.gamekings/resources/lib/gamekings_main.py, plugin.video.gamekings/resources/lib/gamekings_play.py, plugin.video.gamekings/resources/lib/gamekings_search.py, plugin.video.gamekings/resources/settings.xml
v1.2.11 (2018-01-20)
- removed looking for video dialogue
- changed order of categories
- adding a setting to only view Videos category
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice …
=> [plugin.video.gamekings] 1.2.11

plugin.video.dazn/README.md, plugin.video.dazn/addon.py, plugin.video.dazn/addon.xml, plugin.video.dazn/resources/language/resource.language.de_de/strings.po, plugin.video.dazn/resources/language/resource.language.en_gb/strings.po, plugin.video.dazn/resources/language/resource.language.fr_ca/strings.po, plugin.video.dazn/resources/language/resource.language.fr_fr/strings.po, plugin.video.dazn/resources/lib/client.py, plugin.video.dazn/resources/lib/common.py, plugin.video.dazn/resources/lib/context.py, plugin.video.dazn/resources/lib/simple_requests/api.py
added missing self. in class + some minor changes/clean up …
=> [plugin.video.dazn] 1.0.7

plugin.video.botchamania/addon.py, plugin.video.botchamania/addon.xml, plugin.video.botchamania/changelog.txt, plugin.video.botchamania/resources/lib/botchamania_const.py, plugin.video.botchamania/resources/lib/botchamania_play.py
v1.1.7 (2018-01-25)
- fix to prevent import error on youtubedl …
=> [plugin.video.botchamania] 1.1.7

plugin.video.gamegurumania/addon.py, plugin.video.gamegurumania/addon.xml, plugin.video.gamegurumania/changelog.txt, plugin.video.gamegurumania/resources/language/Dutch/strings.po, plugin.video.gamegurumania/resources/language/English/strings.po, plugin.video.gamegurumania/resources/lib/gamegurumania_const.py, plugin.video.gamegurumania/resources/lib/gamegurumania_list_play.py, plugin.video.gamegurumania/resources/lib/gamegurumania_main.py, plugin.video.gamegurumania/resources/settings.xml
v1.0.7 (2018-01-20)
- adding a setting to only view all video category
- This add-on repository has automated code …
=> [plugin.video.gamegurumania] 1.0.7

plugin.video.beergeeks/addon.xml, plugin.video.beergeeks/changelog.txt
- Backend video streams are no longer available …
=> [plugin.video.beergeeks] 2018.1.26 broken

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt, plugin.video.ign_com/default.py, plugin.video.ign_com/resources/settings.xml
v2.3.4 (2018-01-20)
- using requests
- This add-on repository has automated code guideline check which could help …
=> [plugin.video.ign_com] 2.3.4

plugin.video.hak5/addon.py, plugin.video.hak5/addon.xml, plugin.video.hak5/changelog.txt, plugin.video.hak5/resources/lib/hak5_const.py, plugin.video.hak5/resources/lib/hak5_list_episodes.py, plugin.video.hak5/resources/lib/hak5_list_seasons.py, plugin.video.hak5/resources/lib/hak5_main.py, plugin.video.hak5/resources/lib/hak5_play.py, plugin.video.hak5/resources/settings.xml
v1.0.3 (2018-01-20)
- Fixed settings.xml
- This add-on repository has automated code guideline check which could …
=> [plugin.video.hak5] 1.0.3

plugin.video.roosterteeth/addon.py, plugin.video.roosterteeth/addon.xml, plugin.video.roosterteeth/changelog.txt, plugin.video.roosterteeth/resources/lib/roosterteeth_const.py, plugin.video.roosterteeth/resources/lib/roosterteeth_list_episodes.py, plugin.video.roosterteeth/resources/lib/roosterteeth_list_shows.py, plugin.video.roosterteeth/resources/lib/roosterteeth_main.py, plugin.video.roosterteeth/resources/lib/roosterteeth_play.py
1.3.5 (2018-02-21)
- removed looking for video dialogue
- This add-on repository has automated code guideline check …
=> [plugin.video.roosterteeth] 1.3.5

plugin.video.tekthing/addon.py, plugin.video.tekthing/addon.xml, plugin.video.tekthing/changelog.txt
=> [plugin.video.tekthing] 1.0.2

plugin.video.crackle/addon.xml, plugin.video.crackle/main.py, plugin.video.crackle/resources/lib/globals.py
- Added support for inputstream adaptive
- Code clean up …
=> [plugin.video.crackle] 2018.1.27

plugin.video.amaproracing/addon.xml, plugin.video.amaproracing/main.py
- Fixed bug with supercross race day live stream …
=> [plugin.video.amaproracing] 2018.1.27
