plugin.audio.rne/addon.xml, plugin.audio.rne/changelog.txt, plugin.audio.rne/default.py, plugin.audio.rne/resources/lib/rne_api.py, plugin.audio.rne/resources/tests/test_api.py
Hi,
This is a new update for add-on plugin.audio.rne:
Changelog: 1.0.9 (2018.01.30)
- Quick fix for direct channels.
- Added search option for each program (thanks to crashillo for his suggestion).
- Updated integration tests due to code changes.
- Minor changes and fixes.
Thanks a lot in advance and best regards,
jamontes.
- Submitting your add-on to this specific …
=> [plugin.audio.rne] 1.0.9

plugin.video.roosterteeth/addon.xml, plugin.video.roosterteeth/changelog.txt, plugin.video.roosterteeth/resources/language/English/strings.po, plugin.video.roosterteeth/resources/lib/roosterteeth_const.py, plugin.video.roosterteeth/resources/lib/roosterteeth_play.py, plugin.video.roosterteeth/resources/settings.xml
1.3.6 (2018-01-31)
- fixed showing videos in selected video quality …
=> [plugin.video.roosterteeth] 1.3.6

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/action_menu.py, plugin.video.embycon/resources/lib/clientinfo.py, plugin.video.embycon/resources/lib/datamanager.py, plugin.video.embycon/resources/lib/downloadutils.py, plugin.video.embycon/resources/lib/error.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/item_functions.py, plugin.video.embycon/resources/lib/kodi_utils.py, plugin.video.embycon/resources/lib/menu_functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/server_detect.py, plugin.video.embycon/resources/lib/server_sessions.py, plugin.video.embycon/resources/lib/simple_logging.py, plugin.video.embycon/resources/lib/trakttokodi.py, plugin.video.embycon/resources/lib/translation.py, plugin.video.embycon/resources/lib/utils.py, plugin.video.embycon/resources/lib/websocket.py, plugin.video.embycon/resources/lib/websocket_client.py, plugin.video.embycon/resources/lib/widgets.py, plugin.video.embycon/resources/settings.xml, plugin.video.embycon/resources/skins/skin.estuary/xml/Home-17.1.xml, plugin.video.embycon/resources/skins/skin.estuary/xml/Home-17.3-elec.xml, plugin.video.embycon/resources/skins/skin.estuary/xml/Home-17.6.xml, plugin.video.embycon/service.py
Latest release of EmbyCon (1.4)
- Lots of code refactoring
- Removed some redundant code
- Change the way playback works, now uses a Notification service to listen for play events
- Send Notifications for Play/Display/Stop actions
- Add error reporting prompt
- Refactor the way logging works
- Add music support
- This …
=> [plugin.video.embycon] 1.4.39

plugin.video.popcornflix/addon.xml, plugin.video.popcornflix/resources/lib/scraper.py
=> [plugin.video.popcornflix] 6.0.5

plugin.video.rt/README.txt, plugin.video.rt/addon.xml, plugin.video.rt/changelog.txt, plugin.video.rt/resources/lib/scraper.py
=> [plugin.video.rt] 3.0.3

plugin.video.wakanim/README.md, plugin.video.wakanim/addon.xml, plugin.video.wakanim/changelog.txt, plugin.video.wakanim/resources/language/resource.language.de_de/strings.po, plugin.video.wakanim/resources/language/resource.language.en_gb/strings.po, plugin.video.wakanim/resources/language/resource.language.fr_fr/strings.po, plugin.video.wakanim/resources/language/resource.language.he_il/strings.po, plugin.video.wakanim/resources/language/resource.language.ru_ru/strings.po, plugin.video.wakanim/resources/lib/login.py, plugin.video.wakanim/resources/lib/netapi.py, plugin.video.wakanim/resources/lib/view.py, plugin.video.wakanim/resources/lib/wakanim.py, plugin.video.wakanim/resources/settings.xml
Changes:
- Added dependency for script.module.inputstreamhelper
- Added Widevine DRM support
- Added watchlist
- Added last aired episodes list (thanks AkariDN)
- Added new simulcasts list
- Added synchronize of playback stats
- Added dialog to resume playback
- Multiple fixes (thanks AkariDN)
New Videos on Wakanim are released with Widevine DRM.
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best …
=> [plugin.video.wakanim] 0.7.1

plugin.video.akibapass/README.md, plugin.video.akibapass/addon.xml, plugin.video.akibapass/changelog.txt, plugin.video.akibapass/resources/language/resource.language.de_de/strings.po, plugin.video.akibapass/resources/language/resource.language.en_gb/strings.po, plugin.video.akibapass/resources/lib/akibapass.py, plugin.video.akibapass/resources/lib/netapi.py, plugin.video.akibapass/resources/lib/view.py
Changes:
- Added last aired episodes list
- Added new simulcasts list
- Some fixes …
=> [plugin.video.akibapass] 0.6.0

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_radio.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.21

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_radio.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.29

plugin.video.travel/README.txt, plugin.video.travel/addon.xml, plugin.video.travel/changelog.txt, plugin.video.travel/resources/lib/scraper.py
=> [plugin.video.travel] 3.0.7

plugin.video.hgtv/README.txt, plugin.video.hgtv/addon.xml, plugin.video.hgtv/changelog.txt, plugin.video.hgtv/resources/lib/scraper.py
=> [plugin.video.hgtv] 3.0.11

plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/changelog.txt, plugin.video.foodnetwork/readme.txt, plugin.video.foodnetwork/resources/lib/scraper.py
=> [plugin.video.foodnetwork] 3.0.8

plugin.video.diy/LICENSE.txt, plugin.video.diy/addon.xml, plugin.video.diy/changelog.txt, plugin.video.diy/readme.txt, plugin.video.diy/resources/lib/scraper.py
=> [plugin.video.diy] 3.0.9

plugin.video.cook/LICENSE.txt, plugin.video.cook/addon.xml, plugin.video.cook/resources/lib/scraper.py
=> [plugin.video.cook] 3.0.4

plugin.video.foodnetwork/LICENSE.txt, plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/changelog.txt, plugin.video.foodnetwork/readme.txt, plugin.video.foodnetwork/resources/lib/scraper.py
=> Isengard plugin.video.foodnetwork 3.0.9

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.22

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.30

plugin.video.nbcsnliveextra/addon.xml, plugin.video.nbcsnliveextra/nbcsn.py
=> [plugin.video.nbcsnliveextra] 2018.2.10

plugin.video.floptv/addon.xml, plugin.video.floptv/changelog.txt, plugin.video.floptv/default.py, plugin.video.floptv/resources/lib/floptv.py
**2.0.1**
- updated HTML parsing due to upstream changes.
- added li.setInfo video for Kodi 18. …
=> [plugin.video.floptv] 2.0.1

plugin.video.supertennis/addon.xml, plugin.video.supertennis/changelog.txt, plugin.video.supertennis/default.py, plugin.video.supertennis/resources/lib/live.py
**1.2.2**
- Updated HTML parsing due to upstream changes.
- Added li.setInfo video for Kodi 18.
- Swapped to mobile stream because the website stream is currently unavailable. …
=> [plugin.video.supertennis] 1.2.2

plugin.video.abcfamily/LICENSE.txt, plugin.video.abcfamily/addon.xml, plugin.video.abcfamily/changelog.txt, plugin.video.abcfamily/readme.txt, plugin.video.abcfamily/resources/lib/scraper.py
=> [plugin.video.abcfamily] 3.0.6

plugin.image.moebooru/addon.xml, plugin.image.moebooru/changelog.txt, plugin.image.moebooru/default.py
=> [plugin.image.moebooru] 0.9.6

plugin.video.tviplayer/addon.py, plugin.video.tviplayer/addon.xml, plugin.video.tviplayer/changelog.txt, plugin.video.tviplayer/resources/common_variables.py, plugin.video.tviplayer/resources/directory.py, plugin.video.tviplayer/resources/language/English/strings.po, plugin.video.tviplayer/resources/language/Portuguese (Brazil)/strings.po, plugin.video.tviplayer/resources/language/Portuguese/strings.po, plugin.video.tviplayer/resources/net.py, plugin.video.tviplayer/resources/ondemand.py, plugin.video.tviplayer/resources/utilities.py, plugin.video.tviplayer/resources/webutils.py
- Fix resolver 
- Add live chanel …
=> [plugin.video.tviplayer] 0.3.0

plugin.video.multichannel/addon.xml, plugin.video.multichannel/resources/lib/multichannel.py
=> [plugin.video.multichannel] 1.0.1

plugin.video.newsblender/addon.xml, plugin.video.newsblender/resources/lib/newsblender.py
=> [plugin.video.newsblender] 1.0.1

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/readme.txt, plugin.video.wnbc/resources/lib/scraper.py
=> [plugin.video.wnbc] 3.0.14

plugin.video.cook/addon.xml, plugin.video.cook/changelog.txt, plugin.video.cook/readme.txt, plugin.video.cook/resources/lib/scraper.py
=> [plugin.video.cook] 3.0.5

plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/changelog.txt, plugin.video.foodnetwork/readme.txt, plugin.video.foodnetwork/resources/lib/scraper.py
=> [plugin.video.foodnetwork] 3.0.10

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/downloadutils.py, plugin.video.embycon/resources/lib/error.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/item_functions.py, plugin.video.embycon/resources/lib/menu_functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/server_detect.py, plugin.video.embycon/resources/lib/translation.py, plugin.video.embycon/resources/lib/utils.py, plugin.video.embycon/resources/lib/websocket_client.py, plugin.video.embycon/resources/settings.xml, plugin.video.embycon/service.py
Fast follow update to fix a few little things there were broken or missed in the last big update. …
=> [plugin.video.embycon] 1.4.49

plugin.video.psvue/addon.xml, plugin.video.psvue/main.py, plugin.video.psvue/resources/language/resource.language.en_gb/strings.po, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py, plugin.video.psvue/resources/settings.xml
- Kodi will now post resume times to sony servers, so show watch status and resume points are reflected in official apps
- Increased result size returned for kids, sports and episode sections
- Bug fixes and performance enhancements
- This add-on repository has automated code guideline check which could help you improve …
=> [plugin.video.psvue] 2018.2.15

plugin.video.viaplay/README.md, plugin.video.viaplay/addon.xml, plugin.video.viaplay/changelog.txt, plugin.video.viaplay/default.py, plugin.video.viaplay/resources/language/resource.language.en_gb/strings.po, plugin.video.viaplay/resources/lib/addon.py, plugin.video.viaplay/resources/lib/kodihelper.py, plugin.video.viaplay/resources/lib/viaplay.py, plugin.video.viaplay/resources/settings.xml
+ New dependency: script.module.routing
+ Support for 4K streams and 5.1 audio
+ Fix audio bug on some sports streams (requires Kodi v18 Leia)
+ Channels section improvements
+ Code cleanup
Please merge after https://github.com/xbmc/repo-scripts/pull/779. …
=> [plugin.video.viaplay] 2.1.1

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/lib/plugin.py
=> [plugin.video.rtpplay] 3.0.6

plugin.video.diy/addon.xml, plugin.video.diy/changelog.txt, plugin.video.diy/readme.txt, plugin.video.diy/resources/lib/scraper.py
=> [plugin.video.diy] 3.0.10

plugin.video.hgtv/README.txt, plugin.video.hgtv/addon.xml, plugin.video.hgtv/changelog.txt, plugin.video.hgtv/resources/lib/scraper.py
=> [plugin.video.hgtv] 3.0.12

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/resource.language.cs_cz/strings.po, plugin.video.twitch/resources/language/resource.language.da_dk/strings.po, plugin.video.twitch/resources/language/resource.language.de_de/strings.po, plugin.video.twitch/resources/language/resource.language.en_gb/strings.po, plugin.video.twitch/resources/language/resource.language.es_es/strings.po, plugin.video.twitch/resources/language/resource.language.fr_fr/strings.po, plugin.video.twitch/resources/language/resource.language.he_il/strings.po, plugin.video.twitch/resources/language/resource.language.nb_no/strings.po, plugin.video.twitch/resources/language/resource.language.nl_nl/strings.po, plugin.video.twitch/resources/language/resource.language.pl_pl/strings.po, plugin.video.twitch/resources/lib/addon/common/__init__.py, plugin.video.twitch/resources/lib/addon/common/kodi.py, plugin.video.twitch/resources/lib/addon/common/search_history.py, plugin.video.twitch/resources/lib/addon/common/storage.py, plugin.video.twitch/resources/lib/addon/constants.py, plugin.video.twitch/resources/lib/addon/converter.py, plugin.video.twitch/resources/lib/addon/menu_items.py, plugin.video.twitch/resources/lib/addon/search_history.py, plugin.video.twitch/resources/lib/addon/strings.py, plugin.video.twitch/resources/lib/addon/utils.py, plugin.video.twitch/resources/lib/routes.py, plugin.video.twitch/resources/lib/service.py, plugin.video.twitch/resources/settings.xml
[add] Search history
[add] Settings - Maintenance
[fix] VodCast highlighting …
=> [plugin.video.twitch] 2.2.0

plugin.video.arteplussept/.gitignore, plugin.video.arteplussept/CHANGELOG.md, plugin.video.arteplussept/addon.py, plugin.video.arteplussept/addon.xml, plugin.video.arteplussept/changelog.txt, plugin.video.arteplussept/resources/settings.xml
Hotfix to support new arte API
Many features removed (until fixed) …
=> [plugin.video.arteplussept] 0.5.8

plugin.video.hsn/addon.xml, plugin.video.hsn/resources/lib/hsn.py
=> [plugin.video.hsn] 1.0.1

plugin.video.rocketbeans/addon.xml, plugin.video.rocketbeans/changelog.txt, plugin.video.rocketbeans/resources/lib/plugin.py
Fix bug introduced due to last repo review 🥇  …
=> [plugin.video.rocketbeans] 1.1.1

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/default.py, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.31

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerww] 3.0.23

plugin.video.newsblender/addon.xml, plugin.video.newsblender/default.py, plugin.video.newsblender/resources/lib/newsblender.py
=> [plugin.video.newsblender] 1.0.2

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.24

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.32

plugin.video.metalvideo/addon.py, plugin.video.metalvideo/addon.xml, plugin.video.metalvideo/resources/language/resource.language.he_il/strings.po
* Update video resolver.
* Use urlquick directly.
* Some minor changes.
=> [plugin.video.metalvideo] 3.0.5

plugin.video.travel/README.txt, plugin.video.travel/addon.xml, plugin.video.travel/changelog.txt, plugin.video.travel/resources/lib/scraper.py
=> [plugin.video.travel] 3.0.8

plugin.video.embycon/addon.xml, plugin.video.embycon/contextmenu.py, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/clientinfo.py, plugin.video.embycon/resources/lib/downloadutils.py, plugin.video.embycon/resources/lib/error.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/item_functions.py, plugin.video.embycon/resources/lib/kodi_utils.py, plugin.video.embycon/resources/lib/menu_functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/server_detect.py, plugin.video.embycon/resources/lib/simple_logging.py, plugin.video.embycon/resources/lib/translation.py, plugin.video.embycon/resources/lib/utils.py, plugin.video.embycon/resources/lib/widgets.py, plugin.video.embycon/resources/skins/skin.estuary/xml/Home-17.6.xml, plugin.video.embycon/service.py
Monthly bug fix and feature fix release.
- Use addon context menu for all item menus
- Fix error logging string issue
- Dont use Addon(id="addon id") as I think it is causing issues on some systems
- When deleting show name of thing being deleted
- Set a background image for skins to use
- Set some window props for the Emby user library for skins to use 
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered …
=> [plugin.video.embycon] 1.4.62

plugin.video.arretsurimages/addon.xml
Add-on broken due to new website
=> [plugin.video.arretsurimages] broken

plugin.video.comedycentral/addon.xml, plugin.video.comedycentral/resources/language/resource.language.en_gb/strings.po, plugin.video.comedycentral/resources/lib/comedycentral.py
=> [plugin.video.comedycentral] 1.0.1

plugin.video.liveleak/addon.xml, plugin.video.liveleak/changelog.txt, plugin.video.liveleak/default.py, plugin.video.liveleak/resources/language/resource.language.en_gb/strings.po
v1.3.3 (2018-3-11)
- Add fallback for multiprocessing module not available
v1.3.2 (2018-3-9)
- Adapt after Liveleak.com upgrade
v1.3.1 (2018-2-11)
- Improve handling of video description Info
v1.3.0 (2018-1-23)
- Add ability to moderate Liveleak users' postings
v1.2.0 (2018-1-21)
- Implement multiple page fetche threading for improved performance
=> [plugin.video.liveleak] 1.3.3

plugin.video.earthcam/addon.xml, plugin.video.earthcam/resources/lib/earthcam.py
=> [plugin.video.earthcam] 1.0.2

plugin.video.comedycentral/addon.xml, plugin.video.comedycentral/resources/lib/comedycentral.py
=> [plugin.video.comedycentral] 1.0.2

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.2

plugin.video.hsn/addon.xml, plugin.video.hsn/resources/lib/hsn.py
=> [plugin.video.hsn] 1.0.2

plugin.video.psvue/addon.xml, plugin.video.psvue/resources/lib/ps_vue.py
- Fixed issue where airing times were wrong …
=> [plugin.video.psvue] 2018.3.23

plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/lib/gamekings_const.py, plugin.video.gamekings/resources/lib/gamekings_list.py
v1.2.12 (2018-03-24)
- fixed video category (website changes) …
=> [plugin.video.gamekings] 1.2.12

plugin.video.psvue/addon.xml, plugin.video.psvue/resources/lib/ps_vue.py
- Re-enable inputstream adaptive …
=> [plugin.video.psvue] 2018.3.24

plugin.video.cbc/addon.xml, plugin.video.cbc/default.py, plugin.video.cbc/resources/lib/cbc.py, plugin.video.cbc/resources/lib/shows.py, plugin.video.cbc/resources/lib/utils.py
- fix auth problems hopefully
- play videos as videos
- clean up handling of live streams
- add duration
- fix http 500 status as well
- fix watched state
=> [plugin.video.cbc] 4.0.1

plugin.video.filmsforaction/addon.xml, plugin.video.filmsforaction/changelog.txt, plugin.video.filmsforaction/default.py, plugin.video.filmsforaction/resources/language/English/strings.xml, plugin.video.filmsforaction/resources/language/French/strings.xml, plugin.video.filmsforaction/resources/language/German/strings.xml, plugin.video.filmsforaction/resources/language/Spanish/strings.xml, plugin.video.filmsforaction/resources/lib/ffa_api.py, plugin.video.filmsforaction/resources/settings.xml, plugin.video.filmsforaction/resources/tests/test_api.py
Hi,
This is a maintenance update for filmsforacton video add-on.
Changelog: 1.0.9 (2018.03.30)
- Minor fixes due to website changes.
- Added sort by most viewed/recent option from add-on settings menu.
Thanks a lot in advance for your help and best regards,
jamontes.
- This add-on repository has automated code guideline …
=> [plugin.video.filmsforaction] 1.0.9

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py
Try to add multiple seasons listings for episodes …
=> [plugin.video.thinktv] 3.0.12

plugin.video.charge/README.txt, plugin.video.charge/addon.xml, plugin.video.charge/changelog.txt, plugin.video.charge/resources/lib/scraper.py
Version 3.0.3 fix program listing - pains me to fix this because the idiot clown plagurist will have the fix as well
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboar …
=> [plugin.video.charge] 3.0.3

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/resource.language.cs_cz/strings.po, plugin.video.twitch/resources/language/resource.language.da_dk/strings.po, plugin.video.twitch/resources/language/resource.language.de_de/strings.po, plugin.video.twitch/resources/language/resource.language.en_gb/strings.po, plugin.video.twitch/resources/language/resource.language.es_es/strings.po, plugin.video.twitch/resources/language/resource.language.fr_fr/strings.po, plugin.video.twitch/resources/language/resource.language.he_il/strings.po, plugin.video.twitch/resources/language/resource.language.nb_no/strings.po, plugin.video.twitch/resources/language/resource.language.nl_nl/strings.po, plugin.video.twitch/resources/language/resource.language.pl_pl/strings.po, plugin.video.twitch/resources/lib/addon/converter.py, plugin.video.twitch/resources/lib/addon/utils.py, plugin.video.twitch/resources/settings.xml
[add] allow Adaptive as default quality …
=> [plugin.video.twitch] 2.2.1

plugin.audio.ramfm/addon.xml, plugin.audio.ramfm/changelog.txt, plugin.audio.ramfm/default.py
Updated high quality stream URL
=> [plugin.audio.ramfm] 2.0.7

plugin.video.3bmeteo/addon.xml, plugin.video.3bmeteo/changelog.txt, plugin.video.3bmeteo/default.py
Use 3bmeteo Android app user agent …
=> [plugin.video.3bmeteo] 1.0.1

plugin.video.rocketbeans/addon.py, plugin.video.rocketbeans/addon.xml, plugin.video.rocketbeans/changelog.txt, plugin.video.rocketbeans/resources/data/config.py, plugin.video.rocketbeans/resources/language/resource.language.de_DE/strings.po, plugin.video.rocketbeans/resources/language/resource.language.en_GB/strings.po, plugin.video.rocketbeans/resources/lib/guide.py, plugin.video.rocketbeans/resources/lib/plugin.py, plugin.video.rocketbeans/resources/lib/twitch.py, plugin.video.rocketbeans/resources/lib/youtube.py
- Utf-8 changes
- Added new network channel …
=> [plugin.video.rocketbeans] 1.1.3

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/default.py, plugin.video.orftvthek/resources/lib/base.py, plugin.video.orftvthek/resources/lib/htmlscraper.py, plugin.video.orftvthek/resources/lib/serviceapi.py
fixed 403 errors caused by uncommon UA### Checklist:
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about …
=> [plugin.video.orftvthek] 0.8.2

plugin.video.cbc/addon.xml, plugin.video.cbc/resources/lib/shows.py, plugin.video.cbc/resources/lib/utils.py
* bump client version to sufficiently high version
=> [plugin.video.cbc] 4.0.2

plugin.video.hdhomerun.simple/addon.xml, plugin.video.hdhomerun.simple/resources/lib/hdhomerun.py
=> [plugin.video.hdhomerun.simple] 1.0.1

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/server_sessions.py, plugin.video.embycon/resources/lib/widgets.py, plugin.video.embycon/resources/settings.xml
April release of EmbyCon
- Small change the dynamic cast list
- Set window prop for playing Emby item ID
- Bug fixes
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboar …
=> [plugin.video.embycon] 1.4.67

plugin.video.plutotv/addon.xml, plugin.video.plutotv/resources/language/resource.language.en_gb/strings.po, plugin.video.plutotv/resources/lib/plutotv.py
=> [plugin.video.plutotv] 1.0.9

plugin.video.newson/addon.xml, plugin.video.newson/resources/language/resource.language.en_gb/strings.po, plugin.video.newson/resources/lib/newson.py
=> [plugin.video.newson] 1.0.5

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/resources/language/resource.language.en_gb/strings.po, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.3

plugin.video.creationtoday_org/addon.xml, plugin.video.creationtoday_org/changelog.txt, plugin.video.creationtoday_org/default.py
With the permission of the developer in https://github.com/Romans-I-XVI/plugin.video.creationtoday_org/pull/1
=> [plugin.video.creationtoday_org] 1.0.2

plugin.video.eurosportplayer/addon.xml, plugin.video.eurosportplayer/resources/language/resource.language.de_de/strings.po, plugin.video.eurosportplayer/resources/language/resource.language.en_gb/strings.po, plugin.video.eurosportplayer/resources/lib/common.py, plugin.video.eurosportplayer/resources/lib/hits.py, plugin.video.eurosportplayer/resources/lib/items.py, plugin.video.eurosportplayer/resources/lib/parser.py, plugin.video.eurosportplayer/resources/settings.xml
added view settings + 2 bug fixes
=> [plugin.video.eurosportplayer] 2.0.10

plugin.video.tvcatchups/addon.xml, plugin.video.tvcatchups/resources/language/resource.language.en_gb/strings.po, plugin.video.tvcatchups/resources/lib/tvcatchup.py
=> [plugin.video.tvcatchups] 1.0.1

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/resources/language/resource.language.en_gb/strings.po, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.4

plugin.video.hdhomerun.simple/addon.xml, plugin.video.hdhomerun.simple/resources/lib/hdhomerun.py
=> [plugin.video.hdhomerun.simple] 1.0.2

plugin.video.watchbox/addon.xml, plugin.video.watchbox/changelog.txt, plugin.video.watchbox/resources/lib/api.py, plugin.video.watchbox/resources/lib/controller.py
Changes:
- Fixed some crashes
- Fixed website changes …
=> [plugin.video.watchbox] 0.4.3

plugin.video.mlslive/addon.xml
* Mark as broken due to service shutdown
=> [plugin.video.mlslive] 1.17.3

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/addon/common/kodi.py, plugin.video.twitch/resources/lib/addon/player.py, plugin.video.twitch/resources/lib/routes.py
[add] refresh item to streams search when there are no results
[upd] close chat on playback stopped [ccope]
[upd] service start parameter to login …
=> [plugin.video.twitch] 2.2.2

plugin.video.multichannel/addon.xml, plugin.video.multichannel/resources/language/resource.language.en_gb/strings.po, plugin.video.multichannel/resources/lib/multichannel.py
=> [plugin.video.multichannel] 1.0.2

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/main.py, plugin.video.rtpplay/resources/lib/channels.py, plugin.video.rtpplay/resources/lib/plugin.py
- Add support for widevine encrypted streams
- HLS streams without depending on the website (hardcoded)
=> [plugin.video.rtpplay] 4.0.0

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/resources/lib/plugin.py
=> [plugin.video.rtpplay] 4.0.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.34

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.26

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/cache_images.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/utils.py, plugin.video.embycon/resources/lib/widgets.py, plugin.video.embycon/resources/settings.xml
=> [plugin.video.embycon] 1.5.21

plugin.audio.mixcloud/README, plugin.audio.mixcloud/addon.xml, plugin.audio.mixcloud/changelog.txt, plugin.audio.mixcloud/default.py, plugin.audio.mixcloud/resources/language/Dutch/strings.po, plugin.audio.mixcloud/resources/language/English/strings.po, plugin.audio.mixcloud/resources/language/French/strings.po
[plugin.audio.mixcloud] 2.4.0
- fixed local resolver
- removed broken resolvers
- added logoff functionality
- modified login procedure
=> [plugin.audio.mixcloud] 2.4.0

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.5

plugin.video.tufftv/addon.xml, plugin.video.tufftv/resources/lib/tufftv.py
=> [plugin.video.tufftv] 1.0.1

plugin.video.btsportvideo/README.md, plugin.video.btsportvideo/addon.py, plugin.video.btsportvideo/addon.xml, plugin.video.btsportvideo/resources/language/resource.language.en_gb/strings.po, plugin.video.btsportvideo/resources/lib/api.py, plugin.video.btsportvideo/resources/settings.xml
=> [plugin.video.btsportvideo] 0.3.0

plugin.video.npr/README.txt, plugin.video.npr/addon.xml, plugin.video.npr/changelog.txt, plugin.video.npr/resources/lib/scraper.py
=> [plugin.video.npr] 3.0.4

plugin.video.tvokids/README.txt, plugin.video.tvokids/addon.xml, plugin.video.tvokids/changelog.txt, plugin.video.tvokids/resources/lib/scraper.py
=> [plugin.video.tvokids] 3.0.3

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py
[fix] incorrectly raised 'Proxy is not running' error …
=> [plugin.video.youtube] v6.0.2

plugin.video.btsportvideo/addon.py, plugin.video.btsportvideo/addon.xml
Fixes live channels for Kodi 18 …
=> [plugin.video.btsportvideo] 0.3.1

plugin.video.tufftv/addon.xml, plugin.video.tufftv/resources/lib/tufftv.py
=> [plugin.video.tufftv] 1.0.2

plugin.audio.mixcloud/README, plugin.audio.mixcloud/addon.xml, plugin.audio.mixcloud/changelog.txt, plugin.audio.mixcloud/default.py
2.4.1
- fixed offliberty resolver
- fixed mixcloud-downloader resolver
=> [plugin.audio.mixcloud] 2.4.1

plugin.video.cheddar/addon.xml, plugin.video.cheddar/resources/language/resource.language.en_gb/strings.po
=> [plugin.video.cheddar] 1.0.5

plugin.video.mlslive/addon.xml
=> [plugin.video.mlslive] Broken

plugin.video.srfplaytv/addon.xml, plugin.video.srfplaytv/resources/language/resource.language.de_de/strings.po, plugin.video.srfplaytv/resources/language/resource.language.en_gb/strings.po, plugin.video.srfplaytv/resources/lib/srfplaytv.py
Bug fix release:
- Translate untracked strings.
- Only list live streams, if a video is available.
- Ignore video ids, which do not support the new SRF API. …
=> [plugin.video.srfplaytv] v1.0.1

plugin.video.wakanim/addon.xml, plugin.video.wakanim/changelog.txt, plugin.video.wakanim/resources/language/resource.language.de_de/strings.po, plugin.video.wakanim/resources/language/resource.language.en_gb/strings.po, plugin.video.wakanim/resources/lib/api.py
Changes:
- Added 2FA verification. Wakanim enforce this for untrusted devices/browser. …
=> [plugin.video.wakanim] 0.7.3

plugin.video.arteplussept/CHANGELOG.md, plugin.video.arteplussept/addon.xml, plugin.video.arteplussept/changelog.txt, plugin.video.arteplussept/resources/lib/api.py, plugin.video.arteplussept/resources/lib/mapper.py, plugin.video.arteplussept/resources/lib/utils.py, plugin.video.arteplussept/resources/lib/view.py
Fix bug making the plugin unusable (dumb string encoding bug 😥)
Some cleanup and display improvement as well
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You …
=> [plugin.video.arteplussept] 1.0.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.27

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.35

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py
=> [plugin.video.thinktv] 3.0.14

plugin.video.videomediaset/addon.xml, plugin.video.videomediaset/changelog.txt, plugin.video.videomediaset/resources/lib/mediaset.py
=> [plugin.video.videomediaset] 1.3.2

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/default.py, plugin.video.orftvthek/resources/language/English/strings.po, plugin.video.orftvthek/resources/language/German/strings.po, plugin.video.orftvthek/resources/lib/base.py, plugin.video.orftvthek/resources/lib/htmlscraper.py, plugin.video.orftvthek/resources/lib/serviceapi.py, plugin.video.orftvthek/resources/settings.xml
added UHD livestream option, added Adaptive quality settings, fixed "play all" item (issue #66) …
=> [plugin.video.orftvthek] 0.8.5

plugin.video.mediacorp/README.txt, plugin.video.mediacorp/addon.xml, plugin.video.mediacorp/changelog.txt, plugin.video.mediacorp/resources/lib/scraper.py
=> [plugin.video.mediacorp] 3.0.8

plugin.video.pbskids/README.txt, plugin.video.pbskids/addon.xml, plugin.video.pbskids/changelog.txt, plugin.video.pbskids/resources/lib/scraper.py
=> [plugin.video.pbskids] 3.0.5

plugin.video.rt/README.txt, plugin.video.rt/addon.xml, plugin.video.rt/changelog.txt, plugin.video.rt/resources/lib/scraper.py
Add playback of YouTube videos and ORA videos …
=> [plugin.video.rt] 3.0.4

plugin.video.npr/README.txt, plugin.video.npr/addon.xml, plugin.video.npr/changelog.txt, plugin.video.npr/resources/lib/scraper.py
=> [plugin.video.npr] 3.0.5

plugin.video.teleup/addon.xml, plugin.video.teleup/default.py, plugin.video.teleup/resources/language/resource.language.en_gb/strings.po, plugin.video.teleup/resources/lib/teleup.py
=> [plugin.video.teleup] 2018.06.23

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/default.py, plugin.video.ustvnow/resources/language/resource.language.en_gb/strings.po, plugin.video.ustvnow/resources/lib/ustvnow.py
=> [plugin.video.ustvnow] 2018.06.23

plugin.video.rsich/addon.xml, plugin.video.rsich/changelog.txt, plugin.video.rsich/default.py, plugin.video.rsich/resources/language/resource.language.en_gb/strings.po, plugin.video.rsich/resources/language/resource.language.it_it/strings.po
A small fix plus a new feature …
=> [plugin.video.rsich] v1.1.0

plugin.video.tvvn/addon.xml, plugin.video.tvvn/changelog.txt, plugin.video.tvvn/data.json, plugin.video.tvvn/resources/language/resource.language.en_gb/strings.po, plugin.video.tvvn/tvvn.py
v0.9.12: New provider & links updated
=> [plugin.video.tvvn] 0.9.12

plugin.video.wired/addon.xml, plugin.video.wired/resources/lib/wired.py
sorry for repeat PR, fixed minor url encoding issue. …
=> [plugin.video.wired] 1.0.1

plugin.video.rt/README.txt, plugin.video.rt/addon.xml, plugin.video.rt/changelog.txt, plugin.video.rt/resources/lib/scraper.py
=> [plugin.video.rt] 3.0.5

plugin.video.zattoobox/LICENSE.txt, plugin.video.zattoobox/addon.xml, plugin.video.zattoobox/changelog.txt, plugin.video.zattoobox/resources/lib/core/zapisession.py, plugin.video.zattoobox/resources/lib/core/zbplayableitem.py, plugin.video.zattoobox/resources/lib/extensions/livetv.py
- Replaced deprecated authentication procedure
- Added episode title to main title
- [ X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ X ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0
- Kodi …
=> [plugin.video.zattoobox] 1.0.2

plugin.video.eurosportplayer/addon.py, plugin.video.eurosportplayer/addon.xml, plugin.video.eurosportplayer/resources/lib/hits.py, plugin.video.eurosportplayer/resources/lib/items.py, plugin.video.eurosportplayer/resources/lib/parser.py
- enabled reusepython
- fixed playback
- use episode name for plot if avail (fixes missing description) …
=> [plugin.video.eurosportplayer] 2.1.0

plugin.video.zattoobox/addon.xml, plugin.video.zattoobox/changelog.txt, plugin.video.zattoobox/plugin.py, plugin.video.zattoobox/resources/lib/core/zapisession.py, plugin.video.zattoobox/resources/lib/core/zbplayableitem.py
- Fixed broken authentication URLs
- Force cache refresh after upgrade
- [ X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ X ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) …
=> [plugin.video.zattoobox] 1.0.3

plugin.video.newson/addon.xml, plugin.video.newson/default.py, plugin.video.newson/resources/lib/newson.py
=> [plugin.video.newson] 1.0.6

plugin.video.screenrant/addon.xml, plugin.video.screenrant/default.py, plugin.video.screenrant/resources/lib/screenrant.py
=> [plugin.video.screenrant] 1.0.1

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/default.py, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.6

plugin.video.zattoobox/addon.xml, plugin.video.zattoobox/changelog.txt, plugin.video.zattoobox/resources/lib/core/zapisession.py
- [Fix] Force session cache refresh if required
- [ X ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ X ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
- [ X ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the …
=> [plugin.video.zattoobox] 1.0.4

plugin.video.watchbox/addon.xml, plugin.video.watchbox/changelog.txt, plugin.video.watchbox/default.py, plugin.video.watchbox/resources/lib/controller.py, plugin.video.watchbox/resources/lib/model.py
Changes:
- Fix Watchbox changed stream info format
- Added Widevine DRM support
- Small optimations …
=> [plugin.video.watchbox] 0.5.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/language/English/strings.po, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py, plugin.video.iplayerwww/resources/settings.xml
=> [plugin.video.iplayerwww] 3.0.28

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.36

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py
=> [plugin.video.thinktv] 3.0.15

plugin.video.mlbtv/addon.xml, plugin.video.mlbtv/resources/lib/globals.py, plugin.video.mlbtv/resources/lib/mlb.py, plugin.video.mlbtv/resources/settings.xml
- Added Catch Up feature to live games
- Fix Stream order bug
- List game start time instead of Pre-Game …
=> [plugin.video.mlbtv] 2018.7.11

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_radio.py
=> [plugin.video.iplayerwww] 2.5.37

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_radio.py
=> [plugin.video.iplayerwww] 3.0.29

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/__init__.py, plugin.video.mediathek/mediathek/dreisat.py, plugin.video.mediathek/mediathek/factory.py
Reimplement and renable 3SAT
- X[ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
=> [plugin.video.mediathek] 0.8.7

plugin.onedrive/README.md, plugin.onedrive/addon.py, plugin.onedrive/addon.xml, plugin.onedrive/resources/language/resource.language.en_gb/strings.po, plugin.onedrive/resources/lib/provider/onedrive.py, plugin.onedrive/resources/settings.xml, plugin.onedrive/service.py
=> [plugin.onedrive] 2.1.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.38

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.30

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/resources/lib/ustvnow.py
=> [plugin.video.ustvnow] 2018.07.25

plugin.video.mytv_bg/addon.py, plugin.video.mytv_bg/addon.xml
=> [plugin.video.mytv_bg] 2.0.9

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/addon/api.py, plugin.video.twitch/resources/lib/addon/constants.py, plugin.video.twitch/resources/lib/routes.py
[fix] VOD's returning error 404 …
=> [plugin.video.twitch] v2.2.4

plugin.video.tvcatchups/addon.xml, plugin.video.tvcatchups/resources/lib/tvcatchup.py
=> [plugin.video.tvcatchups] 1.0.5

plugin.video.eurosportplayer/addon.xml, plugin.video.eurosportplayer/resources/lib/client.py, plugin.video.eurosportplayer/resources/lib/common.py, plugin.video.eurosportplayer/resources/lib/parser.py
=> [plugin.video.eurosportplayer] 2.1.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.39

plugin.video.dazn/addon.xml, plugin.video.dazn/resources/language/resource.language.de_de/strings.po, plugin.video.dazn/resources/language/resource.language.en_gb/strings.po, plugin.video.dazn/resources/language/resource.language.en_us/strings.po, plugin.video.dazn/resources/language/resource.language.es_es/strings.po, plugin.video.dazn/resources/language/resource.language.fr_ca/strings.po, plugin.video.dazn/resources/language/resource.language.fr_fr/strings.po, plugin.video.dazn/resources/language/resource.language.it_it/strings.po, plugin.video.dazn/resources/lib/client.py, plugin.video.dazn/resources/lib/common.py, plugin.video.dazn/resources/lib/items.py, plugin.video.dazn/resources/lib/playback.py, plugin.video.dazn/resources/lib/simple_requests/api.py, plugin.video.dazn/resources/settings.xml
added compatibility mode setting to ensure proper playback for kodi17+ due to new manifests versions
=> [plugin.video.dazn] 1.2.0

plugin.video.jwtv-unofficial/addon.xml
Cross-reference: https://github.com/xbmc/repo-plugins/issues/1972
=> [plugin.video.jwtv-unofficial] broken

plugin.video.newson/addon.xml, plugin.video.newson/resources/lib/newson.py
=> [plugin.video.newson] 1.0.7

plugin.video.akibapass/addon.xml, plugin.video.akibapass/changelog.txt
Akibapass shut down its streaming service on 2018-07-31, this update will mark the addon as broken. …
=> [plugin.video.akibapass] 0.6.4

plugin.video.kordkutters/addon.xml, plugin.video.kordkutters/changelog.txt
=> [plugin.video.kordkutters] 1.0.9

plugin.video.mediathekview/README.md, plugin.video.mediathekview/addon.py, plugin.video.mediathekview/addon.xml, plugin.video.mediathekview/resources/language/resource.language.de_de/strings.po, plugin.video.mediathekview/resources/language/resource.language.en_gb/strings.po, plugin.video.mediathekview/resources/language/resource.language.it_it/strings.po, plugin.video.mediathekview/resources/lib/downloader.py, plugin.video.mediathekview/resources/lib/filmui.py, plugin.video.mediathekview/resources/lib/kodi/KodiAddon.py, plugin.video.mediathekview/resources/lib/kodi/KodiUI.py, plugin.video.mediathekview/resources/lib/mvupdate.py, plugin.video.mediathekview/resources/lib/mvutils.py, plugin.video.mediathekview/resources/lib/notifier.py, plugin.video.mediathekview/resources/lib/searches.py, plugin.video.mediathekview/resources/lib/settings.py, plugin.video.mediathekview/resources/lib/store.py, plugin.video.mediathekview/resources/lib/storemysql.py, plugin.video.mediathekview/resources/lib/storesqlite.py, plugin.video.mediathekview/resources/lib/updater.py, plugin.video.mediathekview/resources/settings.xml, plugin.video.mediathekview/service.py
- Fixed error that prevented some shows from being downloaded
- Support for old Maria DB / MySQL versions
- Database downloads will be deleted right after processing
- "Play with subtitles" as context menu operation or automatically when configured
- Last searches
- Faster list of live streams
- Possibility to download a show as movie or as series episode (different download location, naming schema and NFO file)
- Fixed a bug that prevented the creation of the SQLite DB on some systems
- More efficient database structure
- New "mvupdate" options --force and --intervall
- More customisation of NFO-Files
- Automatic detection of season and episode
- Improved download settings
- "Update on Start" did not initiate an update on system start if no database was found
- Detailed database …
=> [plugin.video.mediathekview] 0.5.0

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/resources/lib/ipwww_radio.py
=> [plugin.video.iplayerwww] 3.0.32

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_radio.py
=> [plugin.video.iplayerwww] 2.5.40

plugin.video.nos/addon.xml, plugin.video.nos/resources/lib/nos.py
- Update parser to new NOS css classes
- Drop support for Sportjournaal due to DRM …
=> [plugin.video.nos] 4.0.1

plugin.video.nfl.gamepass/README.md, plugin.video.nfl.gamepass/addon.xml, plugin.video.nfl.gamepass/changelog.txt, plugin.video.nfl.gamepass/default.py, plugin.video.nfl.gamepass/resources/lib/pigskin.py, plugin.video.nfl.gamepass/resources/skins/Default/colors/defaults.xml
=> [plugin.video.nfl.gamepass] 2018.08.15

plugin.video.s04tv/README.md, plugin.video.s04tv/addon.xml, plugin.video.s04tv/changelog.txt, plugin.video.s04tv/default.py, plugin.video.s04tv/resources/language/English/strings.xml, plugin.video.s04tv/resources/language/German/strings.xml, plugin.video.s04tv/resources/settings.xml
- update due to website changes
- …
=> [plugin.video.s04tv] 3.1.6

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/resources/lib/ustvnow.py
=> [plugin.video.ustvnow] 2018.08.15

plugin.video.eurosportplayer/addon.py, plugin.video.eurosportplayer/addon.xml, plugin.video.eurosportplayer/resources/lib/client.py, plugin.video.eurosportplayer/resources/lib/common.py
=> [plugin.video.eurosportplayer] 2.2.0

plugin.video.s04tv/addon.xml
=> [plugin.video.s04tv] 3.1.7

plugin.video.espn-player/LICENSE.txt, plugin.video.espn-player/README.md, plugin.video.espn-player/__init__.py, plugin.video.espn-player/addon.xml, plugin.video.espn-player/changelog.txt, plugin.video.espn-player/default.py, plugin.video.espn-player/resources/__init__.py, plugin.video.espn-player/resources/language/English/strings.po, plugin.video.espn-player/resources/lib/__init__.py, plugin.video.espn-player/resources/lib/espnlib.py, plugin.video.espn-player/resources/settings.xml
Watch content from ESPN Player's NCAA College Pass, Indycar Series, and ESPN Select.
This is an update that fixes the plugin for changes made to site
=> [plugin.video.espn-player] 1.0.5

plugin.googledrive/README.md, plugin.googledrive/addon.py, plugin.googledrive/addon.xml, plugin.googledrive/resources/language/resource.language.en_gb/strings.po, plugin.googledrive/resources/lib/provider/googledrive.py, plugin.googledrive/service.py
- Auto export and watch folder …
=> [plugin.googledrive] 1.2.3

plugin.onedrive/addon.py, plugin.onedrive/addon.xml, plugin.onedrive/resources/lib/provider/onedrive.py, plugin.onedrive/service.py
- Auto export and watch folder …
=> [plugin.onedrive] 2.1.2

plugin.video.foodnetwork.canada/README.txt, plugin.video.foodnetwork.canada/addon.xml, plugin.video.foodnetwork.canada/changelog.txt, plugin.video.foodnetwork.canada/resources/lib/scraper.py
=> [plugin.video.foodnetwork.canada] 3.0.4

plugin.video.thinktv/README.txt, plugin.video.thinktv/addon.xml, plugin.video.thinktv/changelog.txt, plugin.video.thinktv/resources/lib/scraper.py
=> [plugin.video.thinktv] 3.0.16

plugin.video.locast/addon.xml, plugin.video.locast/resources/lib/locast.py
=> [plugin.video.locast] v.1.0.1

plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Fixed some bugs where items would not be shown and where items would not be able to play. Also updated Requests and Beautifulsoup4 module. …
=> [plugin.video.vrt.nu] V1.3.3

plugin.video.mlbtv/addon.xml, plugin.video.mlbtv/resources/language/resource.language.en_gb/strings.po, plugin.video.mlbtv/resources/lib/globals.py, plugin.video.mlbtv/resources/lib/mlb.py, plugin.video.mlbtv/resources/settings.xml
- Add ability to toggle catch up mode …
=> [plugin.video.mlbtv] 2018.8.16

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt, plugin.video.ign_com/default.py
2.3.7 (2018-09-08)
- website switched to https …
=> [plugin.video.ign_com] 2.3.7

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py
Fix for some videos failing (ie. music videos) …
=> [plugin.video.youtube] v6.1.4

plugin.video.youtube/addon.xml
Many videos are broken as of ~2 days ago. 
Marking broken, Please upgrade to a newer Kodi version to continue using this add-on …
=> [plugin.video.youtube] v5.4.9-broken

plugin.video.eurosportplayer/addon.xml, plugin.video.eurosportplayer/resources/lib/client.py, plugin.video.eurosportplayer/resources/lib/common.py, plugin.video.eurosportplayer/resources/lib/hits.py
Fixes login error with bad credentials and adds re-login with bad auth
=> [plugin.video.eurosportplayer] 2.2.1

plugin.video.dazn/addon.xml
Marked as broken as its not compatible with krypton anymore.
New version for leia will be pushed later on.
=> [plugin.video.dazn] 1.2.1-broken

plugin.googledrive/README.md, plugin.googledrive/addon.py, plugin.googledrive/addon.xml, plugin.googledrive/resources/lib/provider/googledrive.py, plugin.googledrive/service.py
- Subtitles assigned in source mode
- Fixes …
=> [plugin.googledrive] 1.2.8

plugin.onedrive/addon.xml, plugin.onedrive/resources/lib/provider/onedrive.py, plugin.onedrive/service.py
- Subtitles assigned in source mode
- Fixes …
=> [plugin.onedrive] 2.1.4

plugin.video.zdf_de_2016/addon.xml, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/TeaserLazyload.py
1.0.12 (2018-09-19)
- fix lazy teaser loading after zdf website updates
- fix loading zdf homepage …
=> [plugin.video.zdf_de_2016] 1.0.12

plugin.video.sarpur/addon.xml, plugin.video.sarpur/changelog.txt, plugin.video.sarpur/resources/language/English/strings.po, plugin.video.sarpur/resources/language/Icelandic/strings.po, plugin.video.sarpur/sarpur/__init__.py, plugin.video.sarpur/sarpur/actions.py, plugin.video.sarpur/sarpur/api.py, plugin.video.sarpur/sarpur/logger.py, plugin.video.sarpur/sarpur/scraper.py, plugin.video.sarpur/util/__init__.py, plugin.video.sarpur/util/gui.py
Localization
Add featured and categories. Add context menu …
=> [plugin.video.sarpur] v4.3.0

plugin.video.vrt.nu/addon.py, plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py, plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py, plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py, plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Changed addon to be able to scrape the new vrtnu layout (this broke 90% off the links since today). While at it i also chose to consistenly put strings with single quotes instead of using sometimes single and sometimes double quotes. Thx for merging!
- This add-on repository has automated code guideline check which could …
=> [plugin.video.vrt.nu] V1.4.1

plugin.video.wakanim/addon.xml, plugin.video.wakanim/changelog.txt, plugin.video.wakanim/resources/lib/api.py, plugin.video.wakanim/resources/lib/controller.py
=> [plugin.video.wakanim] 0.7.5

plugin.video.smithsonian/README.txt, plugin.video.smithsonian/addon.xml, plugin.video.smithsonian/changelog.txt, plugin.video.smithsonian/resources/lib/scraper.py
=> [plugin.video.smithsonian] 3.0.3

plugin.video.ustvnow/addon.xml, plugin.video.ustvnow/resources/lib/ustvnow.py
=> [plugin.video.ustvnow] v.2018.09.27

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_radio.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.33

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/default.py, plugin.video.iplayerwww/resources/lib/ipwww_radio.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.41

plugin.video.abcfamily/addon.xml, plugin.video.abcfamily/changelog.txt, plugin.video.abcfamily/readme.txt, plugin.video.abcfamily/resources/lib/scraper.py
=> [plugin.video.abcfamily] 3.0.7

plugin.video.wabc/addon.xml, plugin.video.wabc/changelog.txt, plugin.video.wabc/readme.txt, plugin.video.wabc/resources/lib/scraper.py
=> [plugin.video.wabc] 3.0.11

plugin.video.tvcatchups/addon.xml, plugin.video.tvcatchups/resources/language/resource.language.en_gb/strings.po, plugin.video.tvcatchups/resources/lib/tvcatchup.py
=> [plugin.video.tvcatchups] 1.0.6

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/resources/lib/channels.py, plugin.video.rtpplay/resources/lib/plugin.py
Fix live streams and widevine token determination. …
=> [plugin.video.rtpplay] 4.0.3

plugin.video.itsapixelthing/addon.xml, plugin.video.itsapixelthing/changelog.txt, plugin.video.itsapixelthing/main.py, plugin.video.itsapixelthing/resources/language/resource.language.en_gb/strings.po, plugin.video.itsapixelthing/resources/language/resource.language.pt_pt/strings.po, plugin.video.itsapixelthing/resources/lib/addonutils.py, plugin.video.itsapixelthing/resources/lib/kodiutils.py, plugin.video.itsapixelthing/resources/lib/plugin.py, plugin.video.itsapixelthing/resources/lib/youtubelib.py
Add live streams, fix issue on first installation if the youtube addon is not installed …
=> [plugin.video.itsapixelthing] 1.0.1

plugin.video.rtsplaytv/addon.xml, plugin.video.rtsplaytv/resources/lib/rtsplaytv.py
Updated plugin.video.rtsplaytv to version 0.9.3.
This contains a critical bug fix: Failing to parse the date would let the plugin crash. This should not happen anymore. Furthermore, the forum thread was added to `addon.xml`. …
=> [plugin.video.rtsplaytv] 0.9.3

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/main.py, plugin.video.tyt/resources/lib/modules/logon.py, plugin.video.tyt/resources/lib/modules/scrape.py
Fixed issue when server is missing images
=> [plugin.video.tyt] 3.0.1

plugin.video.psvue/addon.xml, plugin.video.psvue/main.py, plugin.video.psvue/resources/language/resource.language.en_gb/strings.po, plugin.video.psvue/resources/language/resource.language.he_il/strings.po, plugin.video.psvue/resources/lib/ps_vue.py, plugin.video.psvue/resources/lib/sony.py, plugin.video.psvue/resources/settings.xml
Updates / Fixes
- Export to Library Feature Added (Thanks snoopyjoe)
- Rename My Shows to My DVR
- Added Movies section
- Fix for some channels not working with inputstream adaptive
- Add EPG reset mode, which is callable from PS EPG Service
- Only set resume time, when necessary
- Add next and previous page to Movies section
- Add ability to change movie genre
- Reworked badges for show/episode listings (thanks hackthis02)
- …
=> [plugin.video.psvue] 2018.10.9

travis-buddy-success-template.md
Travisbuddy should reply with "tests were successful", not "tests were successfully".
This is not a PR for an addon, so I cannot use the usual commit style message syntax. …
=> [travisbuddy] Fix typo in success template

plugin.video.simpsonsworld/addon.xml, plugin.video.simpsonsworld/resources/lib/globals.py, plugin.video.simpsonsworld/simpsons.py
- Fix for updated adobepass
- Add Season 30
- PEP 8 Code Styling …
=> [plugin.video.simpsonsworld] 2018.10.10

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py
=> [plugin.video.iplayerwww] 2.5.43

plugin.video.transpondertv/addon.xml, plugin.video.transpondertv/resources/language/resource.language.en_gb/strings.po, plugin.video.transpondertv/resources/lib/transponder.py, plugin.video.transpondertv/resources/settings.xml
=> [plugin.video.transpondertv] 1.0.2

plugin.video.telebasel/addon.xml
There was a big error on my previous submission. I had the wrong BeautifulSoup module as a dependency in my `addon.xml`. This issue is resolved now. …
=> [plugin.video.telebasel] 0.9.1

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py, plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py
[fix] clean_title_value UnicodeDecodeError
[fix] Game titles UnicodeEncodeError
[fix] python 3 compat. urllib.quote_plus …
=> [plugin.video.twitch] v2.3.4

plugin.video.nrk/addon.py, plugin.video.nrk/addon.xml, plugin.video.nrk/changelog.txt, plugin.video.nrk/nrktv.py
=> [plugin.video.nrk] 4.6.1

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.36

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.44

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.37

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.45

plugin.video.wsj/addon.xml
=> [plugin.video.wsj] 1.9.5

plugin.video.myvevo/addon.xml
=> [plugin.video.myvevo] 3.0.14

plugin.video.si/addon.xml
=> [plugin.video.si] 3.0.3

plugin.video.aswim/README.txt, plugin.video.aswim/addon.xml, plugin.video.aswim/resources/lib/scraper.py
=> [plugin.video.aswim] 3.0.3

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_context.py, plugin.video.youtube/resources/lib/youtube_plugin/kodion/json_store/json_store.py, plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/http_server.py, plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/monitor.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py
=> [plugin.video.youtube] v6.2.2

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/addon/common/json_store.py, plugin.video.twitch/resources/lib/twitch_addon/addon/common/storage.py, plugin.video.twitch/resources/lib/twitch_addon/addon/constants.py, plugin.video.twitch/resources/lib/twitch_addon/addon/menu_items.py, plugin.video.twitch/resources/lib/twitch_addon/router.py, plugin.video.twitch/resources/lib/twitch_addon/routes/clear_search_history.py, plugin.video.twitch/resources/lib/twitch_addon/routes/edit_blacklist.py, plugin.video.twitch/resources/lib/twitch_addon/routes/edit_user_follows.py, plugin.video.twitch/resources/lib/twitch_addon/routes/refresh.py, plugin.video.twitch/resources/lib/twitch_addon/routes/remove_search_history.py, plugin.video.twitch/resources/lib/twitch_addon/routes/settings.py
=> [plugin.video.twitch] v2.3.5

plugin.video.rtsplaytv/README.md, plugin.video.rtsplaytv/addon.xml, plugin.video.rtsplaytv/resources/language/resource.language.fr_fr/strings.po, plugin.video.rtsplaytv/resources/lib/rtsplaytv.py
This PR adds a french translation to the plugin `plugin.video.rtsplaytv`. …
=> [plugin.video.rtsplaytv] v1.0.0

plugin.video.frikanalen/addon.py, plugin.video.frikanalen/addon.xml, plugin.video.frikanalen/changelog.txt, plugin.video.frikanalen/frikanalen.py, plugin.video.frikanalen/main.py, plugin.video.frikanalen/resources/language/resource.language.en_gb/strings.po, plugin.video.frikanalen/resources/language/resource.language.nb_no/strings.po
- Added HD stream option.
- Added category listing of published videos.
- Show video duration in schedule and category lists.
- Updated to not crash with new API date format.
- Added free text video search option.
=> [plugin.video.frikanalen] v0.0.3

plugin.video.uzg/addon.py, plugin.video.uzg/addon.xml, plugin.video.uzg/changelog.txt, plugin.video.uzg/resources/language/Dutch/strings.po, plugin.video.uzg/resources/language/Dutch/strings.xml, plugin.video.uzg/resources/language/English/strings.po, plugin.video.uzg/resources/language/English/strings.xml, plugin.video.uzg/resources/language/resource.language.en_gb/strings.po, plugin.video.uzg/resources/language/resource.language.nl_nl/strings.po, plugin.video.uzg/resources/lib/uzg.py
=> [plugin.video.uzg] v1.3.2

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.38

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.46

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.47

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.39

plugin.video.dazn/addon.py, plugin.video.dazn/addon.xml, plugin.video.dazn/resources/language/resource.language.de_de/strings.po, plugin.video.dazn/resources/language/resource.language.en_gb/strings.po, plugin.video.dazn/resources/language/resource.language.en_us/strings.po, plugin.video.dazn/resources/language/resource.language.es_es/strings.po, plugin.video.dazn/resources/language/resource.language.fr_ca/strings.po, plugin.video.dazn/resources/language/resource.language.fr_fr/strings.po, plugin.video.dazn/resources/language/resource.language.it_it/strings.po, plugin.video.dazn/resources/lib/client.py, plugin.video.dazn/resources/lib/common.py, plugin.video.dazn/resources/lib/context.py, plugin.video.dazn/resources/lib/items.py, plugin.video.dazn/resources/lib/parser.py, plugin.video.dazn/resources/lib/playback.py, plugin.video.dazn/resources/lib/simple_requests/api.py, plugin.video.dazn/resources/lib/tiles.py, plugin.video.dazn/resources/settings.xml
- few minor bug fixes
- added logout and max bandwidth setting
=> [plugin.video.dazn] 1.3.1

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/default.py, plugin.video.orftvthek/resources/language/English/strings.po, plugin.video.orftvthek/resources/language/German/strings.po, plugin.video.orftvthek/resources/lib/Settings.py, plugin.video.orftvthek/resources/lib/base.py, plugin.video.orftvthek/resources/lib/htmlscraper.py, plugin.video.orftvthek/resources/lib/serviceapi.py, plugin.video.orftvthek/resources/settings.xml
=> [plugin.video.orftvthek] 0.8.8

plugin.video.wnbc/addon.xml, plugin.video.wnbc/changelog.txt, plugin.video.wnbc/readme.txt, plugin.video.wnbc/resources/lib/scraper.py
=> [plugin.video.wnbc] 3.0.17

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/main.py, plugin.video.tyt/resources/lib/modules/scrape.py
Updated code to prevent crash due to new coding at main site
=> [plugin.video.tyt] 3.0.4

plugin.video.infowars/LICENSE.txt, plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
Version 2.1.1
- Updated All Links
- Removed broken documentary section
- Added On Demand Videos Section
- Added Lastest Full On Demand Episodes Section
- Updated Icons
=> [plugin.video.infowars] 2.1.1

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/main.py, plugin.video.tyt/resources/language/resource.language.en_gb/strings.po, plugin.video.tyt/resources/lib/modules/scrape.py
Last nights update worked on some platforms, while not on others.  Same problems some people have on website.  So I added the option of selecting the stream.
=> [plugin.video.tyt] 3.0.6

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt, plugin.video.ign_com/default.py, plugin.video.ign_com/resources/settings.xml
=> [plugin.video.ign_com] 2.3.8

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.7

plugin.video.vrt.nu/addon.py, plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po, plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py, plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/actions.py, plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py, plugin.video.vrt.nu/resources/settings.xml
Fixed mark as watched bug + enabled drm support + subtitles also work again + removed some spaces in addon.xml . …
=> [plugin.video.vrt.nu] V1.5.0

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/addon/common/kodi.py, plugin.video.twitch/resources/lib/twitch_addon/routes/main.py, plugin.video.twitch/resources/lib/twitch_addon/routes/search_results.py
=> [plugin.video.twitch] v2.4.1

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/lib/channels.py, plugin.video.rtpplay/resources/lib/plugin.py
=> [plugin.video.rtpplay] 4.0.4

README.md
=> [README.md] update banner image (#2017)

plugin.video.uzg/addon.xml, plugin.video.uzg/changelog.txt
=> [plugin.video.uzg] v2.0.1

plugin.video.sarpur/addon.xml, plugin.video.sarpur/changelog.txt, plugin.video.sarpur/sarpur/actions.py, plugin.video.sarpur/util/gui.py
Add subtitles when available to playable list items …
=> [plugin.video.sarpur] 4.4.0

plugin.video.uzg/addon.xml, plugin.video.uzg/changelog.txt
=> [plugin.video.uzg] v1.3.3

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/ard.py, plugin.video.mediathek/mediathek/arte.py, plugin.video.mediathek/mediathek/factory.py
Fixed ARD and enabling it again (get access to ARD, Das Erste, BR, HR, MDR, NDR, Radio Bremen, RBB, SR, SWR, WDR, One and Alpha)
=> [plugin.video.mediathek] 0.8.9

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt, plugin.video.ign_com/default.py
2.3.9 (2019-01-14)
- fix to make the addon work for all countries again
- added series updates category
=> [plugin.video.ign_com] 2.3.9

plugin.video.foodnetwork/addon.xml, plugin.video.foodnetwork/resources/lib/scraper.py
=> [plugin.video.foodnetwork] 3.0.11

plugin.video.crackle/addon.xml, plugin.video.crackle/main.py, plugin.video.crackle/resources/lib/globals.py
=> [plugin.video.crackle] 2018.12.17

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/zdf.py
=> [plugin.video.mediathek] 0.9.0

plugin.video.attactv/addon.xml, plugin.video.attactv/changelog.txt
Hi,
Please, mark this version on Gotham repo as broken.
I'll make another PR with the add-on updated for Isengard onwards.
jamontes.
Changelog: 1.1.14 (2019.01.25)
- Marked as broken for Gotham and Helix versions due to a missing dependency.
- This add-on repository …
=> [plugin.video.attactv] v1.1.14

plugin.video.zdf_de_2016/addon.py, plugin.video.zdf_de_2016/addon.xml, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/RubricResource.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Teaser.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/base/Pagelet.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/AbstractPage.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/player/TokenCache.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/search/SearchHistory.py, plugin.video.zdf_de_2016/resources/settings.xml
1.0.14 (2019-01-29)
- fix for missing play icon …
=> [plugin.video.zdf_de_2016] 1.0.14

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py
=> [plugin.video.iplayerwww] 2.5.48

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py
=> [plugin.video.iplayerwww] 3.0.40

plugin.video.tv3.cat/addon.xml, plugin.video.tv3.cat/changelog.txt, plugin.video.tv3.cat/default.py, plugin.video.tv3.cat/resources/lib/tv3cat.py
=> [plugin.video.tv3.cat] 1.4.0

plugin.video.attactv/addon.xml, plugin.video.attactv/changelog.txt, plugin.video.attactv/default.py
Hi,
This is a maintenance PR over Isengard branch for the ATTAC TV video add-on.
Changelog: 1.2.1 (2019.02.10)
- Quick fix due website changes.
jamontes.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results …
=> [plugin.video.attactv] v1.2.1

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_context.py, plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_playlist.py, plugin.video.youtube/resources/lib/youtube_plugin/kodion/service.py, plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/player.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_playlist.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_subscriptions.py
[add] 4K videos with InputStream Adaptive >= v2.3.14
- Thanks to peak3d
[fix] some videos not playing when logged in
[fix] reset function cache at restart/update to resolve issues persisting due to cached results
[fix] service potentially not shutting down http server
[fix] added to playlist/subscriptions notifications
[fix] only generate mpeg-dash file if adaptive formats are available
[fix] map frame rates to more common representation to lessen the chance of double refresh changes (applies only to generated mpeg-dash files)
[fix] currently playing file check when playing file is a plugin:// url
[chg] Settings - General - Autoplay suggested videos
- limit playlist size to 1000 videos
- request less relevant videos at one time
- old behavior: add 50 most relevant videos for each video …
=> [plugin.video.youtube] v6.4.0

plugin.video.mediathek/addon.xml, plugin.video.mediathek/changelog.txt, plugin.video.mediathek/mediathek/ard.py
=> [plugin.video.mediathek] 0.9.3

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.41

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.49

plugin.video.slingtv/addon.xml, plugin.video.slingtv/resources/lib/login.py
=> [plugin.video.slingtv] 1.0.1

plugin.video.yelo/addon.xml, plugin.video.yelo/resources/lib/helpers/dynamic_headers.py, plugin.video.yelo/resources/lib/yelo/yelo.py
Update to 0.0.3 Fixed entitlement issue when requesting user information.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these …
=> [plugin.video.yelo] v0.0.3

plugin.video.pluralsight/addon.xml, plugin.video.pluralsight/changelog.txt
- [x I have read the [CONTRIBUTING](https://github.com/xbmc/repo-plugins/blob/master/CONTRIBUTING.md) document
This addon is completely broken and basically requires a total rewrite to fix
=> [plugin.video.pluralsight] v1.1.4 (broken)

plugin.video.newson/addon.xml, plugin.video.newson/resources/lib/newson.py
=> [plugin.video.newson] 1.0.8

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/resource.language.en_gb/strings.po, plugin.video.twitch/resources/lib/twitch_addon/addon/common/kodi.py, plugin.video.twitch/resources/lib/twitch_addon/addon/common/log_utils.py, plugin.video.twitch/resources/lib/twitch_addon/service.py
=> [plugin.video.twitch] v2.4.2

plugin.video.telebasel/addon.xml, plugin.video.telebasel/resources/lib/telebasel.py
New minor release of the plugin. It stopped working because of change in the website's HTML. …
=> [plugin.video.telebasel] 0.9.2

plugin.video.cbc/addon.xml
Mark addon as broken for migration to inputstream.adaptive. …
=> [plugin.video.cbc] 4.0.5

plugin.video.dailymotion_com/addon.xml, plugin.video.dailymotion_com/changelog.txt, plugin.video.dailymotion_com/default.py
=> [plugin.video.dailymotion_com] v2.3.8

plugin.video.disclosetv/addon.xml, plugin.video.disclosetv/default.py, plugin.video.disclosetv/resources/language/resource.language.en_gb/strings.po, plugin.video.disclosetv/resources/lib/disclosetv.py
=> [plugin.video.disclosetv] 1.0.8

plugin.video.roosterteeth/addon.xml, plugin.video.roosterteeth/changelog.txt, plugin.video.roosterteeth/resources/language/English/strings.po, plugin.video.roosterteeth/resources/lib/roosterteeth_const.py, plugin.video.roosterteeth/resources/lib/roosterteeth_list_episodes.py, plugin.video.roosterteeth/resources/lib/roosterteeth_list_serie_seasons.py, plugin.video.roosterteeth/resources/lib/roosterteeth_list_series.py, plugin.video.roosterteeth/resources/lib/roosterteeth_main.py, plugin.video.roosterteeth/resources/lib/roosterteeth_play.py
1.3.10 (2019-03-13)
- fixed videos
- removed the know channel
- added inside gaming channel
- added kinda funny channel
- removed youtube dependency
=> [plugin.video.roosterteeth] 1.3.10

plugin.video.tekthing/addon.py, plugin.video.tekthing/addon.xml, plugin.video.tekthing/changelog.txt
v1.0.4 (2019-03-13)
- fixed finding of videos
- removing non-ascii characters in title in parameters to prevent UnicodeDecodeError: 'ascii' codec can't decode ...
The error occured when doing urllib.parse.parse_qs of the parameters
- removed youtube dependency
=> [plugin.video.tekthing] 1.0.4

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.50

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.42

plugin.video.spurs-tv/addon.xml, plugin.video.spurs-tv/resources/lib/api.py
Fixes the latest videos listing. …
=> [plugin.video.spurs-tv] v2.15.4

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.51

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.43

plugin.video.watchbox/addon.xml, plugin.video.watchbox/changelog.txt, plugin.video.watchbox/resources/lib/controller.py
Watchbox is now part of the streaming service TVNow and therefore no longer available.
This update will mark the addon as broken. …
=> [plugin.video.watchbox] v0.5.2

plugin.video.rsiplaytv/addon.xml, plugin.video.rsiplaytv/resources/settings.xml
Quick bug fix: Take the correct plugin to choose the user's favourite shows. …
=> [plugin.video.rsiplaytv] v1.5.1

plugin.video.zattoobox/LICENSE.txt, plugin.video.zattoobox/addon.xml, plugin.video.zattoobox/changelog.txt, plugin.video.zattoobox/plugin.py, plugin.video.zattoobox/resources/lib/core/zbplayableitem.py
=> [plugin.video.zattoobox] 1.0.5

plugin.video.tyt/addon.xml, plugin.video.tyt/changelog.txt, plugin.video.tyt/resources/lib/modules/scrape.py
Updated to work with the new changes to site.
=> [plugin.video.tyt] 3.1.0

plugin.video.tvcatchups/addon.xml
=> [plugin.video.tvcatchups] 1.0.8

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt, plugin.video.ign_com/default.py, plugin.video.ign_com/resources/language/English/strings.po, plugin.video.ign_com/resources/language/German/strings.po
2.3.10 (2019-04-07)
- added 'Game Reviews' category. This was needed because not all game reviews show up the 'Reviews' category
- fixed displaying the video in the correct resolution
- removed testing on presence of the videos. This should speed up the addon a bit.
=> [plugin.video.ign_com] 2.3.10

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/addon/api.py, plugin.video.twitch/resources/lib/twitch_addon/addon/google_firebase.py, plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py, plugin.video.twitch/resources/lib/twitch_addon/routes/token_url.py, plugin.video.twitch/resources/lib/twitch_addon/service.py
Requires https://github.com/xbmc/repo-scripts/pull/1031 …
=> [plugin.video.twitch] v2.4.3

plugin.video.dazn/README.md, plugin.video.dazn/addon.py, plugin.video.dazn/addon.xml, plugin.video.dazn/resources/lib/client.py, plugin.video.dazn/resources/lib/common.py, plugin.video.dazn/resources/lib/items.py, plugin.video.dazn/resources/lib/rails.py, plugin.video.dazn/resources/lib/tiles.py
added youth protection pin (mainly for german users)
=> [plugin.video.dazn] 1.3.2

plugin.video.mlbtv/addon.xml, plugin.video.mlbtv/resources/lib/account.py, plugin.video.mlbtv/resources/lib/mlb.py, plugin.video.mlbtv/resources/settings.xml
=> [plugin.video.mlbtv] 2019.3.31

plugin.video.xumotv/addon.xml, plugin.video.xumotv/resources/lib/xumotv.py
=> [plugin.video.xumotv] 1.0.1

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/lib/downloadutils.py
=> [plugin.video.embycon] 1.9.4

plugin.audio.rne/addon.xml, plugin.audio.rne/changelog.txt, plugin.audio.rne/default.py, plugin.audio.rne/resources/lib/rne_api.py, plugin.audio.rne/resources/tests/test_api.py
Hi,
This is a maintenance PR for the RNE add-on:
Changelog: 1.0.12 (2019.05.02)
- Quick fix for direct channels due to website changes (full credits and great thanks to vicglez).
jamontes. …
=> [plugin.audio.rne] v1.0.12

plugin.video.wakanim/addon.xml, plugin.video.wakanim/changelog.txt, plugin.video.wakanim/resources/language/resource.language.fr_fr/strings.po, plugin.video.wakanim/resources/lib/api.py, plugin.video.wakanim/resources/lib/controller.py, plugin.video.wakanim/resources/lib/streamparams.py, plugin.video.wakanim/resources/lib/wakanim.py
Changes:
- Fix login not working
- Small fixes …
=> [plugin.video.wakanim] v0.7.6

plugin.video.mazacka/addon.xml, plugin.video.mazacka/main.py, plugin.video.mazacka/resources/language/resource.language.cs_cz/strings.po, plugin.video.mazacka/resources/language/resource.language.en_gb/strings.po
=> [plugin.video.mazacka] 1.1.0

plugin.video.fosdem/addon.py, plugin.video.fosdem/addon.xml, plugin.video.fosdem/resources/settings.xml
=> [plugin.video.fosdem] 0.0.3

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
Version 2.1.2
- Updated On Demand links
- Updated Recent Full Show links
- Updated Live Events Links
- Removed Counter Think
- Added Kaitlin Bennett Liberty Hangout Youtube Channel
=> [plugin.video.infowars] 2.1.2

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/language/English/strings.po, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.52

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/language/resource.language.en_gb/strings.po, plugin.video.iplayerwww/resources/lib/ipwww_common.py, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.44

plugin.video.bcf/.gitignore, plugin.video.bcf/README.md, plugin.video.bcf/addon.xml, plugin.video.bcf/changelog.txt, plugin.video.bcf/resources/language/resource.language.en_gb/strings.po, plugin.video.bcf/resources/lib/kodiutils.py, plugin.video.bcf/resources/lib/plugin.py, plugin.video.bcf/resources/lib/search.py
Fixes unplayable news items - plus housekeeping
=> [plugin.video.bcf] 1.0.2

PULL_REQUEST_TEMPLATE.md
This information can help new developers to get attention if a PR is not reviewed.
See https://forum.kodi.tv/showthread.php?tid=206635&pid=2858149#pid2858149 for more information.
=> Add info about Kodi IRC

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/addon/player.py, plugin.video.twitch/resources/lib/twitch_addon/routes/token_url.py, plugin.video.twitch/resources/lib/twitch_addon/service.py
Fix unable to clean up class left in memory; N9XBMCAddon7xbmcgui6WindowE …
=> [plugin.video.twitch] v2.4.4

plugin.video.telebasel/addon.xml, plugin.video.telebasel/resources/lib/telebasel.py
The website https://telebasel.ch got a slight redesign and broke the plugin. This PR makes the plugin work again. …
=> [plugin.video.telebasel] 0.9.3

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 2.5.53

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.45

plugin.video.eye/README.md, plugin.video.eye/addon.xml, plugin.video.eye/changelog.txt, plugin.video.eye/resources/lib/plugin.py
Just updated to use the fixed version of script.module.cache (currently in PR)
=> [plugin.video.eye] 1.0.1

plugin.video.vrt.nu/README.md, plugin.video.vrt.nu/addon.py, plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po, plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po, plugin.video.vrt.nu/resources/lib/__init__.py, plugin.video.vrt.nu/resources/lib/favorites.py, plugin.video.vrt.nu/resources/lib/helperobjects.py, plugin.video.vrt.nu/resources/lib/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/metadatacreator.py, plugin.video.vrt.nu/resources/lib/search.py, plugin.video.vrt.nu/resources/lib/statichelper.py, plugin.video.vrt.nu/resources/lib/streamservice.py, plugin.video.vrt.nu/resources/lib/tokenresolver.py, plugin.video.vrt.nu/resources/lib/tvguide.py, plugin.video.vrt.nu/resources/lib/vrtapihelper.py, plugin.video.vrt.nu/resources/lib/vrtplayer.py, plugin.video.vrt.nu/resources/settings.xml
- A small bugfix wrt. roaming tokens
- Now includes YouTube support and one missing radio channel
- A new API call to start a program based on start-time
=> [plugin.video.vrt.nu] 2.1.0

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/language/resource.language.it_it/strings.po, plugin.video.embycon/resources/lib/action_menu.py, plugin.video.embycon/resources/lib/cache_images.py, plugin.video.embycon/resources/lib/datamanager.py, plugin.video.embycon/resources/lib/downloadutils.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/item_functions.py, plugin.video.embycon/resources/lib/library_change_monitor.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/server_detect.py, plugin.video.embycon/resources/lib/websocket.py, plugin.video.embycon/resources/lib/websocket_client.py, plugin.video.embycon/resources/lib/widgets.py, plugin.video.embycon/resources/settings.xml, plugin.video.embycon/resources/skins/default/720p/ActionMenu.xml, plugin.video.embycon/resources/skins/skin.estuary/18/xml/DialogVideoInfo.xml, plugin.video.embycon/service.py
Fixes for the latest changes in the Emby Server
Some small fixes and changes to the usability …
=> [plugin.video.embycon] 1.9.18

plugin.video.newson/addon.xml, plugin.video.newson/resources/lib/newson.py, plugin.video.newson/resources/settings.xml
=> [plugin.video.newson] 1.1.1

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/datamanager.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/utils.py, plugin.video.embycon/resources/settings.xml, plugin.video.embycon/service.py
Fixes for the upcoming Emby Server 4.2 release:
-fix the auto resume on playback code
-fix the search, use new search api
-fix an issue with clearing cached data on startup
-allow overriding some video codecs to force transcode …
=> [plugin.video.embycon] 1.9.25

plugin.video.sportschau/addon.xml
Closes https://github.com/xbmc/repo-plugins/issues/2433
=> [plugin.video.sportschau] broken

plugin.video.hdhomerun.simple/addon.xml, plugin.video.hdhomerun.simple/default.py, plugin.video.hdhomerun.simple/resources/language/resource.language.en_gb/strings.po, plugin.video.hdhomerun.simple/resources/lib/hdhomerun.py
Dependent on module uEPG v.1.0.6
Dependent on module pyHDHR v.1.0.7 …
=> [plugin.video.hdhomerun.simple] 1.0.4

plugin.audio.booksshouldbefree/addon.xml
Requested by @KarellenX in https://github.com/xbmc/repo-plugins/issues/2355
=> [plugin.audio.booksshouldbefree] broken

plugin.video.previewnetworks/addon.xml
Requested by @KarellenX in https://github.com/xbmc/repo-plugins/issues/2409
=> [plugin.video.previewnetworks] broken

plugin.audio.dradio/addon.xml
Requested in https://github.com/xbmc/repo-plugins/issues/2398
=> [plugin.audio.dradio] 1.3.2

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
Version 2.1.3
- Fixed On Demand Section …
=> [plugin.video.infowars] 2.1.3

plugin.video.catchuptvandmore/addon.py, plugin.video.catchuptvandmore/addon.xml, plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py, plugin.video.catchuptvandmore/resources/lib/channels/fr/idf1.py, plugin.video.catchuptvandmore/resources/lib/channels/tv_guides/be_live.py, plugin.video.catchuptvandmore/resources/lib/channels/wo/arte.py, plugin.video.catchuptvandmore/resources/lib/labels.py, plugin.video.catchuptvandmore/resources/lib/skeletons/fr_live.py, plugin.video.catchuptvandmore/resources/m3u/live_tv_all.m3u, plugin.video.catchuptvandmore/resources/m3u/live_tv_fr.m3u, plugin.video.catchuptvandmore/resources/settings.xml
[Version 0.2.10]
[Fix] Catch-up TV - France TV (FR) - Case Fort Boyard
[Add] Live TV - IDF 1 (FR)
[Improvements] Use external tzlocal module
[Fix] Catch-up TV - Arte (WO) - Fix Description
[Fix] Guide TV (BE) - Need to rework the guide TV
- This add-on repository has automated code guideline check which could help you …
=> [plugin.video.catchuptvandmore] 0.2.10

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/channelpack.json, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.de/channelpack.json, plugin.video.retrospect/channels/channel.mtg/channelpack.json, plugin.video.retrospect/channels/channel.mtv/channelpack.json, plugin.video.retrospect/channels/channel.nick/channelpack.json, plugin.video.retrospect/channels/channel.no/channelpack.json, plugin.video.retrospect/channels/channel.nos/channelpack.json, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/channels/channel.regionalnl/channelpack.json, plugin.video.retrospect/channels/channel.rtlnl/channelpack.json, plugin.video.retrospect/channels/channel.rtlnl/rtl/chn_rtl.json, plugin.video.retrospect/channels/channel.rtlnl/rtl/chn_rtl.py, plugin.video.retrospect/channels/channel.sbsnl/channelpack.json, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.streams/channelpack.json, plugin.video.retrospect/channels/channel.uk/channelpack.json, plugin.video.retrospect/channels/channel.videos/channelpack.json, plugin.video.retrospect/resources/language/resource.language.en_gb/strings.po, plugin.video.retrospect/resources/language/resource.language.nl_nl/strings.po, plugin.video.retrospect/resources/language/resource.language.sv_se/strings.po, plugin.video.retrospect/resources/libs/chn_class.py, plugin.video.retrospect/resources/libs/helpers/channelimporter.py, plugin.video.retrospect/resources/libs/helpers/languagehelper.py, plugin.video.retrospect/resources/libs/plugin.py, plugin.video.retrospect/resources/libs/retroconfig.py, plugin.video.retrospect/resources/libs/streams/mpd.py, plugin.video.retrospect/resources/libs/version.py
A small update to fix some stuff:
- Fixed: some versioning stuff for channels and fixed the naming problem of revision and build, which were reversed.
- Fixed: video items always showed channel settings in context menu even if a channel has no settings
- Added: Breadcrumbs for current listing
- Language corrections and additions for Swedish language
- Fixed: show some more information when logging on to a channel fails
- Added: if no username was configured, log this as a warning
- Added: allow playback of NPO Plus content if you are logged in with an NPO Plus account
- Added: option to configure the use of the InputStream Adaptive add-on for RTL XL
- Bumped the version of the script.module.inputstreamhelper to 0.3.5 to solve the Widevine issue
- Added: Install Widevine using the …
=> [plugin.video.retrospect] v5.0.1

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/resources/libs/vault.py
I introduced a stupid bug that causes users to get an OK dialog each time they try to play an NPO Start item without an account configured (that should be possible). That is rather annoying. And I fixed a small encoding/decoding bug that I found with Kodi Matrix (Python 3)
- This add-on repository has automated code …
=> [plugin.video.retrospect] v5.0.2

plugin.audio.resetradio/addon.xml
=> [plugin.audio.resetradio] 1.0.3 (broken)

plugin.video.dplay/addon.xml
=> [plugin.video.dplay] 1.0.5 (broken)

plugin.video.rtpplay/addon.xml, plugin.video.rtpplay/changelog.txt, plugin.video.rtpplay/resources/lib/channels.py, plugin.video.rtpplay/resources/lib/kodilogging.py, plugin.video.rtpplay/resources/lib/kodiutils.py, plugin.video.rtpplay/resources/lib/plugin.py
- Fix thumbnails and EPG
- Python3 compatibility for Matrix
- Bump inputstreamhelper
=> [plugin.video.rtpplay] 5.0.0

plugin.image.bancasapo/addon.xml, plugin.image.bancasapo/main.py, plugin.image.bancasapo/resources/language/resource.language.en_gb/strings.po, plugin.image.bancasapo/resources/language/resource.language.pt_pt/strings.po, plugin.image.bancasapo/resources/lib/kodilogging.py, plugin.image.bancasapo/resources/lib/kodiutils.py, plugin.image.bancasapo/resources/lib/plugin.py
- Minor fixes
- Python3 support
=> [plugin.image.bancasapo] 3.0.0

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py
=> [plugin.video.iplayerwww] 2.5.54

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_common.py
=> [plugin.video.iplayerwww] 3.0.46

plugin.video.vimeo/addon.xml
Mark Vimeo plugin as deprecated as requested in https://github.com/xbmc/repo-plugins/pull/2504#issuecomment-525395220.
Depends on https://github.com/xbmc/repo-plugins/pull/2504.
=> [plugin.video.vimeo] 4.1.5 (broken)

plugin.video.fosdem/addon.py, plugin.video.fosdem/addon.xml, plugin.video.fosdem/resources/lib/fosdem.py
=> [plugin.video.fosdem] 0.0.5

plugin.video.vrt.nu/README.md, plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po, plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po, plugin.video.vrt.nu/resources/lib/addon.py, plugin.video.vrt.nu/resources/lib/metadata.py, plugin.video.vrt.nu/resources/lib/vrtplayer.py
- "Go to program" will now got to "All seasons" listing
- Rename "My programs" to "My favorites"
=> [plugin.video.vrt.nu] 2.2.2

plugin.video.embycon/addon.xml, plugin.video.embycon/resources/language/resource.language.en_gb/strings.po, plugin.video.embycon/resources/lib/cache_images.py, plugin.video.embycon/resources/lib/context_monitor.py, plugin.video.embycon/resources/lib/downloadutils.py, plugin.video.embycon/resources/lib/functions.py, plugin.video.embycon/resources/lib/item_functions.py, plugin.video.embycon/resources/lib/play_utils.py, plugin.video.embycon/resources/lib/websocket_client.py
September release.
Small bug fixes and enhancements. …
=> [plugin.video.embycon] 1.9.32

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/channelpack.json, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.be/vtmbe/chn_vtmbe.py, plugin.video.retrospect/channels/channel.mtg/viafree/chn_viafree.json, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/oppetarkiv/chn_oppetarkiv.py, plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.json, plugin.video.retrospect/channels/channel.se/svt/chn_svt.py, plugin.video.retrospect/channels/channel.se/tv4se/chn_tv4se.json, plugin.video.retrospect/channels/channel.se/tv4se/chn_tv4se.py, plugin.video.retrospect/channels/channel.se/urplay/chn_urplay.json, plugin.video.retrospect/channels/channel.uk/bbc/chn_bbc.py, plugin.video.retrospect/channels/channel.videos/channel9/chn_channel9.py, plugin.video.retrospect/resources/language/resource.language.en_gb/strings.po, plugin.video.retrospect/resources/language/resource.language.nl_nl/strings.po, plugin.video.retrospect/resources/language/resource.language.sv_se/strings.po, plugin.video.retrospect/resources/libs/helpers/languagehelper.py
Another small update to fix some channel related issues and update some translations. The SVT channel was refactored a lot. …
=> [plugin.video.retrospect] v5.0.5

plugin.video.ign_com/addon.xml, plugin.video.ign_com/changelog.txt
2.3.11 (2019-09-14)
- marked the addon broken due to encoded api changes on the website :(
=> [plugin.video.ign_com] 2.3.11

plugin.video.svtplay/README.md, plugin.video.svtplay/addon.xml
Addon now only supports krypton or higher.
I have upped the requirements to krypton or this addon. …
=> [plugin.video.svtplay] Mark addon as broken in gotham

plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/language/resource.language.en_gb/strings.po, plugin.video.gamekings/resources/language/resource.language.nl_nl/strings.po, plugin.video.gamekings/resources/lib/gamekings_const.py, plugin.video.gamekings/resources/lib/gamekings_list.py, plugin.video.gamekings/resources/lib/gamekings_main.py, plugin.video.gamekings/resources/lib/gamekings_play.py, plugin.video.gamekings/resources/settings.xml
v1.2.16 (2019-09-15)
- added premium video category
- fixes due to website change (september 2019). Let's hope they keep working
- added maximum video quality setting for the new m3u8 videos
=> [plugin.video.gamekings] 1.2.16

plugin.video.southpark_unofficial/addon.xml, plugin.video.southpark_unofficial/changelog.txt, plugin.video.southpark_unofficial/resources/settings.xml, plugin.video.southpark_unofficial/southpark.py
Added southparkstudios.nu support and fixed issue with Premiere episodes …
=> [plugin.video.southpark_unofficial] v0.5.3

plugin.video.svtplay/addon.xml, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/language/resource.language.en_gb/strings.po, plugin.video.svtplay/resources/language/resource.language.sv_se/strings.po, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/svt.py, plugin.video.svtplay/resources/settings.xml
New features and continued clean-up.
Python 2 and 3 compatible.
Will fix the complex entry point next. …
=> [plugin.video.svtplay] 5.0.2

plugin.image.dumpert/addon.xml, plugin.image.dumpert/changelog.txt, plugin.image.dumpert/default.py
v1.0.3 (2019-09-21)
- marked broken for gotham. A new version will be made for Krypton.
=> [plugin.image.dumpert] 1.0.3

plugin.video.svtplay/addon.xml, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/mode/common.py, plugin.video.svtplay/resources/lib/mode/normallist.py, plugin.video.svtplay/resources/lib/playback.py, plugin.video.svtplay/resources/settings.xml
Fixes addon crashing on Kodi 17 due to addon using API method from Kodi 18. …
=> [plugin.video.svtplay] 5.0.3

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
[B]Version 2.1.4[/B]
- Added Fire Power with Will Johnson
- On demand section switched to https://Banned.Video site (Infowars version of Youtube)
- On demand section to include all contributors
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of …
=> [plugin.video.infowars] 2.1.4

plugin.audio.eco99music/addon.py, plugin.audio.eco99music/addon.xml
Eco99music audio Add-on
v0.0.4 (09-10-2019):
Switched to use 'xmltodict' instead of BeautifulSoup because of wrong
XML files parsing. …
=> [plugin.audio.eco99music] v0.0.4

plugin.video.crackle/addon.xml, plugin.video.crackle/resources/lib/globals.py
- Display info improvements
- Code cleanup …
=> [plugin.video.crackle] 2019.10.2

plugin.video.svtplay/addon.xml, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/language/resource.language.en_gb/strings.po, plugin.video.svtplay/resources/language/resource.language.sv_se/strings.po, plugin.video.svtplay/resources/lib/api/svt.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/listing/common.py, plugin.video.svtplay/resources/lib/listing/router.py, plugin.video.svtplay/resources/lib/playback.py, plugin.video.svtplay/resources/lib/settings.py, plugin.video.svtplay/resources/lib/svtplay.py, plugin.video.svtplay/resources/settings.xml
Two new user facing features; kids mode and new sort method.
Massive code overhaul. …
=> [plugin.video.svtplay] 5.0.4

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/channelpack.json, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.be/vtmbe/chn_vtmbe.py, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/urplay/chn_urplay.py, plugin.video.retrospect/channels/channel.videos/channelpack.json, plugin.video.retrospect/channels/channel.videos/dumpert/chn_dumpert.py
Just a small update fixing some channels that broke the past weeks. …
=> [plugin.video.retrospect] v5.0.6

plugin.video.yelo/addon.xml, plugin.video.yelo/main.py, plugin.video.yelo/resources/language/resource.language.en_gb/strings.po, plugin.video.yelo/resources/lib/helpers/dynamic_headers.py, plugin.video.yelo/resources/lib/helpers/helpermethods.py, plugin.video.yelo/resources/lib/kodiwrapper/kodiwrapper.py, plugin.video.yelo/resources/lib/yelo/yelo.py, plugin.video.yelo/resources/settings.xml
=> [plugin.video.yelo] 0.0.5

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/default.py, plugin.video.orftvthek/resources/language/English/strings.po, plugin.video.orftvthek/resources/language/German/strings.po, plugin.video.orftvthek/resources/lib/htmlscraper.py, plugin.video.orftvthek/resources/lib/serviceapi.py
=> [plugin.video.orftvthek] 0.9.2

plugin.video.news12/LICENSE.md, plugin.video.news12/addon.xml, plugin.video.news12/default.py, plugin.video.news12/resources/lib/news12.py
=> [plugin.video.news12] Broken

plugin.video.plutotv/addon.xml, plugin.video.plutotv/resources/lib/plutotv.py
=> [plugin.video.plutotv] 1.1.4

plugin.video.teleup/addon.xml
=> [plugin.video.teleup] Broken

plugin.video.rtsplaytv/README.md, plugin.video.rtsplaytv/addon.xml, plugin.video.rtsplaytv/resources/language/resource.language.de_de/strings.po, plugin.video.rtsplaytv/resources/language/resource.language.en_gb/strings.po, plugin.video.rtsplaytv/resources/language/resource.language.fr_fr/strings.po, plugin.video.rtsplaytv/resources/lib/rtsplaytv.py, plugin.video.rtsplaytv/resources/settings.xml
Plugin update to enable the search feature introduced in `script.module.srgssr` v1.7.0. …
=> [plugin.video.rtsplaytv] 1.6.0

plugin.video.rsiplaytv/README.md, plugin.video.rsiplaytv/addon.xml, plugin.video.rsiplaytv/resources/language/resource.language.de_de/strings.po, plugin.video.rsiplaytv/resources/language/resource.language.en_gb/strings.po, plugin.video.rsiplaytv/resources/language/resource.language.fr_fr/strings.po, plugin.video.rsiplaytv/resources/language/resource.language.it_it/strings.po, plugin.video.rsiplaytv/resources/lib/rsiplaytv.py, plugin.video.rsiplaytv/resources/settings.xml
Plugin update to enable the search feature introduced in `script.module.srgssr` v1.7.0. …
=> [plugin.video.rsiplaytv] v1.6.0

plugin.audio.srfplayradio/README.md, plugin.audio.srfplayradio/addon.xml, plugin.audio.srfplayradio/resources/language/resource.language.de_de/strings.po, plugin.audio.srfplayradio/resources/language/resource.language.en_gb/strings.po, plugin.audio.srfplayradio/resources/language/resource.language.fr_fr/strings.po, plugin.audio.srfplayradio/resources/language/resource.language.it_it/strings.po, plugin.audio.srfplayradio/resources/lib/srfplayradio.py, plugin.audio.srfplayradio/resources/settings.xml
Version 1.0.0 release.
Added "search" feature. …
=> [plugin.audio.srfplayradio] v1.0.0

plugin.video.nhlgcl/addon.py, plugin.video.nhlgcl/addon.xml, plugin.video.nhlgcl/resources/language/resource.language.en_gb/strings.po, plugin.video.nhlgcl/resources/lib/globals.py, plugin.video.nhlgcl/resources/lib/nhl_tv.py, plugin.video.nhlgcl/resources/settings.xml
- Fix error on user cancel stream selection
- Code clean up …
=> [plugin.video.nhlgcl] 2019.10.3

plugin.video.tv3.cat/addon.xml, plugin.video.tv3.cat/changelog.txt, plugin.video.tv3.cat/default.py, plugin.video.tv3.cat/resources/language/German/strings.po, plugin.video.tv3.cat/resources/language/Norwegian/strings.po, plugin.video.tv3.cat/resources/language/Spanish/strings.po
Fixed web server changes. Fixed errors listing videos in two sections
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
=> [plugin.video.tv3.cat] 1.4.1

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/svt/chn_svt.py, plugin.video.retrospect/channels/channel.se/tv4se/chn_tv4se.py, plugin.video.retrospect/channels/channel.se/urplay/chn_urplay.py, plugin.video.retrospect/resources/libs/urihandler.py
Fixed some Swedish channel related issues and a Python 3 issue for HTTP responses without encoding information. …
=> [plugin.video.retrospect] v5.0.8

plugin.video.swrmediathek/addon.xml
All content migrated to the ARD Mediathek.
=> [plugin.video.swrmediathek] 1.0.1

plugin.video.phoenixmediathek/addon.xml
The add-on broke due to website changes.
=> [plugin.video.phoenixmediathek] 1.1.1

plugin.video.unithek/addon.xml
Marked as broken due to website changes
=> [plugin.video.unithek] 1.0.1

plugin.video.youtube/addon.xml, plugin.video.youtube/changelog.txt, plugin.video.youtube/resources/language/resource.language.de_de/strings.po, plugin.video.youtube/resources/language/resource.language.nl_nl/strings.po, plugin.video.youtube/resources/language/resource.language.pl_pl/strings.po, plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/storage.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py, plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py, plugin.video.youtube/resources/lib/youtube_requests.py, plugin.video.youtube/resources/lib/youtube_resolver.py
=> [plugin.video.youtube] v6.5.2

plugin.video.esa/.gitignore, plugin.video.esa/addon.xml, plugin.video.esa/changelog.txt, plugin.video.esa/default.py, plugin.video.esa/resources/language/Czech/strings.po, plugin.video.esa/resources/language/English/strings.po, plugin.video.esa/resources/language/French/strings.po, plugin.video.esa/resources/language/German/strings.po, plugin.video.esa/resources/language/Greek/strings.po, plugin.video.esa/resources/language/Italian/strings.po, plugin.video.esa/resources/language/Portuguese/strings.po, plugin.video.esa/resources/language/Spanish/strings.po, plugin.video.esa/resources/settings.xml
Hi,
This is a maintenance PR due to the website design has completely changed.
Changelog: v1.1.2 (2019.11.03)
- Quick fix due to website new design.
Many hanks in advance and best regards,
jamontes. …
=> [plugin.video.esa] v1.1.2

plugin.audio.eco99music/addon.py, plugin.audio.eco99music/addon.xml, plugin.audio.eco99music/changelog.txt
Solved a bug related to RSS feed tag change which broke the Addon.
The Addon is now Python3 ready. …
=> [plugin.audio.eco99music] v0.0.5

plugin.video.yelo/addon.xml, plugin.video.yelo/main.py, plugin.video.yelo/resources/language/resource.language.en_gb/strings.po, plugin.video.yelo/resources/lib/helpers/UAHelper.py, plugin.video.yelo/resources/lib/helpers/dynamic_headers.py, plugin.video.yelo/resources/lib/helpers/helpermethods.py, plugin.video.yelo/resources/lib/kodiwrapper/kodiwrapper.py, plugin.video.yelo/resources/lib/plugin.py, plugin.video.yelo/resources/lib/statics/static.py, plugin.video.yelo/resources/lib/yelo/yelo.py, plugin.video.yelo/resources/settings.xml
=> [plugin.video.yelo] 0.0.6

plugin.video.svtplay/README.md, plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/lib/api/graphql.py, plugin.video.svtplay/resources/lib/api/svt.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/listing/router.py, plugin.video.svtplay/resources/lib/svtplay.py
Update of SVTPlay due to major changes. …
=> [plugin.video.svtplay] 5.1.0

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.nos/channelpack.json, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/resources/lib/addon.py, plugin.video.retrospect/resources/lib/helpers/datehelper.py
There was a rather annoying bug in 5.1.0 that cause Retrospect to run twice each time. We also fixed the NPO Timestamp issue. …
=> [plugin.video.retrospect] v5.1.1

plugin.video.svtplay/README.md, plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/lib/api/graphql.py, plugin.video.svtplay/resources/lib/listing/router.py
Fixes lack of thumbnail images in video listings …
=> [plugin.video.svtplay] 5.1.1

plugin.video.yelo/addon.xml, plugin.video.yelo/resources/lib/plugin.py, plugin.video.yelo/resources/lib/yelo/yelo.py
=> [plugin.video.yelo] 0.0.7

plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/language/resource.language.en_gb/strings.po, plugin.video.svtplay/resources/language/resource.language.sv_se/strings.po, plugin.video.svtplay/resources/lib/api/graphql.py, plugin.video.svtplay/resources/lib/api/svt.py, plugin.video.svtplay/resources/lib/listing/common.py, plugin.video.svtplay/resources/lib/listing/router.py, plugin.video.svtplay/resources/lib/svtplay.py
Fix for backend change in source (Popular section not working)
Fix broken feature.
Sorry for the many PRs, but the source made huge backend changes and I am trying to restore functionality piece by piece. …
=> [plugin.video.svtplay] 5.1.2

plugin.video.regiotv/LICENSE, plugin.video.regiotv/README.md, plugin.video.regiotv/addon.xml, plugin.video.regiotv/resources/lib/addon.py, plugin.video.regiotv/resources/lib/addon_entry.py, plugin.video.regiotv/resources/lib/data.py
This is a new add-on for (Flemish) regional TV stations.
=> [plugin.video.regiotv] v0.1.0

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.nos/channelpack.json, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/channels/channel.nos/nosnl/chn_nosnl.py, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/svt/chn_svt.py, plugin.video.retrospect/resources/lib/streams/npostream.py
This update mainly contains channel fixes for NPO, NOS and the SVT channel. …
=> [plugin.video.retrospect] v5.1.2

plugin.video.yelo/addon.xml, plugin.video.yelo/resources/lib/helpers/helpermethods.py, plugin.video.yelo/resources/lib/kodiwrapper/kodiwrapper.py, plugin.video.yelo/resources/lib/plugin.py, plugin.video.yelo/resources/lib/yelo/yelo.py
=> [plugin.video.yelo] 0.0.8

plugin.audio.soundcloud/addon.xml, plugin.audio.soundcloud/resources/language/resource.language.nl_nl/strings.po, plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py
* Fixed an issue with client-ID extraction from the SoundCloud website, which broke the plugin (https://github.com/jaylinski/kodi-addon-soundcloud/pull/36)
* Added Dutch translations
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these …
=> [plugin.audio.soundcloud] 3.1.1

plugin.video.infowars/addon.xml, plugin.video.infowars/changelog.txt, plugin.video.infowars/default.py
Version 2.1.5
- Fixed On demand section
- Added On demand menu navigation
- Added Banned.video icon …
=> [plugin.video.infowars] 2.1.5

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/resource.language.cs_cz/strings.po, plugin.video.twitch/resources/language/resource.language.da_dk/strings.po, plugin.video.twitch/resources/language/resource.language.de_de/strings.po, plugin.video.twitch/resources/language/resource.language.en_gb/strings.po, plugin.video.twitch/resources/language/resource.language.es_es/strings.po, plugin.video.twitch/resources/language/resource.language.fr_fr/strings.po, plugin.video.twitch/resources/language/resource.language.he_il/strings.po, plugin.video.twitch/resources/language/resource.language.nb_no/strings.po, plugin.video.twitch/resources/language/resource.language.nl_nl/strings.po, plugin.video.twitch/resources/language/resource.language.pl_pl/strings.po, plugin.video.twitch/resources/lib/twitch_addon/addon/api.py, plugin.video.twitch/resources/lib/twitch_addon/addon/constants.py, plugin.video.twitch/resources/lib/twitch_addon/addon/google_firebase.py, plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py, plugin.video.twitch/resources/settings.xml
**Requires:** https://github.com/xbmc/repo-scripts/pull/1214
2.4.7
[fix] remaining private api calls ie. following games, toggle following games
2.4.6
[add] Settings - Login - Private API Credentials
[fix] basic playback, set default Private API Credentials - Client ID
[fix] oauth short link generation w/ python 3
[rem] Remove deprecated scope chat_login
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered …
=> [plugin.video.twitch] v2.4.7

plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/language/resource.language.en_gb/strings.po, plugin.video.svtplay/resources/language/resource.language.sv_se/strings.po, plugin.video.svtplay/resources/lib/api/graphql.py, plugin.video.svtplay/resources/lib/api/svt.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/listing/common.py
=> [plugin.video.svtplay] 5.1.3

plugin.image.cook/addon.xml
Broken due to site changes and inactivity in recent years
=> [plugin.image.cook] broken

plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/lib/api/graphql.py, plugin.video.svtplay/resources/lib/api/svt.py, plugin.video.svtplay/resources/lib/helper.py, plugin.video.svtplay/resources/lib/listing/common.py, plugin.video.svtplay/resources/lib/listing/listitem.py, plugin.video.svtplay/resources/lib/listing/router.py
Bug fix as I accidently removed a menu option.... 😢 
Lots of refactoring as well, hence the big diff.
Sorry for the many PRs, lot of debt after a big change in the video source. …
=> [plugin.video.svtplay] 5.1.5

plugin.video.dailymotion_com/addon.xml, plugin.video.dailymotion_com/changelog.txt, plugin.video.dailymotion_com/default.py
=> [plugin.video.dailymotion_com] v2.4.0

plugin.video.svtplay/addon.xml, plugin.video.svtplay/default.py, plugin.video.svtplay/resources/lib/api/graphql.py, plugin.video.svtplay/resources/lib/listing/common.py, plugin.video.svtplay/resources/lib/svtplay.py
Fixes a bug where movies were not seen in search results.
🎅🎄 …
=> [plugin.video.svtplay] 5.1.6

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/default.py, plugin.video.orftvthek/resources/language/English/strings.po, plugin.video.orftvthek/resources/language/German/strings.po, plugin.video.orftvthek/resources/lib/Scraper.py, plugin.video.orftvthek/resources/lib/Settings.py, plugin.video.orftvthek/resources/lib/base.py, plugin.video.orftvthek/resources/lib/common.py, plugin.video.orftvthek/resources/lib/helpers.py, plugin.video.orftvthek/resources/lib/htmlscraper.py, plugin.video.orftvthek/resources/lib/serviceapi.py, plugin.video.orftvthek/resources/settings.xml
python2/3 compatible, added "Gapless Video" option, major cleanup, dropped script.module.parsedom and script.common.plugin.cache …
=> [plugin.video.orftvthek] 0.10.0

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/svt/chn_svt.py, plugin.video.retrospect/channels/channel.se/urplay/chn_urplay.py, plugin.video.retrospect/menu_bitrate.py, plugin.video.retrospect/menu_channel_selection.py, plugin.video.retrospect/resources/lib/streams/adaptive.py
This update mainly contains channel fixes for the SVT and UR Play channel. …
=> [plugin.video.retrospect] v5.1.3

plugin.video.zdf_de_2016/addon.xml, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Regex.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/RubricResource.py, plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/TeaserLazyload.py
1.0.16 (2019-12-12)
- fix after zdf website updates …
=> [plugin.video.zdf_de_2016] 1.0.16

plugin.video.sandmann/addon.py, plugin.video.sandmann/addon.xml, plugin.video.sandmann/changelog.txt, plugin.video.sandmann/resources/language/resource.language.de_de/strings.po, plugin.video.sandmann/resources/language/resource.language.en_gb/strings.po, plugin.video.sandmann/resources/settings.xml, plugin.video.sandmann/sandmann.py
- **add**: reload functionality (can be configured in the addon-settings)
- **fix**: images not loading
=> [plugin.video.sandmann] v1.1.0

plugin.video.yelo/addon.xml, plugin.video.yelo/resources/lib/yelo/yelo.py
=> [plugin.video.yelo] 0.0.9

plugin.audio.radio_de/addon.xml, plugin.audio.radio_de/changelog.txt, plugin.audio.radio_de/resources/lib/plugin.py
Simple fix for thumbs not showing in the player
=> [plugin.audio.radio_de] 2.3.5

plugin.video.rsich/addon.xml, plugin.video.rsich/changelog.txt, plugin.video.rsich/default.py, plugin.video.rsich/resources/language/resource.language.en_gb/strings.po, plugin.video.rsich/resources/language/resource.language.it_it/strings.po
Update for python 3.x
Requires https://github.com/xbmc/repo-scripts/pull/1256 …
=> [plugin.video.rsich] 1.2.0

plugin.video.sandmann/addon.py, plugin.video.sandmann/addon.xml, plugin.video.sandmann/changelog.txt, plugin.video.sandmann/resources/language/resource.language.de_de/strings.po, plugin.video.sandmann/resources/language/resource.language.en_gb/strings.po, plugin.video.sandmann/resources/settings.xml, plugin.video.sandmann/sandmann.py
- NEW: List all Episodes instead of just the newest
- FIX: Fixed umlauts-bug in episode title
=> [plugin.video.sandmann] v1.2.0

plugin.video.filmarkivet/addon.xml
Deprecating support for pre Krypton: marking the Gotham version as broken. …
=> [plugin.video.filmarkivet] broken

plugin.library.node.editor/addon.xml, plugin.library.node.editor/resources/lib/addon.py, plugin.library.node.editor/resources/lib/moveNodes.py
1.0.8
- Move node and change name fixes
=> [plugin.library.node.editor] 1.0.8

plugin.audio.radio_de/addon.xml, plugin.audio.radio_de/resources/lib/api.py, plugin.audio.radio_de/resources/lib/plugin.py
=> [plugin.audio.radio_de] 2.4.1

plugin.library.node.editor/addon.xml, plugin.library.node.editor/resources/lib/pluginBrowser.py, plugin.library.node.editor/resources/lib/viewattrib.py
1.0.9 (2/1/2020)
- Fixes plugin listings
=> [plugin.library.node.editor] 1.0.9

plugin.library.node.editor/addon.xml, plugin.library.node.editor/resources/lib/addon.py, plugin.library.node.editor/resources/lib/rules.py
- Fix parent nodes (unquote issues)
=> [plugin.library.node.editor] 1.0.10

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.mtg/channelpack.json, plugin.video.retrospect/channels/channel.mtg/viafree/chn_viafree.py, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.py, plugin.video.retrospect/channels/channel.se/svt/chn_svt.py, plugin.video.retrospect/channels/channel.se/tv4se/chn_tv4se.py, plugin.video.retrospect/resources/lib/favourites.py, plugin.video.retrospect/resources/lib/mediaitem.py, plugin.video.retrospect/resources/lib/plugin.py
This update contains some appearances fixes to both Retrospect and some Swedish channels …
=> [plugin.video.retrospect] v5.1.4

plugin.video.plutotv/addon.xml, plugin.video.plutotv/default.py, plugin.video.plutotv/pseudotv_recommended.py, plugin.video.plutotv/resources/language/resource.language.en_gb/strings.po, plugin.video.plutotv/resources/lib/net.py, plugin.video.plutotv/resources/lib/plutotv.py, plugin.video.plutotv/resources/skins/default/1080i/script.module.uepg.guide.xml
=> [plugin.video.plutotv] 1.1.6

plugin.audio.podcatcher/addon.xml
For updates of PodCatcher, please upgrade to krypton or above
=> [plugin.audio.podcatcher] broken

plugin.video.vrt.nu/README.md, plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/lib/apihelper.py, plugin.video.vrt.nu/resources/lib/data.py, plugin.video.vrt.nu/resources/lib/favorites.py, plugin.video.vrt.nu/resources/lib/helperobjects.py, plugin.video.vrt.nu/resources/lib/kodiutils.py, plugin.video.vrt.nu/resources/lib/metadata.py, plugin.video.vrt.nu/resources/lib/playerinfo.py, plugin.video.vrt.nu/resources/lib/resumepoints.py, plugin.video.vrt.nu/resources/lib/search.py, plugin.video.vrt.nu/resources/lib/streamservice.py, plugin.video.vrt.nu/resources/lib/tvguide.py, plugin.video.vrt.nu/resources/lib/utils.py, plugin.video.vrt.nu/resources/lib/vrtplayer.py, plugin.video.vrt.nu/resources/lib/webscraper.py
- Fix an issue related to type-handling for settings
- Fix an issue related to marking played videos as watched when using Up Next
- Small fix for livestreams
- Improvements to metadata handling specific to Kodi rendering
- Support multiple YouTube links per channel
=> [plugin.video.vrt.nu] v2.3.1

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/resources/lib/base.py, plugin.video.orftvthek/resources/lib/htmlscraper.py
fixed kodi crash when using the playlist listitem …
=> [plugin.video.orftvthek] 0.10.1

plugin.video.plutotv/addon.xml, plugin.video.plutotv/pseudotv_recommended.py, plugin.video.plutotv/resources/language/resource.language.en_gb/strings.po, plugin.video.plutotv/resources/lib/net.py, plugin.video.plutotv/resources/lib/plutotv.py
=> [plugin.video.plutotv] 1.1.8

plugin.video.vrt.nu/README.md, plugin.video.vrt.nu/addon.xml, plugin.video.vrt.nu/resources/lib/addon.py, plugin.video.vrt.nu/resources/lib/apihelper.py, plugin.video.vrt.nu/resources/lib/favorites.py, plugin.video.vrt.nu/resources/lib/kodiutils.py, plugin.video.vrt.nu/resources/lib/metadata.py, plugin.video.vrt.nu/resources/lib/playerinfo.py, plugin.video.vrt.nu/resources/lib/resumepoints.py, plugin.video.vrt.nu/resources/lib/search.py, plugin.video.vrt.nu/resources/lib/streamservice.py, plugin.video.vrt.nu/resources/lib/tokenresolver.py, plugin.video.vrt.nu/resources/lib/tvguide.py, plugin.video.vrt.nu/resources/lib/utils.py, plugin.video.vrt.nu/resources/lib/webscraper.py
- Fix issues related to categories scraping and caching (@mediaminister)
- Various improvements to TV guide (@dagwieers)
This is another bugfix release. Without the bugfix some of our users will have issues with the categories listing in 2 days (it expires after 7 days, since our last release).
=> [plugin.video.vrt.nu] v2.3.2

plugin.video.101barz/addon.xml, plugin.video.101barz/changelog.txt, plugin.video.101barz/default.py, plugin.video.101barz/resources/language/resource.language.en_gb/strings.po, plugin.video.101barz/resources/language/resource.language.nl_nl/strings.po, plugin.video.101barz/resources/settings.xml
1.1.0 (2020-01-15)
- changes due to major website changes
=> [plugin.video.101barz] 1.1.0

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/channelpack.json, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.nick/channelpack.json, plugin.video.retrospect/channels/channel.nick/nickelodeon/chn_nickelodeon.py, plugin.video.retrospect/channels/channel.nick/nickjr/chn_nickjr.py, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.py, plugin.video.retrospect/channels/channel.se/tv4se/chn_tv4se.py
This update contains a fix for VRT.nu that broken, Nickelodeon and more appearances fixes for Swedish channels. …
=> [plugin.video.retrospect] v5.1.5

plugin.video.puls4/README.md, plugin.video.puls4/addon.xml, plugin.video.puls4/changelog.txt, plugin.video.puls4/default.py, plugin.video.puls4/resources/language/English/strings.po, plugin.video.puls4/resources/language/English/strings.xml, plugin.video.puls4/resources/language/German/strings.po, plugin.video.puls4/resources/language/German/strings.xml, plugin.video.puls4/resources/lib/api_scraper.py, plugin.video.puls4/resources/lib/app_common.py, plugin.video.puls4/resources/lib/base.py, plugin.video.puls4/resources/lib/livePlayer.py, plugin.video.puls4/resources/lib/settings.py, plugin.video.puls4/resources/lib/utils.py, plugin.video.puls4/resources/lib/xxtea.py, plugin.video.puls4/resources/settings.xml
* Added Livestream
* Kodi19 support
* Add categorys like 'ganze videos' to Shows
* Since the API is slow, added possibility to cache API calls to improve loading time
* Updated Icon/Banner handling
* Code restructure/cleanup …
=> [plugin.video.puls4] 0.4.0

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/channelpack.json, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py
This update contains a fix for VRT.nu that broken again! …
=> [plugin.video.retrospect] v5.1.6

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/addon/api.py, plugin.video.twitch/resources/lib/twitch_addon/addon/error_handling.py, plugin.video.twitch/resources/lib/twitch_addon/routes/browse.py, plugin.video.twitch/resources/lib/twitch_addon/routes/following.py, plugin.video.twitch/resources/lib/twitch_addon/routes/main.py, plugin.video.twitch/resources/lib/twitch_addon/routes/play.py, plugin.video.twitch/resources/lib/twitch_addon/routes/search.py, plugin.video.twitch/resources/lib/twitch_addon/routes/search_history.py, plugin.video.twitch/resources/settings.xml
=> [plugin.video.twitch] v2.4.8

plugin.video.composite_for_plex/addon.xml, plugin.video.composite_for_plex/resources/language/resource.language.de_de/strings.po, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/processing/xml.py
- add support forum
- fix playlists that are broken for some people …
=> [plugin.video.composite_for_plex] v0.8.2

plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/lib/api/svt.py
=> [plugin.video.svtplay] 5.1.8

plugin.audio.navahang/addon.xml, plugin.audio.navahang/main.py
=> [plugin.audio.navahang] v2.4

plugin.video.iplayerwww/addon.xml, plugin.video.iplayerwww/changelog.txt, plugin.video.iplayerwww/resources/lib/ipwww_video.py
=> [plugin.video.iplayerwww] 3.0.47

plugin.audio.mixcloud/README, plugin.audio.mixcloud/addon.xml, plugin.audio.mixcloud/changelog.txt, plugin.audio.mixcloud/default.py, plugin.audio.mixcloud/resources/language/Dutch/strings.po, plugin.audio.mixcloud/resources/language/English/strings.po, plugin.audio.mixcloud/resources/language/German/strings.po
fixed local resolver
added german language
=> [plugin.audio.mixcloud] v.2.4.2

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.nos/channelpack.json, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py
There was a bug in the latest NPO channel. Had to fix it. …
=> [plugin.video.retrospect] v5.1.8

plugin.video.arloview/addon.xml, plugin.video.arloview/resources/lib/__init__.py, plugin.video.arloview/resources/lib/arlo_stream.py
Upgrade to new version of arlo, patch sseclient (script.module.ssearlo)
NOTE:
3 items need to be merged at the same time
- [script.module.ssearlo] 0.0.22
- [script.module.arlo] 1.2.33
- [plugin.video.arlowview] 1.1.0
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi …
=> [plugin.video.arloview] 1.1.0

plugin.video.zoneminder/addon.xml, plugin.video.zoneminder/changelog.txt, plugin.video.zoneminder/resources/language/resource.language.en_gb/strings.po, plugin.video.zoneminder/resources/settings.xml, plugin.video.zoneminder/zoneminder.py
Update Zoneminder plugin with new API authentication methods. …
=> [plugin.video.zoneminder] 2.0.2

plugin.googledrive/addon.py, plugin.googledrive/addon.xml, plugin.googledrive/resources/language/resource.language.en_gb/strings.po, plugin.googledrive/resources/language/resource.language.it_it/strings.po, plugin.googledrive/resources/lib/provider/googledrive.py, plugin.googledrive/resources/settings.xml
* Fix playback
* Fix search
* Fix videos in Google Photos …
=> [plugin.googledrive] 1.3.3

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/routes/followed.py, plugin.video.twitch/resources/lib/twitch_addon/routes/game_streams.py, plugin.video.twitch/resources/lib/twitch_addon/routes/streams.py
=> [plugin.video.twitch] 2.4.9

plugin.audio.mixcloud/README, plugin.audio.mixcloud/addon.xml, plugin.audio.mixcloud/changelog.txt, plugin.audio.mixcloud/default.py
- handle exclusive cloudcasts
- removed obsolete menu items
- fixed local resolver
=> [plugin.audio.mixcloud] 2.4.3

plugin.video.vimeo/addon.xml, plugin.video.vimeo/resources/language/resource.language.de_de/strings.po, plugin.video.vimeo/resources/language/resource.language.en_gb/strings.po, plugin.video.vimeo/resources/lib/models/video.py, plugin.video.vimeo/resources/lib/vimeo/api.py
Fixed a small issue with on-demand videos in search listings.
See https://github.com/jaylinski/kodi-addon-vimeo/pull/20 for details. …
=> [plugin.video.vimeo] 5.1.1

plugin.video.imdb.trailers/addon.xml, plugin.video.imdb.trailers/changelog.txt, plugin.video.imdb.trailers/default.py, plugin.video.imdb.trailers/resources/language/resource.language.de_de/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.en_gb/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.es_es/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.fr_fr/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.tr_tr/strings.po, plugin.video.imdb.trailers/resources/lib/imdb_trailers.py
=> [plugin.video.imdb.trailers] v2.1.9

plugin.video.sandmann/addon.py, plugin.video.sandmann/addon.xml, plugin.video.sandmann/changelog.txt
* fix a bug where the update-interval was initiated multiple times
=> [plugin.video.sandmann] v1.2.1

plugin.video.vimeo/addon.xml, plugin.video.vimeo/resources/language/resource.language.de_de/strings.po, plugin.video.vimeo/resources/language/resource.language.en_gb/strings.po, plugin.video.vimeo/resources/lib/vimeo/api.py, plugin.video.vimeo/resources/plugin.py
Fixes a minor issue with unavailable HLS streams and a wrong localization.
See https://github.com/jaylinski/kodi-addon-vimeo/pull/24 for details. …
=> [plugin.video.vimeo] 5.1.2

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/resources/lib/htmlscraper.py
=> [plugin.video.orftvthek] 0.10.2

plugin.googledrive/addon.xml, plugin.googledrive/resources/language/resource.language.en_gb/strings.po, plugin.googledrive/resources/settings.xml
=> [plugin.googledrive] 1.3.4

plugin.video.mediathek/addon.xml
New PR to replace https://github.com/xbmc/repo-plugins/pull/2735 with a proper `<broken>` messages. …
=> [plugin.video.mediathek] 0.9.4 - Broken

plugin.video.spurs-tv/addon.py, plugin.video.spurs-tv/addon.xml, plugin.video.spurs-tv/changelog.txt, plugin.video.spurs-tv/resources/language/resource.language.en_gb/strings.po, plugin.video.spurs-tv/resources/lib/api.py, plugin.video.spurs-tv/resources/lib/new_stadium.py
Adds pagination and extra categories …
=> [plugin.video.spurs-tv] 2.16.0

plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/lib/api/graphql.py, plugin.video.svtplay/resources/lib/api/svt.py, plugin.video.svtplay/resources/lib/listing/listitem.py, plugin.video.svtplay/resources/lib/svtplay.py
=> [plugin.video.svtplay] 5.1.9

plugin.video.nos/addon.xml, plugin.video.nos/resources/lib/nos.py
Fixed parsing of latest website update
=> [plugin.video.nos] 4.0.3

plugin.video.orftvthek/addon.xml, plugin.video.orftvthek/changelog.txt, plugin.video.orftvthek/resources/lib/htmlscraper.py
fixed the livestream error caused by markup changes from special news shows …
=> [plugin.video.orftvthek] 0.10.3

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/channelpack.json, plugin.video.retrospect/channels/channel.de/channelpack.json, plugin.video.retrospect/channels/channel.mtg/channelpack.json, plugin.video.retrospect/channels/channel.mtg/viafree/chn_viafree.py, plugin.video.retrospect/channels/channel.mtv/channelpack.json, plugin.video.retrospect/channels/channel.nick/channelpack.json, plugin.video.retrospect/channels/channel.no/channelpack.json, plugin.video.retrospect/channels/channel.nos/channelpack.json, plugin.video.retrospect/channels/channel.regionalnl/channelpack.json, plugin.video.retrospect/channels/channel.regionalnl/lokaal/chn_lokaal.py, plugin.video.retrospect/channels/channel.rtlnl/channelpack.json, plugin.video.retrospect/channels/channel.sbsnl/channelpack.json, plugin.video.retrospect/channels/channel.se/channelpack.json, plugin.video.retrospect/channels/channel.se/tv4se/chn_tv4se.py, plugin.video.retrospect/channels/channel.streams/channelpack.json, plugin.video.retrospect/channels/channel.uk/channelpack.json, plugin.video.retrospect/channels/channel.videos/channelpack.json, plugin.video.retrospect/resources/lib/__init__.py, plugin.video.retrospect/resources/lib/chn_class.py, plugin.video.retrospect/resources/lib/helpers/subtitlehelper.py, plugin.video.retrospect/resources/lib/menu.py, plugin.video.retrospect/resources/lib/paramparser.py, plugin.video.retrospect/resources/lib/pickler.py, plugin.video.retrospect/resources/lib/player.py, plugin.video.retrospect/resources/lib/plugin.py, plugin.video.retrospect/resources/lib/xbmcwrapper.py
In this version of Retrospect we fixed some minor bugs in channels and introduced two new major changes. The first one is related to the way we detect whether playback started: we now properly inherit from the Kodi classes instead of having our own code. Secondly, we finally got rid of our `pickle` data in the item's urls. This caused minor updates to items, such as images or dates, to make Kodi see the items as new, because the `pickle` in its url changed. We now store a reference to a pickled file in the Retrospect user data folder.
- [add-on …
=> [plugin.video.retrospect] v5.2.0

plugin.video.nhklive/README.txt, plugin.video.nhklive/addon.xml, plugin.video.nhklive/changelog.txt, plugin.video.nhklive/resources/lib/scraper.py
=> plugin.video.nhklive 3.0.12

plugin.video.hgtv/README.txt, plugin.video.hgtv/addon.xml, plugin.video.hgtv/changelog.txt, plugin.video.hgtv/resources/lib/scraper.py
=> plugin.video.hgtv 3.0.13

plugin.video.aswim/README.txt, plugin.video.aswim/addon.xml, plugin.video.aswim/resources/lib/scraper.py
=> plugin.video.aswim 3.0.4

plugin.video.tvokids/README.txt, plugin.video.tvokids/addon.xml, plugin.video.tvokids/changelog.txt, plugin.video.tvokids/resources/lib/scraper.py
=> plugin.video.tvokids 3.0.4

plugin.video.pbskids/README.txt, plugin.video.pbskids/addon.xml, plugin.video.pbskids/changelog.txt, plugin.video.pbskids/resources/lib/scraper.py
=> plugin.video.pbskids 3.0.7

plugin.video.pcloud-video-streaming/addon.xml, plugin.video.pcloud-video-streaming/changelog.txt
v1.4.1- Now also made available as a Music add-on. …
=> [plugin.video.pcloud-video-streaming] 1.4.1

plugin.audio.shoutcast/addon.xml, plugin.audio.shoutcast/changelog.txt, plugin.audio.shoutcast/resources/lib/api.py
- **General**
- Add-on name: SHOUTcast
- Add-on ID: plugin.audio.shoutcast
- Version number: 2.4.1
- URL: 
With this Add-on you can browse more than 50.000 free internet radio stations. Current Features:[CR]- Top 500 Stations[CR]- Browse by genre (and subgenre if enabled in settings)[CR]- Search Station by name[CR]- Search Stations by current playing track[CR]- You can manage a "My Stations"-list[CR]- bitrate and amount of listeners visible and sortable[CR]- 500 Stations on each Page (can be changed in the settings)[CR]- uses cache (24h genre, 1h station listings)
2.4.1 (29.3.2020)
- Fix requests
=> [plugin.audio.shoutcast] 2.4.1

plugin.audio.soundcloud/addon.xml, plugin.audio.soundcloud/resources/lib/kodi/vfs.py, plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py, plugin.audio.soundcloud/resources/plugin.py
Fixed loading of large (> 50) track lists.
Also fixed some code style issues.
See https://github.com/jaylinski/kodi-addon-soundcloud/compare/v3.1.1...master for details. …
=> [plugin.audio.soundcloud] 3.1.2

plugin.video.vimeo/addon.xml, plugin.video.vimeo/resources/language/resource.language.de_de/strings.po, plugin.video.vimeo/resources/language/resource.language.en_gb/strings.po, plugin.video.vimeo/resources/lib/kodi/items.py, plugin.video.vimeo/resources/lib/kodi/vfs.py, plugin.video.vimeo/resources/lib/models/channel.py, plugin.video.vimeo/resources/lib/models/group.py, plugin.video.vimeo/resources/lib/models/user.py, plugin.video.vimeo/resources/lib/models/video.py, plugin.video.vimeo/resources/lib/vimeo/api.py, plugin.video.vimeo/resources/plugin.py
This is a patch release which fixes the following issues:
* Use H264 fallback if video resolution is not available
* Videos are now marked as watched again
* Plugin now works with live video streams
I also did some code style fixes.
Details: https://github.com/jaylinski/kodi-addon-vimeo/compare/v5.1.2...master
- This …
=> [plugin.video.vimeo] 5.1.3

plugin.video.nhklive/README.txt, plugin.video.nhklive/addon.xml, plugin.video.nhklive/changelog.txt, plugin.video.nhklive/resources/lib/scraper.py
=> plugin.video.nhklive 3.0.14

plugin.video.zattoobox/LICENSE.txt, plugin.video.zattoobox/addon.xml, plugin.video.zattoobox/changelog.txt, plugin.video.zattoobox/plugin.py, plugin.video.zattoobox/resources/lib/core/zapisession.py, plugin.video.zattoobox/resources/lib/core/zbaddonproxy.py, plugin.video.zattoobox/resources/lib/core/zbdirectoryitem.py, plugin.video.zattoobox/resources/lib/core/zbextension.py, plugin.video.zattoobox/resources/lib/core/zbfolderitem.py, plugin.video.zattoobox/resources/lib/core/zbplayableitem.py, plugin.video.zattoobox/resources/lib/extensions/livetv.py, plugin.video.zattoobox/resources/lib/extensions/recordings.py
The plugin stopped working due to provider changes. Fixed. …
=> [plugin.video.zattoobox] 1.0.6

plugin.video.nasa/addon.xml, plugin.video.nasa/changelog.txt
- **General**
- Add-on name: Nasa
- Add-on ID: plugin.video.nasa
- Version number: 3.0.0
- URL: https://github.com/XBMC-Addons/plugin.video.nasa
This video plugin provides access to more than 1800 videos, 8 vodcasts and 4 nasa-tv livestreams[CR]All content is dynamic and should be always up to date.
3.0.0 (12.04.2020)
- Automated submissions for gotham
=> [plugin.video.nasa@gotham] 3.0.0

plugin.video.nhklive/addon.xml, plugin.video.nhklive/resources/lib/scraper.py
=> plugin.video.nhklive 3.0.16

plugin.video.fox.news/addon.xml, plugin.video.fox.news/resources/lib/scraper.py
=> plugin.video.fox.news

plugin.video.snagfilms/addon.xml
Mark as broken. Website has shutdown. …
=> plugin.video.snagfilms 3.0.8

plugin.video.wabc/addon.xml, plugin.video.wabc/changelog.txt, plugin.video.wabc/readme.txt, plugin.video.wabc/resources/lib/scraper.py
=> plugin.video.wabc 3.0.14

plugin.video.themoviedb.helper/addon.xml, plugin.video.themoviedb.helper/context-addtouserlist.py, plugin.video.themoviedb.helper/context-library-userlist.py, plugin.video.themoviedb.helper/context-library.py, plugin.video.themoviedb.helper/context-open.py, plugin.video.themoviedb.helper/context-play.py, plugin.video.themoviedb.helper/context-refresh-item.py, plugin.video.themoviedb.helper/context-removefromuserlist.py, plugin.video.themoviedb.helper/resources/language/resource.language.en_gb/strings.po, plugin.video.themoviedb.helper/resources/lib/constants.py, plugin.video.themoviedb.helper/resources/lib/container.py, plugin.video.themoviedb.helper/resources/lib/context.py, plugin.video.themoviedb.helper/resources/lib/downloader.py, plugin.video.themoviedb.helper/resources/lib/fanarttv.py, plugin.video.themoviedb.helper/resources/lib/kodilibrary.py, plugin.video.themoviedb.helper/resources/lib/listitem.py, plugin.video.themoviedb.helper/resources/lib/omdb.py, plugin.video.themoviedb.helper/resources/lib/player.py, plugin.video.themoviedb.helper/resources/lib/plugin.py, plugin.video.themoviedb.helper/resources/lib/requestapi.py, plugin.video.themoviedb.helper/resources/lib/script.py, plugin.video.themoviedb.helper/resources/lib/service.py, plugin.video.themoviedb.helper/resources/lib/tmdb.py, plugin.video.themoviedb.helper/resources/lib/traktapi.py, plugin.video.themoviedb.helper/resources/lib/utils.py, plugin.video.themoviedb.helper/resources/players/embycon.json, plugin.video.themoviedb.helper/resources/players/embycon.parentid.json, plugin.video.themoviedb.helper/resources/players/netflix.json, plugin.video.themoviedb.helper/resources/players/youtube.json, plugin.video.themoviedb.helper/resources/settings.xml
Several updates including:
Better window management of extendedinfo type replacement using native kodi dialogvideoinfo.
Improvements to service monitor, library integration, trakt management and other functions.
Added blur function to service monitor.
Many other improvements.
- This add-on repository has automated code …
=> plugin.video.themoviedb.helper 2.4.36

plugin.video.fox.news/addon.xml, plugin.video.fox.news/resources/lib/scraper.py
=> plugin.video.fox.news 6.0.3

plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/language/resource.language.en_gb/strings.po, plugin.video.gamekings/resources/language/resource.language.nl_nl/strings.po, plugin.video.gamekings/resources/lib/gamekings_const.py, plugin.video.gamekings/resources/lib/gamekings_list.py, plugin.video.gamekings/resources/lib/gamekings_main.py
v1.2.17 (2020-05-02)
- added video on frontpage category
=> [plugin.video.gamekings] 1.2.17

plugin.video.tv3.cat/addon.xml, plugin.video.tv3.cat/changelog.txt, plugin.video.tv3.cat/resources/lib/tv3cat/TV3cat.py
=> [plugin.video.tv3.cat] v1.4.6

plugin.audio.rne/README.md, plugin.audio.rne/addon.xml, plugin.audio.rne/changelog.txt, plugin.audio.rne/default.py, plugin.audio.rne/resources/language/English/strings.po, plugin.audio.rne/resources/language/French/strings.po, plugin.audio.rne/resources/language/German/strings.po, plugin.audio.rne/resources/language/Spanish/strings.po, plugin.audio.rne/resources/lib/lutil.py, plugin.audio.rne/resources/lib/rne_api.py, plugin.audio.rne/resources/tests/test_api.py
Hi,
This is a maintenance PR for the RNE add-on due to website changes:
- Several code fixes due to website changes.
Please, bear in mind that this is a pure Python2 version for Helix branch up to Leia.
I will summit another PR for the Matrix branch which is pure Python3.
jamontes.
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but …
=> [plugin.audio.rne] v1.0.13

plugin.video.aswim/addon.xml, plugin.video.aswim/resources/lib/scraper.py
=> plugin.video.aswim 3.0.5

plugin.video.composite_for_plex/addon.xml, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/cache_control.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/constants.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/containers.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/common.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/context_menu.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/plex_online.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/plex_plugin.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/logger.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/playback.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/processing/plex_online.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/processing/xml.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/up_next.py, plugin.video.composite_for_plex/resources/lib/composite_addon/composite.py, plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plex.py, plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plexserver.py, plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plexsignin.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/display_known_servers.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/get_content.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/search_all.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/widgets.py
equivalent: #2910
diff: https://github.com/anxdpanic/plugin.video.composite_for_plex/compare/official_repository_matrix …
=> [plugin.video.composite_for_plex] 1.1.1+matrix.1

README.md
The issue tracker URL linked to an outdated website.
Also updated links to use https. :lock: 
Should this be also done on all branches?
It should probably be also updated on https://github.com/xbmc/repo-scripts and https://github.com/xbmc/repo-scrapers. …
=> [readme] Update issue tracker URL

plugin.video.composite_for_plex/addon.xml, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/cache_control.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/constants.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/containers.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/common.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/context_menu.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/plex_online.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/items/plex_plugin.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/logger.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/playback.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/processing/plex_online.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/processing/xml.py, plugin.video.composite_for_plex/resources/lib/composite_addon/addon/up_next.py, plugin.video.composite_for_plex/resources/lib/composite_addon/composite.py, plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plex.py, plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plexserver.py, plugin.video.composite_for_plex/resources/lib/composite_addon/plex/plexsignin.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/display_known_servers.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/get_content.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/search_all.py, plugin.video.composite_for_plex/resources/lib/composite_addon/routes/widgets.py
=> [plugin.video.composite_for_plex] 1.1.1

plugin.video.twitch/addon.xml, plugin.video.twitch/resources/language/resource.language.cs_cz/strings.po, plugin.video.twitch/resources/language/resource.language.da_dk/strings.po, plugin.video.twitch/resources/language/resource.language.de_de/strings.po, plugin.video.twitch/resources/language/resource.language.en_gb/strings.po, plugin.video.twitch/resources/language/resource.language.es_es/strings.po, plugin.video.twitch/resources/language/resource.language.fr_fr/strings.po, plugin.video.twitch/resources/language/resource.language.he_il/strings.po, plugin.video.twitch/resources/language/resource.language.nb_no/strings.po, plugin.video.twitch/resources/language/resource.language.nl_nl/strings.po, plugin.video.twitch/resources/language/resource.language.pl_pl/strings.po, plugin.video.twitch/resources/lib/twitch_addon/addon/common/log_utils.py, plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py, plugin.video.twitch/resources/lib/twitch_addon/addon/strings.py, plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py, plugin.video.twitch/resources/lib/twitch_addon/routes/channel_videos.py, plugin.video.twitch/resources/lib/twitch_addon/routes/clips.py, plugin.video.twitch/resources/lib/twitch_addon/routes/edit_languages.py, plugin.video.twitch/resources/lib/twitch_addon/routes/followed.py, plugin.video.twitch/resources/lib/twitch_addon/routes/game_streams.py, plugin.video.twitch/resources/lib/twitch_addon/routes/play.py, plugin.video.twitch/resources/lib/twitch_addon/routes/streams.py, plugin.video.twitch/resources/settings.xml
equivalent: #2906
diff: https://github.com/MrSprigster/Twitch-on-Kodi/compare/matrix
requires: https://github.com/xbmc/repo-scripts/pull/1549 …
=> [plugin.video.twitch] 2.5.0+matrix.1

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/language/resource.language.cs_cz/strings.po, plugin.video.twitch/resources/language/resource.language.da_dk/strings.po, plugin.video.twitch/resources/language/resource.language.de_de/strings.po, plugin.video.twitch/resources/language/resource.language.en_gb/strings.po, plugin.video.twitch/resources/language/resource.language.es_es/strings.po, plugin.video.twitch/resources/language/resource.language.fr_fr/strings.po, plugin.video.twitch/resources/language/resource.language.he_il/strings.po, plugin.video.twitch/resources/language/resource.language.nb_no/strings.po, plugin.video.twitch/resources/language/resource.language.nl_nl/strings.po, plugin.video.twitch/resources/language/resource.language.pl_pl/strings.po, plugin.video.twitch/resources/lib/twitch_addon/addon/common/log_utils.py, plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py, plugin.video.twitch/resources/lib/twitch_addon/addon/strings.py, plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py, plugin.video.twitch/resources/lib/twitch_addon/routes/channel_videos.py, plugin.video.twitch/resources/lib/twitch_addon/routes/clips.py, plugin.video.twitch/resources/lib/twitch_addon/routes/edit_languages.py, plugin.video.twitch/resources/lib/twitch_addon/routes/followed.py, plugin.video.twitch/resources/lib/twitch_addon/routes/game_streams.py, plugin.video.twitch/resources/lib/twitch_addon/routes/play.py, plugin.video.twitch/resources/lib/twitch_addon/routes/streams.py, plugin.video.twitch/resources/settings.xml
requires: https://github.com/xbmc/repo-scripts/pull/1548 …
=> [plugin.video.twitch] 2.5.0

plugin.video.iranintl/addon.xml, plugin.video.iranintl/default.py
Parse m3u8 stream list and show all available stream qualities …
=> [plugin.video.iranintl] v1.1.0

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.py, plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.json, plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.py, plugin.video.retrospect/resources/language/resource.language.nl_nl/strings.po, plugin.video.retrospect/resources/lib/addonsettings.py, plugin.video.retrospect/resources/settings.xml
This version of Retrospect fixes some login related issues for VRT.nu and Dplay.se and squashes a minor bug for kijk.nl. …
=> [plugin.video.retrospect] v5.2.5+matrix.1

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.py, plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.json, plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.py, plugin.video.retrospect/resources/language/resource.language.nl_nl/strings.po, plugin.video.retrospect/resources/lib/addonsettings.py, plugin.video.retrospect/resources/settings.xml
This version of Retrospect fixes some login related issues for VRT.nu and Dplay.se and squashes a minor bug for kijk.nl.
Leia version of https://github.com/xbmc/repo-plugins/pull/2927
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these …
=> [plugin.video.retrospect] v5.2.5

plugin.video.imdb.trailers/addon.xml, plugin.video.imdb.trailers/resources/language/resource.language.de_de/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.en_gb/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.es_es/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.fr_fr/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.tr_tr/strings.po, plugin.video.imdb.trailers/resources/lib/imdb_trailers.py
Updated api calls
same as #2913 but for matrix branch …
=> [plugin.video.imdb.trailers] v2.1.11.1 matrix

plugin.video.imdb.trailers/addon.xml, plugin.video.imdb.trailers/resources/language/resource.language.de_de/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.en_gb/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.es_es/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.fr_fr/strings.po, plugin.video.imdb.trailers/resources/language/resource.language.tr_tr/strings.po, plugin.video.imdb.trailers/resources/lib/imdb_trailers.py
=>  [plugin.video.imdb.trailers] v2.1.11 leia

plugin.video.twitch/addon.xml, plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py, plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py, plugin.video.twitch/resources/lib/twitch_addon/service.py
equivalent: #2923 
matrix diff: https://github.com/MrSprigster/Twitch-on-Kodi/compare/matrix …
=> [plugin.video.twitch] 2.5.1+matrix.1

plugin.video.twitch/addon.xml, plugin.video.twitch/changelog.txt, plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py, plugin.video.twitch/resources/lib/twitch_addon/addon/utils.py, plugin.video.twitch/resources/lib/twitch_addon/service.py
Equivalent: #2924
matrix diff: https://github.com/MrSprigster/Twitch-on-Kodi/compare/matrix …
=> [plugin.video.twitch] 2.5.1

plugin.video.curiositystream/addon.xml, plugin.video.curiositystream/resources/language/resource.language.en_gb/strings.po, plugin.video.curiositystream/resources/lib/curiositystream.py, plugin.video.curiositystream/resources/lib/router.py
Version 2.0.0 of Curiositystream plugin.
Changes:
- Added search
- Added subtitles
- Removed "News this week"
- Added Add/Remove watchlist context menu action
- Improvements on video description
=> [plugin.video.curiositystream] 2.0.0

plugin.audio.kxmxpxtx.bandcamp/addon.xml, plugin.audio.kxmxpxtx.bandcamp/default.py, plugin.audio.kxmxpxtx.bandcamp/resources/lib/bandcamp_api/bandcamp.py, plugin.audio.kxmxpxtx.bandcamp/resources/lib/kodi/ListItems.py
Fix for the search:
https://forum.kodi.tv/showthread.php?tid=354190&pid=2952840#pid2952840
Workaround for the playlist:
https://forum.kodi.tv/showthread.php?tid=354733
Working share for:
Yatse
Cast Kodi Firefox addon
=> [plugin.audio.kxmxpxtx.bandcamp] 0.0.4

plugin.video.filmsforaction/README.md, plugin.video.filmsforaction/addon.xml, plugin.video.filmsforaction/changelog.txt, plugin.video.filmsforaction/default.py, plugin.video.filmsforaction/icon_and_fanart_credits.txt, plugin.video.filmsforaction/resources/language/resource.language.de_de/strings.po, plugin.video.filmsforaction/resources/language/resource.language.en_gb/strings.po, plugin.video.filmsforaction/resources/language/resource.language.es_es/strings.po, plugin.video.filmsforaction/resources/language/resource.language.fr_fr/strings.po, plugin.video.filmsforaction/resources/lib/ffa_api.py, plugin.video.filmsforaction/resources/lib/lutil.py
Hi,
This is a maintenance PR for the filmsforaction  add-on due to website changes:
- Quick fix due to website changes.
Please, bear in mind that this is a pure Python2 version for Isengard branch up to Leia.
I will summit another PR for the Matrix branch which is pure Python3.
jamontes.
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best …
=> [plugin.video.filmsforaction] v1.1.1

plugin.video.svtplay/addon.xml, plugin.video.svtplay/resources/lib/svtplay.py
Fix for broken watched status. …
=> [plugin.video.svtplay] 5.1.10

plugin.video.liveleak/addon.xml, plugin.video.liveleak/changelog.txt, plugin.video.liveleak/default.py, plugin.video.liveleak/resources/language/resource.language.en_gb/strings.po
Fix YT video link parsing, various other fixes and upgrades including proper unicode handling
=> [plugin.video.liveleak] 1.4.0

plugin.video.gamekings/addon.xml, plugin.video.gamekings/changelog.txt, plugin.video.gamekings/resources/lib/gamekings_const.py, plugin.video.gamekings/resources/lib/gamekings_play.py
v1.2.18 (2020-06-05)
- fixed playback for youtube videos
=> [plugin.video.gamekings] 1.2.18

plugin.video.liveleak/addon.xml, plugin.video.liveleak/changelog.txt, plugin.video.liveleak/default.py, plugin.video.liveleak/resources/language/resource.language.en_gb/strings.po
FIX: Gracefully handle anomalous missing element exceptions
Add: new categories since I needed to do a PR anyway
=> [plugin.video.liveleak] 1.4.1

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.nick/nickjr/chn_nickjr.py, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/channels/channel.se/svt/chn_svt.py, plugin.video.retrospect/resources/data/settings_template.xml, plugin.video.retrospect/resources/language/resource.language.en_gb/strings.po, plugin.video.retrospect/resources/language/resource.language.fi_fi/strings.po, plugin.video.retrospect/resources/language/resource.language.nb_no/strings.po, plugin.video.retrospect/resources/language/resource.language.nl_nl/strings.po, plugin.video.retrospect/resources/language/resource.language.sv_se/strings.po, plugin.video.retrospect/resources/lib/actions/videoaction.py, plugin.video.retrospect/resources/lib/addonsettings.py, plugin.video.retrospect/resources/lib/mediaitem.py, plugin.video.retrospect/resources/lib/menu.py, plugin.video.retrospect/resources/lib/player.py, plugin.video.retrospect/resources/lib/streams/npostream.py, plugin.video.retrospect/resources/settings.xml
This new version of Retrospect addresses a number of channel bugs. Besides this the behavior of the bitrate limiting was changed and by default no limit is set. Users can still change this via the add-on settings. There was also a fix for changed Kodi Matrix Python API.
- This add-on repository has automated code …
=> [plugin.video.retrospect] v5.2.6+matrix.1

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.nick/nickjr/chn_nickjr.py, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/channels/channel.se/svt/chn_svt.py, plugin.video.retrospect/resources/data/settings_template.xml, plugin.video.retrospect/resources/language/resource.language.en_gb/strings.po, plugin.video.retrospect/resources/language/resource.language.fi_fi/strings.po, plugin.video.retrospect/resources/language/resource.language.nb_no/strings.po, plugin.video.retrospect/resources/language/resource.language.nl_nl/strings.po, plugin.video.retrospect/resources/language/resource.language.sv_se/strings.po, plugin.video.retrospect/resources/lib/actions/videoaction.py, plugin.video.retrospect/resources/lib/addonsettings.py, plugin.video.retrospect/resources/lib/mediaitem.py, plugin.video.retrospect/resources/lib/menu.py, plugin.video.retrospect/resources/lib/player.py, plugin.video.retrospect/resources/lib/streams/npostream.py, plugin.video.retrospect/resources/settings.xml
Same as https://github.com/xbmc/repo-plugins/pull/2950 but then for Kodi Leia …
=> [plugin.video.retrospect] v5.2.6

plugin.video.cbcnews/addon.xml, plugin.video.cbcnews/resources/lib/scraper.py
=> plugin.video.cbcnews 3.0.5

plugin.video.diy/addon.xml, plugin.video.diy/changelog.txt, plugin.video.diy/readme.txt, plugin.video.diy/resources/lib/scraper.py
=> [plugin.video.diy] 3.0.12

plugin.video.retrospect/README.md, plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.json, plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.py, plugin.video.retrospect/resources/lib/actions/cleanaction.py, plugin.video.retrospect/resources/lib/actions/folderaction.py, plugin.video.retrospect/resources/lib/mediaitem.py, plugin.video.retrospect/resources/lib/urihandler.py, plugin.video.retrospect/resources/settings.xml
Matrix version of https://github.com/xbmc/repo-plugins/pull/2985 …
=> [plugin.video.retrospect] v5.2.7+matrix.1

plugin.video.catchuptvandmore/addon.xml, plugin.video.catchuptvandmore/resources/lib/channels/ch/srgssr.py, plugin.video.catchuptvandmore/resources/lib/channels/fr/01net.py, plugin.video.catchuptvandmore/resources/lib/channels/fr/bfmregion.py, plugin.video.catchuptvandmore/resources/lib/channels/fr/bfmtv.py, plugin.video.catchuptvandmore/resources/lib/channels/fr/francetvspectaclesetculture.py, plugin.video.catchuptvandmore/resources/lib/channels/fr/jack.py, plugin.video.catchuptvandmore/resources/lib/channels/fr/lcp.py, plugin.video.catchuptvandmore/resources/lib/channels/it/raiplay.py, plugin.video.catchuptvandmore/resources/lib/channels/nl/npo.py, plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py, plugin.video.catchuptvandmore/resources/lib/skeletons/fr_live.py, plugin.video.catchuptvandmore/resources/lib/skeletons/uk_live.py, plugin.video.catchuptvandmore/resources/lib/websites/allocine.py, plugin.video.catchuptvandmore/resources/m3u/live_tv_all.m3u, plugin.video.catchuptvandmore/resources/m3u/live_tv_fr.m3u, plugin.video.catchuptvandmore/resources/m3u/live_tv_uk.m3u
[Version 0.2.23]
[Fix] Live TV / Catchup TV - BFM (TV, Region, ...)
[Add] Live TV - OneNet TV (FR)
[Add] Live TV - The Pet Collective, Fail Army, ... from STV (UK)
[Fix] Catchup TV - LCP (FR)
[Update] YT-dl - Reactivate Dailymotion stream and Download mode
[Fix] Catchup TV - Jack (mycanal) (FR)
[Remove] Live TV - Mont Blanc Live TV (FR)
[Fix] Live TV - NPO channels (NL)
[Fix] Catchup TV - Raiplay (IT) - Work from jmzambon !
[Fix] Catchup TV - Spectacle et Culture (FranceTV) (FR)
[Fix] Catchup TV - Swiss national channels (CH)
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki …
=> [plugin.video.catchuptvandmore] 0.2.23

plugin.video.retrospect/addon.xml, plugin.video.retrospect/channels/channel.be/vrtnu/chn_vrtnu.py, plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py, plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.json, plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.py, plugin.video.retrospect/readme.md, plugin.video.retrospect/resources/lib/actions/cleanaction.py, plugin.video.retrospect/resources/lib/actions/folderaction.py, plugin.video.retrospect/resources/lib/mediaitem.py, plugin.video.retrospect/resources/lib/urihandler.py, plugin.video.retrospect/resources/settings.xml
This new version of Retrospect addresses a number of small issues in Retrospect. It also fixes a number of channel related bugs for kijk.nl, vrt.nu and NPO. …
=> [plugin.video.retrospect] v5.2.7

plugin.video.pbskids/addon.xml, plugin.video.pbskids/resources/lib/scraper.py
=> plugin.video.pbskids 4.0.1

.github/ISSUE_TEMPLATE/config.yml
Added a config.yml to the issue templates just like https://github.com/xbmc/repo-scripts/pull/1615  …
=> Added: config.yml to issue templates
