- plugin.video.vox-now.de/addon.xml
- plugin.video.vox-now.de/changelog.txt
- plugin.video.vox-now.de/resources/lib/rtlinteractive/client.py
UPD: skip DRM protected videos (HDS + Manifest +f4m)
> [plugin.video.vox-now.de] 2.1.3

- plugin.video.ntv-now.de/addon.xml
- plugin.video.ntv-now.de/changelog.txt
- plugin.video.ntv-now.de/resources/lib/rtlinteractive/client.py
UPD: skip DRM protected videos (HDS + Manifest +f4m)
> [plugin.video.ntv-now.de] 2.1.3

- plugin.video.rtl-now.de/addon.xml
- plugin.video.rtl-now.de/changelog.txt
- plugin.video.rtl-now.de/resources/lib/rtlinteractive/client.py
UPD: skip DRM protected videos (HDS + Manifest +f4m)
> [plugin.video.rtl-now.de] 2.1.3

- plugin.video.rtl2-now.de/addon.xml
- plugin.video.rtl2-now.de/changelog.txt
- plugin.video.rtl2-now.de/resources/lib/rtlinteractive/client.py
UPD: skip DRM protected videos (HDS + Manifest +f4m)
> [plugin.video.rtl2-now.de] 2.1.3

- plugin.video.rts/addon.py
- plugin.video.rts/addon.xml
- plugin.video.rts/changelog.txt
- plugin.video.rts/resources/lib/rtsProvider.py
- Fix xbmcaddon.Addon() call (was preventing plugin run at least from 13.2)
- Fix rss parsing on channel/item/description content when there is no img tag in
PS: the source repository referenced in the add-on page http://kodi.wiki/view/Add-on:RTS_-_Emissions_TV was deleted so I started a new one at https://github.com/trepmag/plugin.video.rts.
> [plugin.video.rts] 1.1.4

- plugin.video.ntv-now.de/addon.xml
- plugin.video.ntv-now.de/changelog.txt
- plugin.video.ntv-now.de/resources/lib/rtlinteractive/client.py
I added only the broken tag. I don't know if it's possible to support **Adobe Access** in the future...but for now this addon won't work. Maybe remove it completely from the gotham repo? (I would be okay with me)
> [plugin.video.ntv-now.de] 2.2.2

- plugin.video.vox-now.de/addon.xml
I added only the broken tag because of no support of **Adobe Access**. The addon can be removed later.
> [plugin.video.vox-now.de] 2.2.3

- plugin.video.rtl-now.de/addon.xml
- plugin.video.rtl-now.de/resources/lib/test/test_client.py
Can be removed. The successor is NOW TV. After years the provider decided finally to merge all 6 channels to one big platform.
> [plugin.video.rtl-now.de] 3.0.1

- plugin.video.ntv-now.de/addon.xml
Can be removed. The successor is NOW TV. After years the provider decided finally to merge all 6 channels to one big platform.
> [plugin.video.ntv-now.de] 3.0.1

- plugin.video.rtl2-now.de/addon.xml
Can be removed. The successor is NOW TV. After years the provider decided finally to merge all 6 channels to one big platform.
> [plugin.video.rtl2-now.de] 3.0.1

- plugin.video.vox-now.de/addon.xml
Can be removed. The successor is NOW TV. After years the provider decided finally to merge all 6 channels to one big platform.
> [plugin.video.vox-now.de] 3.0.1

- plugin.audio.rne/.gitignore
- plugin.audio.rne/addon.xml
- plugin.audio.rne/changelog.txt
- plugin.audio.rne/resources/lib/rne_api.py
Hi,
This is a new update for plugin.audio.rne over Helix branch.
Changelog:
1.0.6 (2016.04.11)
- Got the direct channels back to their original source (credits: vicglez).
jamontes.
> [plugin.audio.rne] 1.0.6

- plugin.video.odeon/README.md
- plugin.video.odeon/addon.xml
- plugin.video.odeon/changelog.txt
- plugin.video.odeon/odeon.py
- plugin.video.odeon/resources/lib/simplerequests.py
- plugin.video.odeon/resources/lib/utils.py
- use of zlib instead of gzip library
- optimize cache for short max-age responses
- change in api call
- renumbered version
> [plugin.video.odeon] 1.2.0

- plugin.video.mediathek/addon.xml
- plugin.video.mediathek/changelog.txt
This is only a version pump to seperate pre-krypton version from krypton version of this plugin. (as requested here: https://github.com/xbmc/repo-plugins/pull/757)
> [plugin.video.mediathek] v0.8.0

- plugin.video.mediathek/addon.xml
- plugin.video.mediathek/changelog.txt
- plugin.video.mediathek/default.py
- plugin.video.mediathek/mediathek/__init__.py
- plugin.video.mediathek/mediathek/arte.py
- plugin.video.mediathek/mediathek/zdf.py
- plugin.video.mediathek/resources/language/English/strings.xml
- plugin.video.mediathek/resources/language/German/strings.xml
- plugin.video.mediathek/resources/language/Italian/strings.xml
- plugin.video.mediathek/resources/settings.xml
- plugin.video.mediathek/simplexbmc.py
ZDF Completly changes its WebInterface so the plugin is rewriten to adopt that (now using JSON API, hopefully more stable)
ZDF enforces TLSv1 with SNI enabled. Support for this is added in Pyhton 2.7.9. (See here https://github.com/raptor2101/Mediathek/issues/85). Therefore i mark it as broken.
> [plugin.video.mediathek] 0.7.5 (depcrate pre krypton version)

- plugin.video.southpark_unofficial/addon.xml
- plugin.video.southpark_unofficial/changelog.txt
- plugin.video.southpark_unofficial/default.py
0.4.5 - Fixed EN/ES streams due RTMPE bad behaviour.
> [plugin.video.southpark_unofficial] 0.4.5

- plugin.video.eitb/addon.xml
- plugin.video.eitb/changelog.txt
Minor update of the plugin. The plugin id in addon.xml is fixed to be _plugin.video.eitb_ instead of the previous _plugin.video.eitb-master_, which created install errors when installing from repository. …
> [plugin.video.eitb] 1.0.5

- plugin.video.sportschau/addon.xml
This PR deprecates the older plugin.video.sportschau version in order to merge the version from membrane submitted in https://github.com/xbmc/repo-plugins/pull/903
> [plugin.video.sportschau] deprecate older version

- plugin.video.currenttime.tv/addon.py
- plugin.video.currenttime.tv/addon.xml
- plugin.video.currenttime.tv/changelog.txt
- plugin.video.currenttime.tv/resources/language/English/strings.po
- plugin.video.currenttime.tv/resources/language/Russian/strings.po
TV listing with schedule for today added …
> [plugin.video.currenttime.tv] 1.0.3

- plugin.video.snnow/addon.xml
- plugin.video.snnow/changelog.txt
- plugin.video.snnow/default.py
- plugin.video.snnow/snnow.py
- plugin.video.snnow/test.py
Neulion HLS doesn't work with the default ffmpeg probing behaviour added into Krypton (eg: probe each substream) because it sends an HTTP 403 in response to repeated key requests. To work around this, I'm forcing the user to select which bitrate they would like to watch.
> [plugin.video.snnow] 1.0.12

- plugin.video.redbull.tv/addon.xml
Marking the add-on as broken, since it throws an error when launched.
> [plugin.video.redbull.tv] 1.2.2

- plugin.video.wnbc/addon.xml
- plugin.video.wnbc/changelog.txt
- plugin.video.wnbc/readme.txt
bump t1mlib version for request timeout fix for Kodi 17.0 on Android
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
> [plugin.video.wnbc] 3.0.8

- plugin.video.wabc/addon.xml
- plugin.video.wabc/changelog.txt
- plugin.video.wabc/readme.txt
bump t1mlib version to fix request timeout in Kodi 17.0 android
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide …
> [plugin.video.wabc] 3.0.9

- plugin.video.revision3/addon.xml
Marking this plugin as broken
-Last update was 4 years ago
-I attempted to submit fixes for some broken sections (didn't receive feedback for almost 2 years)
-Author is away from our forums for 2 years
So, decided to do a full re-write and to be the new maintainer of the addon, since I use it a lot myself. The original author has been added as an author in the new addon.
My version will be submitted through another pull request.
> [plugin.video.revision3] broken

- plugin.video.fatstone/addon.xml
- plugin.video.fatstone/changelog.txt
- plugin.video.fatstone/default.py
- plugin.video.fatstone/resources/language/English/strings.xml
- plugin.video.fatstone/resources/language/Norwegian/strings.xml
- plugin.video.fatstone/resources/settings.xml
Made it possible for users to choose bitrate themselves. Since Kodi does not do it automatically. …
> [plugin.video.fatstone] 1.0.3

- plugin.video.gamekings/addon.xml
- plugin.video.gamekings/changelog.txt
- plugin.video.gamekings/resources/lib/gamekings_const.py
- plugin.video.gamekings/resources/lib/gamekings_main.py
- plugin.video.gamekings/resources/lib/gamekings_play.py
v1.2.5 (2017-03-11)
- small fix for tv-episodes
- added twitch 'Gamekings live' stream support by using the twitch plugin (much respect to authors of the plugin)
> [plugin.video.gamekings] 1.2.5

- plugin.video.aljazeera/addon.xml
Mark the add-on broken, as the website has changed and it doesn't work any longer.
> [plugin.video.aljazeera] broken

- plugin.video.tweakers/addon.py
- plugin.video.tweakers/addon.xml
- plugin.video.tweakers/changelog.txt
- plugin.video.tweakers/resources/language/Dutch/strings.po
- plugin.video.tweakers/resources/language/English/strings.po
- plugin.video.tweakers/resources/lib/tweakers_const.py
v1.1.8 (2017-03-12):
- changed 'xbmc' to 'kodi' in some text
- not using addon-name in xbmcaddon.Addon() anymore (thanks enen92)
> [plugin.video.tweakers] 1.1.8

- plugin.video.worldstarhiphop/addon.py
- plugin.video.worldstarhiphop/addon.xml
- plugin.video.worldstarhiphop/changelog.txt
- plugin.video.worldstarhiphop/resources/language/English/strings.po
- plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_const.py
v1.0.8 (2017-03-12):
- changed 'xbmc' to 'kodi' in some text
- not using addon-name in xbmcaddon.Addon() anymore (thanks enen92)
- fixed po-file
> [plugin.video.worldstarhiphop] 1.0.8

- plugin.video.dumpert/addon.xml
- plugin.video.dumpert/changelog.txt
- plugin.video.dumpert/resources/lib/dumpert_const.py
- plugin.video.dumpert/resources/lib/dumpert_play.py
v1.1.4 (2017-04-06):
- small fix to enable starting a video with a browser (chrome and 'send to kodi'-extension)
> [plugin.video.dumpert] 1.1.4

- plugin.video.gamekings/addon.py
- plugin.video.gamekings/addon.xml
- plugin.video.gamekings/changelog.txt
- plugin.video.gamekings/resources/lib/gamekings_const.py
- plugin.video.gamekings/resources/lib/gamekings_play.py
v1.2.7 (2017-04-14)
- small fix for twitch stream
- changed text from xbmc to kodi
- not using addon-name in xbmcaddon.Addon() anymore (thanks enen92)
> [plugin.video.gamekings] 1.2.7

- plugin.video.media-ccc-de/addon.xml
- plugin.video.media-ccc-de/changelog.txt
Remove the old version of the plugin from the Gotham repository, to be reintroduced in Jarvis, mostly out of TLS 1.2 compatibility concerns (all media.ccc.de servers only support TLS 1.2, some still support TLS 1.1).
- This add-on repository has automated code guideline check which could help you improve your coding. You …
> [plugin.video.media-ccc-de] 0.0.6 (Mark old versions as broken, see #1154).

- plugin.video.noco/.hg_archival.txt
- plugin.video.noco/addon.py
- plugin.video.noco/addon.xml
- plugin.video.noco/changelog.txt
- plugin.video.noco/resources/language/English/strings.xml
- plugin.video.noco/resources/language/French/strings.xml
- plugin.video.noco/resources/lib/api.py
- plugin.video.noco/resources/settings.xml
- Navigation in list of videos now shows N items per page and navigations items (Next page, Previous page)
- Add "Free content" entry to see free content of other catalogs (when logged as user) 
- Add setting to use in guest mode to see free content without being logged (some recent videos from Nolife catalog)
- Adding "History" entry to view previously seen video
- "Most popular" entry allows to choose the period of popularity (week, month, all time) 
- Adding "Top Rated" entry 
- Renaming "Playlists" entry by "Noco playlists" (only "File d'attente" inside atm)
- Adding basic support on "Noco playlists" : adding/deleting/moving videos & clear/queue playlist
- Adding "Noco favorite shows" entry with basic support (adding/deleting favorite shows, clear favorites)
- Already seen videos are …
> [plugin.video.noco] v1.0.13

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Fixed broken streaming urls, the provider switched to a new one. 
By the way i was wondering the counter on the https://kodi.tv/addon/plugins-video-add-ons/vrt-nu-0 site always says 35. Are this unique downloads or how is this counted? And is this correct for my addon since the first time i uploaded my addon with the wrong addonid. Because i am thinking 35 downloads is really really low :/. …
> [plugin.video.vrt.nu] 0.0.3

- plugin.video.nlhardwareinfo/addon.py
- plugin.video.nlhardwareinfo/addon.xml
- plugin.video.nlhardwareinfo/changelog.txt
- plugin.video.nlhardwareinfo/resources/__init__.py
- plugin.video.nlhardwareinfo/resources/language/Dutch/strings.po
- plugin.video.nlhardwareinfo/resources/language/English/strings.po
- plugin.video.nlhardwareinfo/resources/lib/__init__.py
- plugin.video.nlhardwareinfo/resources/lib/nlhardwareinfo_const.py
- plugin.video.nlhardwareinfo/resources/lib/nlhardwareinfo_list_play.py
v1.0.7 (2017-07-12)
- added listitem.setInfo video for Kodi 18 and up
- added sorting
- added context item episode info
- use requests …
> [plugin.video.nlhardwareinfo] 1.0.7

- plugin.video.zdf_de_2016/README.md
- plugin.video.zdf_de_2016/addon.xml
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/api/VideoContentResource.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/Constants.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/Mediathek.py
New version after website updates:
1.0.5 (2017-07-28)
- fix for apiToken handling (see https://github.com/generia/plugin.video.zdf_de_2016/issues/8)
- fix for streamInfoUrl not (yet) available (see https://github.com/generia/plugin.video.zdf_de_2016/issues/7)
- minor variable initialization cleanups
- This add-on …
> [plugin.video.zdf_de_2016] 1.0.5

- plugin.video.vrt.nu/addon.py
- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
- plugin.video.vrt.nu/resources/lib/kodiwrappers/sortmethod.py
Fixed a sorting bug where some content was sorted by alphabet and it shouldnt be.
Thx for merging 👍 
- Kodi …
> [plugin.video.vrt.nu] 0.0.6

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Fixed a bug where dates were not showing, also reordered the the news part where the newest now comes first.
thanks for merging
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki …
> [plugin.video.vrt.nu] 0.0.7

- plugin.video.noco/addon.py
- plugin.video.noco/addon.xml
- plugin.video.noco/changelog.txt
- plugin.video.noco/resources/language/English/strings.xml
- plugin.video.noco/resources/language/French/strings.xml
- plugin.video.noco/resources/lib/api.py
- plugin.video.noco/resources/settings.xml
Fix crash with shows without family
Add setting to hide single daily news (gathered in a single show)
> [plugin.video.noco] 1.0.16

- plugin.video.worldstarhiphop/addon.xml
- plugin.video.worldstarhiphop/changelog.txt
- plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_const.py
- plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_list.py
- plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_play.py
- plugin.video.worldstarhiphop/resources/lib/worldstarhiphop_search.py
v1.0.11 (2017-09-23)
- removed looking for video dialogue
- skipping items without videolink
> [plugin.video.worldstarhiphop] 1.0.11

- plugin.video.zdf_de_2016/addon.xml
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/RubricResource.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Teaser.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/Constants.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/Mediathek.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/MediathekFactory.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/RubricPage.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/RubricsPage.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/ShowsAzPage.py
- plugin.video.zdf_de_2016/resources/language/English/strings.po
- plugin.video.zdf_de_2016/resources/language/German/strings.po
New version after website updates:
1.0.7 (2017-10-31)
- handle new content elements after 'heute.de' relaunch
- use first teaser image for cluster folders
- added 'Startseite zdf.de' homepage processing
- fix handling '/sendungen-a-z' properly in all cases  …
> [plugin.video.zdf_de_2016] 1.0.7

- plugin.video.zdf_de_2016/addon.xml
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/VideoResource.py
An edge case slipped through and cause the addon to stop working. Sorry for the inconvenience.
1.0.8 (2017-11-02)
- hotfix for parsing api-token, if token-cache is empty (https://github.com/generia/plugin.video.zdf_de_2016/issues/13)
- This add-on repository has automated code guideline check which could help you improve …
> [plugin.video.zdf_de_2016] 1.0.8

- plugin.video.roosterteeth/addon.xml
- plugin.video.roosterteeth/changelog.txt
- plugin.video.roosterteeth/resources/language/English/strings.po
- plugin.video.roosterteeth/resources/lib/roosterteeth_const.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_list_episodes.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_main.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_play.py
+v1.3.4 (2017-12-12)
+removed looking for video dialogue
+small log fix
+added shows for Sugar Pine 7
+added recent video's for Sugar Pine 7 …
> [plugin.video.roosterteeth] 1.3.4

- plugin.video.zdf_de_2016/addon.xml
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/RubricResource.py
An edge case slipped through and cause the addon to stop working. Sorry for the inconvenience.
1.0.9 (2017-12-22)
- fix for empty cluster lists after website update …
> [plugin.video.zdf_de_2016] 1.0.9

- plugin.video.media-ccc-de/addon.xml
- plugin.video.media-ccc-de/changelog.txt
- plugin.video.media-ccc-de/resources/lib/recording.py
- plugin.video.media-ccc-de/resources/lib/test_recording.py
Bugfix to work with newly added slide streams (ignore them for now).
> [plugin.video.media-ccc-de] 0.1.2

- plugin.video.zdf_de_2016/addon.xml
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/LiveTvResource.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Teaser.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/Constants.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/player/PlayVideo.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/RubricPage.py
An edge case slipped through and cause the addon to stop working. Sorry for the inconvenience.
1.0.10 (2018-01-11)
- fix for rest-api url structure after change by zdf.de (see https://github.com/generia/plugin.video.zdf_de_2016/issues/14)
- This add-on repository has automated code guideline check which could help you …
> [plugin.video.zdf_de_2016] 1.0.10

- plugin.video.dumpert/addon.py
- plugin.video.dumpert/addon.xml
- plugin.video.dumpert/changelog.txt
- plugin.video.dumpert/resources/language/Dutch/strings.po
- plugin.video.dumpert/resources/language/English/strings.po
- plugin.video.dumpert/resources/lib/dumpert_const.py
- plugin.video.dumpert/resources/lib/dumpert_json.py
- plugin.video.dumpert/resources/lib/dumpert_list.py
- plugin.video.dumpert/resources/lib/dumpert_list_themas.py
- plugin.video.dumpert/resources/lib/dumpert_main.py
- plugin.video.dumpert/resources/lib/dumpert_play.py
- plugin.video.dumpert/resources/lib/dumpert_search.py
- plugin.video.dumpert/resources/lib/dumpert_timemachine.py
- plugin.video.dumpert/resources/settings.xml
v1.1.5 (2018-01-20)
- adding a setting for only view new video category
Kudo's to the python future package for making this possible.
- fixed scraping of some youtube videos
- This add-on repository has …
> [plugin.video.dumpert] 1.1.5

- plugin.video.cnet.podcasts/addon.xml
- plugin.video.cnet.podcasts/changelog.txt
- plugin.video.cnet.podcasts/default.py
- plugin.video.cnet.podcasts/resources/language/English/strings.po
- plugin.video.cnet.podcasts/resources/settings.xml
v1.1.6 (2018-01-20)
- removed caching
- adding a setting to only view all video category
- This add-on repository …
> [plugin.video.cnet.podcasts] 1.1.6

- plugin.video.corrieretv/addon.xml
- plugin.video.corrieretv/changelog.txt
- plugin.video.corrieretv/default.py
- plugin.video.corrieretv/resources/lib/corrieretv.py
**2.0.1**
- Added li.setInfo video for Kodi 18.
- Fixed missing thumbnails. …
> [plugin.video.corrieretv] 2.0.1

- plugin.video.tvkc/addon.xml
- plugin.video.tvkc/changelog.txt
- plugin.video.tvkc/default.py
**1.0.1**
- use setResolvedUrl for playback. …
> [plugin.video.tvkc] 1.0.1

- plugin.video.vercelliwebtv/addon.xml
- plugin.video.vercelliwebtv/changelog.txt
- plugin.video.vercelliwebtv/default.py
**1.0.1**
- updated HTML parsing due to upstream changes.
- added li.setInfo video for Kodi 18. …
> [plugin.video.vercelliwebtv] 1.0.1

- plugin.video.cbcolympics/README.md
- plugin.video.cbcolympics/addon.xml
- plugin.video.cbcolympics/changelog.txt
- plugin.video.cbcolympics/default.py
- plugin.video.cbcolympics/resources/language/English/strings.po
- plugin.video.cbcolympics/resources/settings.xml
- Added news tag to addon.xml
- Added bitrate limit setting
- Changed Python dependency to 2.24 for Kodi 16 compatibility
- Added durations to video listing
- Added start times to upcoming events
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results …
> [plugin.video.cbcolympics] v1.0.1

- plugin.video.roosterteeth/addon.xml
- plugin.video.roosterteeth/changelog.txt
- plugin.video.roosterteeth/resources/lib/roosterteeth_const.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_list_episodes.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_list_shows.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_play.py
1.3.7 (2018-02-21)
- removing non-ascii characters in title in parameters to prevent UnicodeDecodeError: 'ascii' codec can't decode ...
The error occured when doing urllib.parse.parse_qs of the parameters …
> [plugin.video.roosterteeth] 1.3.7

- plugin.video.jupiterbroadcasting/addon.xml
- plugin.video.jupiterbroadcasting/changelog.txt
- plugin.video.jupiterbroadcasting/default.py
- Restore `script.module.requests` as a dependency …
> [plugin.video.jupiterbroadcasting] 3.6.2

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Added nullcheck since it was malfunctioning when scraping.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information …
> [plugin.video.vrt.nu] 1.1.1

- plugin.video.zdf_de_2016/addon.xml
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Regex.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/RubricResource.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/TeaserLazyload.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/TeaserLazyloadResolver.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/TeaserLazyloadResource.py
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/rubrics/RubricPage.py
1.0.11 (2018-05-13)
- fix for handling lazyload teasers newly introduced by zdf.de
- performance improvements for long lists …
> [plugin.video.zdf_de_2016] 1.0.11

- plugin.video.roosterteeth/addon.xml
- plugin.video.roosterteeth/changelog.txt
- plugin.video.roosterteeth/resources/language/English/strings.po
- plugin.video.roosterteeth/resources/lib/roosterteeth_const.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_list_episodes.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_main.py
1.3.9 (2018-05-15)
- renamed series category
- prefix the titles of sponsor-only videos with an asterisk
- using news tag in addon.xml …
> [plugin.video.roosterteeth] 1.3.9

- plugin.video.ign_com/addon.xml
- plugin.video.ign_com/changelog.txt
- plugin.video.ign_com/default.py
- plugin.video.ign_com/resources/language/English/strings.po
- plugin.video.ign_com/resources/language/German/strings.po
- plugin.video.ign_com/resources/settings.xml
2.3.6 (2018-05-17)
- adding a setting to only view new video category.
- updated forum link to new thread.
- using news tag in addon.xml
- removed audio podcast category …
> [plugin.video.ign_com] 2.3.6

- plugin.video.jupiterbroadcasting/README.md
- plugin.video.jupiterbroadcasting/addon.xml
- plugin.video.jupiterbroadcasting/changelog.txt
- plugin.video.jupiterbroadcasting/jb_shows.py
- plugin.video.jupiterbroadcasting/ml_stripper.py
- plugin.video.jupiterbroadcasting/tests/test_ml_stripper.py
This updates to [Jupiter Broadcasting Kodi addon](https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting) to [3.6.3](https://github.com/JupiterBroadcasting/plugin.video.jupiterbroadcasting/releases/tag/3.6.3), which includes...
- Added default encoding to file parsing rss feeds
- By @rickyphewitt
- Updated Audio Feed URLs and moved Tech Talk Today to active show list
- By @Xmetalfanx
> [plugin.video.jupiterbroadcasting] 3.6.3

- plugin.video.gamekings/addon.xml
- plugin.video.gamekings/changelog.txt
- plugin.video.gamekings/resources/language/Dutch/strings.po
- plugin.video.gamekings/resources/language/English/strings.po
- plugin.video.gamekings/resources/lib/gamekings_const.py
- plugin.video.gamekings/resources/lib/gamekings_list.py
- plugin.video.gamekings/resources/lib/gamekings_play.py
- plugin.video.gamekings/resources/lib/gamekings_search.py
v1.2.13 (2018-05-18)
- prefix the titles of premium-only videos with an asterisk
- using news-tag in addon.xml
- showing a popup when it's a twitch live stream …
> [plugin.video.gamekings] 1.2.13

- plugin.video.liveleak/addon.xml
- plugin.video.liveleak/changelog.txt
- plugin.video.liveleak/default.py
Bugfix: Prevent errors caused by 'ghost' threads
- [?] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0
I don't know why Github thinks there are 3 commits since I did everything I could think of to squash them.
>  [plugin.video.liveleak] 1.3.5 

- plugin.video.vrt.nu/addon.py
- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/urltolivestreamservice.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Changed the mechanism for live streaming. Instead of passing a URL i need to get a token before getting a playable URL
- Kodi …
> [plugin.video.vrt.nu] 1.2.0

- plugin.video.popcorntv/addon.xml
- plugin.video.popcorntv/changelog.txt
This addon now requires youtube addon.
Updates will only be available for krypton and higher …
> [plugin.video.popcorntv] 1.0.16

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Reworked the mechanism of getting the streams because the source site changed.
> [plugin.video.vrt.nu] 1.3.0

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
The content providor changed a CSS class so i had to change as well.
Thx for merging! …
> [plugin.video.vrt.nu] V1.3.1

- plugin.video.mytv_bg/addon.py
- plugin.video.mytv_bg/addon.xml
> [plugin.video.mytv_bg] 2.0.8

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
The site im scraping from changed a css class, so i changed my scraper to scrape li elements instead of using a class selector.
thx for merging! …
> [plugin.video.vrt.nu] V1.3.2

- plugin.image.500px/addon.xml
500px shutdown their api, requested by the plugin author
> [plugin.image.500px] broken (closes #1931)

- plugin.video.spurs-tv/addon.py
- plugin.video.spurs-tv/addon.xml
- plugin.video.spurs-tv/changelog.txt
- plugin.video.spurs-tv/resources/lib/api.py
Fixes broken video listing caused by a small website change. …
> [plugin.video.spurs-tv] v2.15.1

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Changed way of selecting items due to a change in the vrt.nu site. Because of this change the A-Z menu was not working anymore which has been fixed in this update. …
> [plugin.video.vrt.nu] V1.3.4

- plugin.video.twitch/addon.xml
- plugin.video.twitch/changelog.txt
- plugin.video.twitch/resources/lib/twitch_addon/addon/converter.py
[fix] Description template UnicodeDecodeError
[chg] Use unicode punctuation space in description template
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You …
> [plugin.video.twitch] v2.3.3

- plugin.video.tweakers/addon.xml
- plugin.video.tweakers/changelog.txt
- plugin.video.tweakers/resources/lib/tweakers_const.py
- plugin.video.tweakers/resources/lib/tweakers_list.py
- plugin.video.tweakers/resources/lib/tweakers_play.py
- plugin.video.tweakers/resources/lib/tweakers_search.py
- plugin.video.tweakers/resources/settings.xml
v1.1.10 (2018-10-01)
- removing non-ascii characters in title in parameters to prevent UnicodeDecodeError: 'ascii' codec can't decode ...
The error occured when doing urllib.parse.parse_qs of the parameters
- using youtube now (website change)
- removed video quality setting as the youtube addon is used
> [plugin.video.tweakers] 1.1.10

- plugin.video.vrt.nu/addon.py
- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/urltolivestreamservice.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py
Changed way of getting a token to show some livestreams in my addon. The livestream provider expects to be logged in now for getting the livestreams. …
> [plugin.video.vrt.nu] V1.4.3

- plugin.video.rtsplaytv/addon.xml
- plugin.video.rtsplaytv/resources/data/youtube_channels.json
- plugin.video.rtsplaytv/resources/language/resource.language.de_de/strings.po
- plugin.video.rtsplaytv/resources/language/resource.language.en_gb/strings.po
- plugin.video.rtsplaytv/resources/language/resource.language.fr_fr/strings.po
- plugin.video.rtsplaytv/resources/lib/rtsplaytv.py
- plugin.video.rtsplaytv/resources/settings.xml
New release of `plugin.video.rtsplaytv` (version 1.1.0).
Changes:
- Add support to browse and watch the official RTS YouTube channels. …
> [plugin.video.rtsplaytv] v1.1.0

- plugin.video.zdf_de_lite/addon.xml
plugin.video.zdf_de_lite was marked broken in a higher branch (isengard), but @MartijnKaijser completely removed it at fdf87447 from the isengard branch.
Because of that the repo generator placed non broken version 2.1.3 into isengard and jarvis repo.
- This add-on repository has automated code guideline check which could …
> [plugin.video.zdf_de_lite] 2.2.3 (broken)

- plugin.video.pcloud-video-streaming/addon.py
- plugin.video.pcloud-video-streaming/addon.xml
- plugin.video.pcloud-video-streaming/changelog.txt
- plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
Fixed issue #18: if the PCloud username (i.e. the email address) contained nonstandard symbols such as for example a "+", logon would fail.
> [plugin.video.pcloud-video-streaming] 1.2.11

- plugin.video.tyt/addon.xml
- plugin.video.tyt/changelog.txt
- plugin.video.tyt/main.py
- plugin.video.tyt/resources/lib/modules/scrape.py
Changed playback reference. This method relies on JW player reference which is consistent.  Relying on download links was unstable due to poor website QC.
> [plugin.video.tyt] 3.0.5

- plugin.video.dumpert/addon.xml
- plugin.video.dumpert/changelog.txt
- plugin.video.dumpert/resources/lib/dumpert_const.py
v1.1.7 (2018-12-28)
- marked addon broken for gotham
> [plugin.video.dumpert] 1.1.7

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
- plugin.video.vrt.nu/resources/lib/helperobjects/apidata.py
- plugin.video.vrt.nu/resources/lib/helperobjects/streamurls.py
- plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/actions.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py
- plugin.video.vrt.nu/resources/settings.xml
- plugin.video.vrt.nu/service.py
- Bug fix where the vrt token would be stored in a wrong format
- Inputstream helper for easier widevine installation (thanks for tip kodi team)
- Token resets when settings are being changed
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of …
> [plugin.video.vrt.nu] V1.5.2

- plugin.video.zdf_de_2016/addon.py
- plugin.video.zdf_de_2016/addon.xml
- plugin.video.zdf_de_2016/de/generia/kodi/plugin/backend/zdf/Teaser.py
1.0.15 (2019-02-11)
- fix 'Live TV' and 'Sendungen A-Z' (github issue #16) …
> [plugin.video.zdf_de_2016] 1.0.15

- plugin.video.gamekings/addon.xml
- plugin.video.gamekings/changelog.txt
- plugin.video.gamekings/resources/lib/gamekings_const.py
v1.2.14 (2019-02-23)
- marking the addon broken for gotham. A working version (1.2.15) will be available in Leia (Kodi 18)
> [plugin.video.gamekings] 1.2.14

- plugin.video.vrt.nu/addon.py
- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Fixed error for people who are roaming, also using the vrt nu api to get video's which will greatly improve stability. Also implemented fall back mechanism for stream selection …
> [plugin.video.vrt.nu] V1.6.0

- plugin.video.mediathekview/addon.xml
- plugin.video.mediathekview/resources/lib/kodi/kodiaddon.py
- plugin.video.mediathekview/resources/lib/mvupdate.py
- plugin.video.mediathekview/resources/lib/mvutils.py
- plugin.video.mediathekview/resources/lib/updater.py
- Implemented Workaround for broken `gzip` module support in Kodi 18 running on Android
- Fixed crash in `mvupdate` tool when invoked with MySQL support
- Improved compatibility with future Kodi versions with Python 3 support
- Fixed module exception due to case error
- This add-on repository has automated code guideline …
> [plugin.video.mediathekview] 0.6.2

- plugin.video.vrt.nu/README.md
- plugin.video.vrt.nu/addon.py
- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/helperobjects/apidata.py
- plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py
- plugin.video.vrt.nu/resources/lib/helperobjects/streamurls.py
- plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
- plugin.video.vrt.nu/resources/lib/kodiwrappers/sortmethod.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/actions.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
- plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
- plugin.video.vrt.nu/service.py
- Remove the **inputstream.adaptive** requirement for Krypton
- A set of fixes to accommodate Travis CI :-)
Due to the addition of a requirement, our addon fails to update on Kodi Krypton.
The requirement is not needed since we rely on **script.module.inputstreamhelper**.
> [plugin.video.vrt.nu] 1.7.1

- plugin.video.jafc/addon.xml
- plugin.video.jafc/changelog.txt
- plugin.video.jafc/resources/language/resource.language.en_gb/strings.po
- plugin.video.jafc/resources/lib/cache.py
- plugin.video.jafc/resources/lib/kodilogging.py
- plugin.video.jafc/resources/lib/kodiutils.py
- plugin.video.jafc/resources/lib/plugin.py
- plugin.video.jafc/resources/lib/search.py
- plugin.video.jafc/resources/settings.xml
Updated to (hopefully) be Python 3 compatible 
Removed all special:// uris
Changed streams from M3U8 to MPD
> [plugin.video.jafc] 1.1.0

- plugin.video.roosterteeth/addon.xml
- plugin.video.roosterteeth/changelog.txt
- plugin.video.roosterteeth/resources/lib/roosterteeth_const.py
1.3.11 (2019-06-09)
- marking the addon broken for gotham. A working version will be available in Leia (Kodi 18)
> [plugin.video.roosterteeth] 1.3.11

- plugin.video.glwiz/addon.xml
Marking the plugin as broken as I can no longer maintain it.
> [plugin.video.glwiz] v1.1.4 deprecated, no longer maintained.

- plugin.video.southpark_unofficial/addon.xml
- plugin.video.southpark_unofficial/changelog.txt
- plugin.video.southpark_unofficial/southpark.py
Fixed issue with http to https redirection …
> [plugin.video.southpark_unofficial] 0.5.1

- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/lib/kodiwrapper.py
Emergency release for Kodi 17 which does not support `offscreen=True`.
Please merge ASAP.
> [plugin.video.vrt.nu] v2.1.1

- plugin.video.xumotv/addon.xml
- plugin.video.xumotv/resources/language/resource.language.en_gb/strings.po
- plugin.video.xumotv/resources/lib/xumotv.py
Dependent on module uEPG v.1.0.6 …
> [plugin.video.xumotv] 1.0.3

- plugin.video.nhklive/addon.xml
- plugin.video.nhklive/changelog.txt
- plugin.video.nhklive/resources/lib/scraper.py
NHK Live stopped working because page has changed, this is fix to make it work again. …
> [plugin.video.nhklive] v3.0.8

- plugin.video.southpark_unofficial/addon.xml
- plugin.video.southpark_unofficial/changelog.txt
- plugin.video.southpark_unofficial/southpark.py
Added southparkstudios.co.uk and fixed issue with season 23 on southparkstudios.nu and video playback on southpark.de
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboa …
> [plugin.video.southpark_unofficial] 0.5.4

- plugin.video.southpark_unofficial/addon.xml
- plugin.video.southpark_unofficial/changelog.txt
- plugin.video.southpark_unofficial/southpark.py
fixed issue with Debian buster (Kodi 17.6) missing xbmcgui.ListItem.setIsFolder method. …
> [plugin.video.southpark_unofficial] 0.5.5

- plugin.video.southpark_unofficial/addon.xml
- plugin.video.southpark_unofficial/changelog.txt
- plugin.video.southpark_unofficial/southpark.py
Fixed issue with Kodi 16 and Python 2.x …
> [plugin.video.southpark_unofficial] 0.5.6

- plugin.video.southpark_unofficial/addon.xml
- plugin.video.southpark_unofficial/changelog.txt
- plugin.video.southpark_unofficial/southpark.py
fixed issue with DE random episode. …
> [plugin.video.southpark_unofficial] 0.5.7

- plugin.video.themoviedb.helper/addon.xml
- plugin.video.themoviedb.helper/resources/lib/container.py
- plugin.video.themoviedb.helper/resources/lib/requestapi.py
- plugin.video.themoviedb.helper/resources/lib/utils.py
Fixes some string encoding/decoding errors for diacritics in infolabels passed to plugin paramstring. …
> [plugin.video.themoviedb.helper] 1.0.5

- plugin.video.mdrmediathek/addon.xml
The PR marks the add-on as broken. The content is now included in the ARD Mediathek.
> [plugin.video.mdrmediathek] 1.1.2

- plugin.video.zoneminder/README.md
- plugin.video.zoneminder/addon.xml
- plugin.video.zoneminder/changelog.txt
- plugin.video.zoneminder/resources/language/resource.language.en_gb/strings.po
- plugin.video.zoneminder/resources/settings.xml
- plugin.video.zoneminder/zoneminder.py
Update ZoneMinder plugin to allow users to modify the cgi-bin path. The RedHat version of ZoneMinder uses a different path from other distros so we need to make an option for this.
> [plugin.video.zoneminder] 2.0.1

- plugin.video.pcloud-video-streaming/addon.xml
- plugin.video.pcloud-video-streaming/changelog.txt
- plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
Fixed issue #23: fixed crash on Android and Mac when performing first network operation, on Kodi 18.
> [plugin.video.pcloud-video-streaming] 1.3.2

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/lib/plugin.py
- **General**
- Version number: 5.0.2
- Fix on demand section
> [plugin.video.rtpplay] 5.0.2

- plugin.video.svtplay/addon.xml
- plugin.video.svtplay/resources/lib/listing/router.py
Quick bug fix for unplayable items. …
> [plugin.video.svtplay] 5.1.4

- plugin.video.conversasabenfica/README.md
- plugin.video.conversasabenfica/addon.xml
- plugin.video.conversasabenfica/changelog.txt
- plugin.video.conversasabenfica/resources/language/README.md
- plugin.video.conversasabenfica/resources/language/resource.language.en_gb/strings.po
- plugin.video.conversasabenfica/resources/language/resource.language.pt_pt/strings.po
- plugin.video.conversasabenfica/resources/lib/kodiutils.py
- plugin.video.conversasabenfica/resources/lib/plugin.py
- plugin.video.conversasabenfica/resources/lib/youtubelib.py
- plugin.video.conversasabenfica/resources/settings.xml
- **General**
- Add-on name: Conversas à Benfica
- Add-on ID: plugin.video.conversasabenfica
- Version number: 1.1.0
- URL: 
Conversas à Benfica... Easy![CR]For the ones who love Benfica and (almost) everything around it.[CR]Everything related with the played football and the stands.[CR]History, laughs and beers![CR]ONE LIFE, ONE GAME!
Support for python3
> [plugin.video.conversasabenfica] 1.1.0

- plugin.video.dumpert/addon.xml
- plugin.video.dumpert/changelog.txt
- plugin.video.dumpert/resources/lib/dumpert_const.py
- plugin.video.dumpert/resources/lib/dumpert_main.py
v1.1.10 (2019-12-12) (thanks for the help Nixxor)
- Removed Top as it is basically the same as Daily Top
- Using different url for DumpertTV so that most recent items are at the top of the list
- Moved DumpertTV up in the main list
> [plugin.video.dumpert] 1.1.10

- plugin.audio.deejayIt.reloaded/addon.xml
- plugin.audio.deejayIt.reloaded/changelog.txt
Plugin update: marking as broken, to be then removed from repository. A new version will come from a different repository. …
> [plugin.audio.deejayIt.reloaded] 1.6.3 - broken

- plugin.library.node.editor/addon.xml
- plugin.library.node.editor/resources/lib/rules.py
A small miss on the last update. Fixes operators and matches in parent nodes.
> [plugin.library.node.editor] 1.0.11

- plugin.video.pcloud-video-streaming/addon.py
- plugin.video.pcloud-video-streaming/addon.xml
- plugin.video.pcloud-video-streaming/changelog.txt
- plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py
* Fixed issue #24: it is now possible to also sort by date. …
> [plugin.video.pcloud-video-streaming] 1.4.0

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/lib/channels.py
- **General**
- Version number: 5.0.3
- Fix live
> [plugin.video.rtpplay] 5.0.3

- plugin.audio.radio_de/addon.xml
- plugin.audio.radio_de/changelog.txt
- plugin.audio.radio_de/resources/language/English/strings.po
- plugin.audio.radio_de/resources/lib/api.py
- plugin.audio.radio_de/resources/lib/plugin.py
- plugin.audio.radio_de/resources/settings.xml
- **General**
- Version number: 2.4.2
- URL: 
Music plugin to access over 7000 international radio broadcasts from rad.io, radio.de, radio.fr and radio.pt[CR]Currently features[CR]- English, german and french translated[CR]- Browse stations by location, genre, topic, country, city and language[CR]- Search for stations[CR]- 115 genres, 59 topics, 94 countrys, 1010 citys, 63 languages
v2.4.2 (9/2/2020)
[add] sort methods for categories
[add] setting to prefer http connections over https if http streams are available
[fix] use sys.version_info[0] for compatibility with python2.6
> [plugin.audio.radio_de] 2.4.2

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/lib/plugin.py
- **General**
- Version number: 5.0.4
- URL: 
- Fix for some on-demand streams
> [plugin.video.rtpplay] 5.0.4

- plugin.video.hbogoeu/README.md
- plugin.video.hbogoeu/addon.xml
- plugin.video.hbogoeu/hbogolib/handler.py
- **General**
- Add-on name: hGO EU
- Add-on ID: plugin.video.hbogoeu
- Version number: 2.3.10
- Kodi/repository version: leia
- URL: https://github.com/arvvoid/plugin.video.hbogoeu
Simple, Kodi add-on to access HBO® Go EU content. (This add-on is not officially commissioned/supported by HBO®.)
Important, HBO® Go must be paid for!!!  You need a valid account!
Register on the official HBO® Go website for your region.
Read the disclaimer!
Curently support: Bosnia and Herzegovina, Bulgaria, Croatia, Czech Republic, Hungary, Macedonia, Montenegro, Polonia, Portugal, Romania, Serbia, Slovakia, Slovenija, Spain, Norway, Denmark, Sweden, Finland
To report bugs or request assistence with the add-on go to: https://github.com/arvvoid/plugin.video.hbogoeu
- Fixed encoding error …
> [plugin.video.hbogoeu] 2.3.10

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/lib/channels.py
- plugin.video.rtpplay/resources/lib/kodiutils.py
- plugin.video.rtpplay/resources/lib/plugin.py
- **General**
- Version number: 5.0.5
- URL: 
- Fix live and ondemand
> [plugin.video.rtpplay] 5.0.5

- plugin.video.rtpplay/addon.xml
- **General**
- Version number: 5.0.6
- URL: 
- Addon is now supported in matrix
> [plugin.video.rtpplay] 5.0.6

- plugin.video.hbogoeu/README.md
- plugin.video.hbogoeu/addon.xml
- plugin.video.hbogoeu/hbogolib/constants.py
- plugin.video.hbogoeu/hbogolib/handler.py
- plugin.video.hbogoeu/hbogolib/handlereu.py
- plugin.video.hbogoeu/hbogolib/handlersp.py
This is the same as https://github.com/xbmc/repo-plugins/pull/2808 just for Matrix
- **General**
- Add-on name: hGO EU
- Add-on ID: plugin.video.hbogoeu
- Version number: 2.5.5+matrix.1
- URL: https://github.com/arvvoid/plugin.video.hbogoeu
Simple, Kodi add-on to access HBO® Go EU content. (This add-on is not officially commissioned/supported by HBO®.)
Important, HBO® Go must be paid for!!!  You need a valid account!
Register on the official HBO® Go website for your region.
Read the disclaimer!
Curently support: Bosnia and Herzegovina, Bulgaria, Croatia, Czech Republic, Hungary, Macedonia, Montenegro, Polonia, Portugal, Romania, Serbia, Slovakia, Slovenija, Spain, Norway, Denmark, Sweden, Finland
To report bugs or request assistence …
> [plugin.video.hbogoeu] 2.5.5+matrix.1

- plugin.video.vimeo/addon.xml
- plugin.video.vimeo/resources/lib/vimeo/api.py
Fixed a playback issue with HLS streams on macOS.
Details: https://github.com/jaylinski/kodi-addon-vimeo/issues/31
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard) …
> [plugin.video.vimeo] 5.1.4

- plugin.audio.radio_de/addon.xml
- plugin.audio.radio_de/changelog.txt
- plugin.audio.radio_de/resources/lib/api.py
- plugin.audio.radio_de/resources/lib/plugin.py
- **General**
- Version number: 3.0.0
- URL: https://github.com/XBMC-Addons/plugin.audio.radio_de
Music plugin to access over 7000 international radio broadcasts from rad.io, radio.de, radio.fr and radio.pt[CR]Currently features[CR]- English, german and french translated[CR]- Browse stations by location, genre, topic, country, city and language[CR]- Search for stations[CR]- 115 genres, 59 topics, 94 countrys, 1010 citys, 63 languages
3.0.0 (12/4/2020)
[fix] playlist based stations (backport)
[fix] ratings (backport)
[new] removed python3 compatibility
[new] automated submissions to repository
> [plugin.audio.radio_de@gotham] 3.0.0

- plugin.video.vimcasts/addon.xml
- **General**
- Add-on name: VimCasts
- Add-on ID: plugin.video.vimcasts
- Version number: 1.3.0
- URL: https://github.com/XBMC-Addons/plugin.video.vimcasts
Vimcasts publishes free screencasts about Vim, the text editor. Vim has been around in one form or another for over 20 years. The learning curve is famously difficult, but those who manage to climb it insist that nothing can match Vim's modal editing model for speed and efficiency.[CR][CR]The patterns of use that make a Vim master productive are not easily discovered. Trial and error will get you so far, but the best way to learn is to watch an experienced Vim user at work. By providing short videos with digestible advice, Vimcasts gives you something you can take away and use …
> [plugin.video.vimcasts@gotham] 1.3.0

- plugin.audio.shoutcast/addon.xml
- plugin.audio.shoutcast/changelog.txt
- **General**
- Add-on name: SHOUTcast
- Add-on ID: plugin.audio.shoutcast
- Version number: 2.5.0
- URL: https://github.com/XBMC-Addons/plugin.audio.shoutcast
With this Add-on you can browse more than 50.000 free internet radio stations. Current Features:[CR]- Top 500 Stations[CR]- Browse by genre (and subgenre if enabled in settings)[CR]- Search Station by name[CR]- Search Stations by current playing track[CR]- You can manage a "My Stations"-list[CR]- bitrate and amount of listeners visible and sortable[CR]- 500 Stations on each Page (can be changed in the settings)[CR]- uses cache (24h genre, 1h station listings)
2.5.0 (12.4.2020)
- Automated submissions to gotham branch
- Addon.xml cosmetics
> [plugin.audio.shoutcast@gotham] 2.5.0

- plugin.audio.radio_de/addon.xml
- plugin.audio.radio_de/changelog.txt
- plugin.audio.radio_de/resources/lib/api.py
- plugin.audio.radio_de/resources/lib/plugin.py
- **General**
- Version number: 3.0.1
- URL: https://github.com/XBMC-Addons/plugin.audio.radio_de
Music plugin to access over 7000 international radio broadcasts from rad.io, radio.de, radio.fr and radio.pt[CR]Currently features[CR]- English, german and french translated[CR]- Browse stations by location, genre, topic, country, city and language[CR]- Search for stations[CR]- 115 genres, 59 topics, 94 countrys, 1010 citys, 63 languages
3.0.1 (13/4/2020)
- [new] Use internal playlist resolver also in custom stations (backport)
> [plugin.audio.radio_de@gotham] 3.0.1

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/lib/plugin.py
- **General**
- Version number: 5.0.7+matrix.1
- Addon is now supported in matrix
> [plugin.video.rtpplay@matrix] 5.0.7+matrix.1

- plugin.audio.radio_de/addon.xml
- plugin.audio.radio_de/changelog.txt
- plugin.audio.radio_de/resources/lib/api.py
- plugin.audio.radio_de/resources/lib/plugin.py
- **General**
- Version number: 3.0.1+matrix.1
- URL: https://github.com/XBMC-Addons/plugin.audio.radio_de
Music plugin to access over 7000 international radio broadcasts from rad.io, radio.de, radio.fr and radio.pt[CR]Currently features[CR]- English, german and french translated[CR]- Browse stations by location, genre, topic, country, city and language[CR]- Search for stations[CR]- 115 genres, 59 topics, 94 countrys, 1010 citys, 63 languages
v3.0.1+matrix.1 (13/4/2020)
[new] Use internal playlist resolver also in custom stations
> [plugin.audio.radio_de@matrix] 3.0.1+matrix.1

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/lib/plugin.py
- **General**
- Version number: 5.0.7
- Addon is now supported in matrix
> [plugin.video.rtpplay@krypton] 5.0.7

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/language/resource.language.en_gb/strings.po
- plugin.video.rtpplay/resources/language/resource.language.pt_pt/strings.po
- plugin.video.rtpplay/resources/lib/plugin.py
- **General**
- Version number: 5.0.8+matrix.1
- Add #estudoemcasa (school classes during lockdown)
> [plugin.video.rtpplay@matrix] 5.0.8+matrix.1

- plugin.video.rtpplay/addon.xml
- plugin.video.rtpplay/resources/language/resource.language.en_gb/strings.po
- plugin.video.rtpplay/resources/language/resource.language.pt_pt/strings.po
- plugin.video.rtpplay/resources/lib/plugin.py
- **General**
- Version number: 5.0.8
- Add #estudoemcasa (school classes during lockdown)
> [plugin.video.rtpplay@krypton] 5.0.8

- plugin.audio.radio_de/addon.xml
- plugin.audio.radio_de/changelog.txt
- **General**
- Version number: 3.0.3+matrix.6
- URL: https://github.com/XBMC-Addons/plugin.audio.radio_de
Music plugin to access over 30000 international radio broadcasts from rad.io, radio.de, radio.fr, radio.pt and radio.es[CR]Currently features[CR]- English, german, french translated[CR]- Browse stations by location, genre, topic, country, city and language[CR]- Search for stations[CR]- 115 genres, 59 topics, 94 countrys, 1010 citys, 63 languages
v3.0.3+matrix.6 (1/5/2020)
[fix] Custom stations if the url is not a playlist
[new] Spanish website radio.es and improved translations
[new] screenshot support for addon-website
> [plugin.audio.radio_de@matrix] 3.0.3+matrix.6

- plugin.video.roosterteeth/addon.xml
- plugin.video.roosterteeth/changelog.txt
- plugin.video.roosterteeth/resources/language/resource.language.en_gb/strings.po
- plugin.video.roosterteeth/resources/lib/roosterteeth_const.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_list_episodes.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_list_serie_seasons.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_list_series.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_main.py
- plugin.video.roosterteeth/resources/lib/roosterteeth_play.py
- plugin.video.roosterteeth/resources/settings.xml
1.5 (2020-05-02)
- dynamic channels instead of hardcoded channels
- set initial sorting, changing the sort order in Kodi now seems to actually do something
- added channel shows
- changes due to sponsership to First membership change
> [plugin.video.roosterteeth] 1.5

- plugin.video.vrt.nu/README.md
- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
- plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
- plugin.video.vrt.nu/resources/lib/favorites.py
- plugin.video.vrt.nu/resources/lib/iptvmanager.py
- plugin.video.vrt.nu/resources/lib/metadata.py
- plugin.video.vrt.nu/resources/lib/resumepoints.py
- plugin.video.vrt.nu/resources/lib/streamservice.py
- plugin.video.vrt.nu/resources/lib/tokenresolver.py
- plugin.video.vrt.nu/resources/lib/utils.py
- plugin.video.vrt.nu/resources/settings.xml
- **General**
- Add-on name: VRT NU
- Add-on ID: plugin.video.vrt.nu
- Version number: 2.3.5+matrix.1
- URL: https://github.com/add-ons/plugin.video.vrt.nu
VRT NU is the video-on-demand platform of the Flemish public broadcaster (VRT).
- Track the programs you like
- List all videos alphabetically by program, category, channel or feature
- Watch live streams from Eén, Canvas, Ketnet, Ketnet Junior and Sporza
- Discover recently added or soon offline content
- Browse the online TV guides or search VRT NU
*The VRT NU add-on is not endorsed by VRT, and is provided 'as is' without any warranty of any kind.*
v2.3.5 (2020-05-27)
- Fix watching VRT NU abroad
- Improve and fix user authentication
- Add support for playing from the Guide with …
> [plugin.video.vrt.nu@matrix] 2.3.5+matrix.1

- plugin.video.vrt.nu/README.md
- plugin.video.vrt.nu/addon.xml
- plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
- plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
- plugin.video.vrt.nu/resources/lib/favorites.py
- plugin.video.vrt.nu/resources/lib/iptvmanager.py
- plugin.video.vrt.nu/resources/lib/metadata.py
- plugin.video.vrt.nu/resources/lib/resumepoints.py
- plugin.video.vrt.nu/resources/lib/streamservice.py
- plugin.video.vrt.nu/resources/lib/tokenresolver.py
- plugin.video.vrt.nu/resources/lib/utils.py
- plugin.video.vrt.nu/resources/settings.xml
- **General**
- Add-on name: VRT NU
- Add-on ID: plugin.video.vrt.nu
- Version number: 2.3.5
- URL: https://github.com/add-ons/plugin.video.vrt.nu
VRT NU is the video-on-demand platform of the Flemish public broadcaster (VRT).
- Track the programs you like
- List all videos alphabetically by program, category, channel or feature
- Watch live streams from Eén, Canvas, Ketnet, Ketnet Junior and Sporza
- Discover recently added or soon offline content
- Browse the online TV guides or search VRT NU
*The VRT NU add-on is not endorsed by VRT, and is provided 'as is' without any warranty of any kind.*
v2.3.5 (2020-05-27)
- Fix watching VRT NU abroad
- Improve and fix user authentication
- Add support for playing from the Guide with IPTV …
> [plugin.video.vrt.nu@krypton] 2.3.5

- plugin.video.pcloud-video-streaming/addon.py
- plugin.video.pcloud-video-streaming/addon.xml
- plugin.video.pcloud-video-streaming/changelog.txt
Fixed issue #27: In certain locales (such as en-nz), the "Back to parent folder" list item would sort after folders starting with a number. Now it sorts correctly at the top of the list.
> [plugin.video.pcloud-video-streaming] 1.4.2

- plugin.audio.radiobrowser/addon.xml
- plugin.audio.radiobrowser/changelog.txt
- plugin.audio.radiobrowser/main.py
- plugin.audio.radiobrowser/resources/language/resource.language.bg_bg/strings.po
This is an update of the plugin audio radiobrowser to version 1.2.0 with the following changes:
* use new api as documented at https://api.radio-browser.info
* stop play before start again to fix play only every second time bug
* use xbmc log instead of print
> [plugin.audio.radiobrowser] 1.2.0

- service.upnext/addon.xml
- service.upnext/resources/lib/player.py
- **General**
- Add-on name: Up Next
- Add-on ID: service.upnext
- Version number: 1.1.2
- Kodi/repository version: leia
- URL: https://github.com/im85288/service.upnext
A service add-on that shows a Netflix-style notification for watching the next episode. After a few automatic iterations it asks the user if he is still there watching.
A lot of existing add-ons already integrate with this service out-of-the-box.
- Bug fix for change from sleep to waitForAbort using seconds and not ms
- Avoid conflict with external players
- Restore "Ignore Playlist" option
- Fix a known Kodi bug related to displaying hours
- Improvements to endtime visualization
- New translations for Hindi and Romanian
- Translation updates to Hungarian and Spanish
- Add notification_offset for …
> [service.upnext@leia] 1.1.2
